tool/doc.dart

Depended on by: https://github.com/dart-lang/linter/pull/2115
Read the linked PR for more information, but this implements some minor cleanup and organizational changes for the proposed new site design. 
As I mentioned on the other PR, please feel free to to present heavy feedback and large changes.

Updated doc gen for proposed new site design

---

lib/src/rules/unnecessary_this.dart
test/rules/unnecessary_this.dart

make `unnecessary_this` null-aware

---

lib/src/rules/unnecessary_lambdas.dart
test/_data/unnecessary_lambdas/src/a.dart
test/integration_test.dart

See: https://github.com/dart-lang/linter/pull/2172/files#r451851058

improve check for deferred imports

---

lib/src/rules/unsafe_html.dart
pubspec.yaml

add unique codes for unsafe_html variations

---

lib/src/rules/unsafe_html.dart
pubspec.yaml

Revert of https://github.com/dart-lang/linter/pull/2183.

Revert unique `unsafe_html` error codes

---

lib/src/rules/unsafe_html.dart
pubspec.yaml

unique `unsafe_html` error codes

---

AUTHORS

Add Nolan to AUTHORS

---

tool/baseline/pana.json
tool/pana_baseline.dart

See: https://github.com/dart-lang/pana/issues/768

update pana scoring

---

lib/src/rules/unawaited_futures.dart
test/rules/unawaited_futures.dart

check for Future subtypes

---

lib/src/util/leak_detector_visitor.dart
test/_data/close_sinks/src/a.dart

fix `this` prefixed access for `close_sinks`

---

lib/src/rules/prefer_final_fields.dart

update to preferred analyzer API

---

lib/src/rules/flutter_style_todos.dart

add Flutter doc guidance to clarify $user in `flutter_style_todos`

---

test/rules/sort_child_properties_last.dart

See: https://dart-review.googlesource.com/c/sdk/+/161624

+ test for nested reports

---

lib/src/rules/public_member_api_docs.dart
test/_data/public_member_api_docs/lib/a.dart
test/integration_test.dart

add `public_member_apis` check for generic type aliases

---

tool/travis.sh

Fixes travis script to exit w/  test result exit code.
See: https://github.com/dart-lang/linter/pull/2252#issue-495177133
/cc @grouma @bwilkerson

cache and set test result exit code

---

lib/src/rules/avoid_type_to_string.dart

Fixes benchmark bot breakage: https://travis-ci.org/github/dart-lang/linter/jobs/731431248

guard against null target types

---

tool/travis.sh

fix exit code setting

---

test/rules/avoid_type_to_string.dart

regression test for extensions on non-interface types

---

lib/src/rules/public_member_api_docs.dart

re-work lib dir checking

---

lib/src/rules/cast_nullable_to_non_nullable.dart
lib/src/rules/null_check_on_nullable_type_parameter.dart
lib/src/rules/tighten_type_of_initializing_formals.dart
lib/src/rules/unnecessary_nullable_for_final_variable_declarations.dart

See: #2259.
/cc @scheglov @bwilkerson @a14n

short circuit node processor registry outside NNBD

---

lib/src/rules/avoid_init_to_null.dart

feature check tweak

---

lib/src/rules/overridden_fields.dart
test/rules/experiments/nnbd/rules/overridden_fields.dart

Fixes #2269
/cc @bwilkerson @srawlins @a14n

allow overriding abstract fields in NNBD

---

lib/src/rules/unnecessary_nullable_for_final_variable_declarations.dart
test/rules/experiments/nnbd/rules/unnecessary_nullable_for_final_variable_declarations.dart

relax unnecessary_nullable_for_final_variable_declarations to allow dynamic

---

pubspec.yaml

widen markdown dep

---

analysis_options.yaml

enable `sort_pub_dependencies`

---

lib/src/rules/valid_regexps.dart

Fixes: #2289 
/cc @lrhn @bwilkerson

prefer raw strings in `valid_regexps` example

---

test/mock_packages/flutter/lib/foundation.dart
test/mock_packages/flutter/lib/src/foundation/platform.dart
test/mock_packages/flutter/lib/src/widgets/framework.dart
test/mock_packages/flutter/lib/src/widgets/navigator.dart
test/mock_packages/flutter/lib/src/widgets/placeholder.dart
test/mock_packages/flutter/lib/widgets.dart

more flutter SDK member mocks

---

test/mock_packages/flutter/lib/src/widgets/navigator.dart

Follow-up from #2291.
Sorry for the noise.

fixed NavigatorState

---

test/mock_packages/flutter/lib/src/widgets/navigator.dart

more navigator mocking

---

lib/src/rules/unnecessary_null_checks.dart
test/rules/experiments/nnbd/rules/unnecessary_null_checks.dart

Trying to apply `unnecessary_null_checks` in flutter I face some pattern that looks ok. See added tests.

allow some patterns in unnecessary_null_checks

---

lib/src/rules/unnecessary_null_checks.dart

fix NPE in getExpectedType

---

test/integration/lines_longer_than_80_chars.dart

fix test description

---

.travis.yml
tool/travis.sh

A stab at fixing build failures:
https://travis-ci.org/github/dart-lang/linter/jobs/739980709
I'll bump us back to the dev channel when the fix to https://github.com/dart-lang/sdk/issues/43979 is in a build.

[TBR] disable analytics

---

README.md

Let's try the GH actions badge.

migrate to the GH actions build status badge

---

tool/travis.sh

/cc  @devoncarew @bwilkerson 
Fixes: #2315

run tests w/o coverage token

---

.github/workflows/build.yaml

See: https://github.com/dart-lang/cli_util/pull/51.
/cc @kevmoo @devoncarew

cron schedule a weekly build

---

lib/src/rules/unnecessary_null_checks.dart
test/experiments_test.dart
test/rule_test.dart
test/rules/experiments/nnbd/rules/unnecessary_null_checks.dart

Fixes #2326 
/cc @scheglov @bwilkerson @a14n

npe fixes for `unnecessary_null_checks`

---

lib/src/utils.dart
test/utils_test.dart

Fixes #2331 
/cc @bwilkerson @kevmoo

support leading underscores in package names

---

lib/src/rules/prefer_constructors_over_static_methods.dart
test/rules/prefer_constructors_over_static_methods.dart

check for type assignability in static methods

---

lib/src/rules/avoid_equals_and_hash_code_on_mutable_classes.dart
lib/src/rules/lines_longer_than_80_chars.dart
test/integration/lines_longer_than_80_chars.dart

fix error descriptions (drop screaming caps)

---

pubspec.yaml
test/integration/lines_longer_than_80_chars.dart

analyzer dep bump

---

lib/src/rules/unnecessary_statements.dart

drop unnecessary `new`

---

CHANGELOG.md
lib/src/util/score_utils.dart
lib/src/version.dart
pubspec.yaml
tool/crawl.dart

Prepare for https://github.com/dart-lang/http/issues/375

Pass a Uri to package:http APIs

---

test/validate_format_test.dart

migrate to `dart format`

---

tool/scorecard.dart

remove unneeded ignore

---

lib/src/rules/avoid_implementing_value_types.dart
lib/src/rules/avoid_slow_async_io.dart
lib/src/rules/close_sinks.dart
lib/src/rules/constant_identifier_names.dart
lib/src/rules/join_return_with_assignment.dart
lib/src/rules/only_throw_errors.dart
lib/src/rules/prefer_collection_literals.dart
lib/src/rules/prefer_constructors_over_static_methods.dart
lib/src/rules/unawaited_futures.dart
lib/src/rules/unrelated_type_equality_checks.dart

doc cleanup of lingering unnecessary `new`s

---

test/rules/non_constant_identifier_names.dart

add tests (for #2378)

---

lib/src/rules/prefer_final_fields.dart
test/rules/prefer_final_fields.dart

The docs were incorrect.  This fixes them and adds a test.
/fyi @lrhn

update `prefer_final_fields` docs to widen class to library

---

analysis_options.yaml
lib/src/rules/always_specify_types.dart
lib/src/rules/avoid_equals_and_hash_code_on_mutable_classes.dart
lib/src/rules/cascade_invocations.dart
lib/src/rules/iterable_contains_unrelated_type.dart
lib/src/rules/list_remove_unrelated_type.dart
lib/src/rules/prefer_const_constructors_in_immutables.dart
lib/src/rules/prefer_const_literals_to_create_immutables.dart
lib/src/rules/type_init_formals.dart
lib/src/util/boolean_expression_utilities.dart

enable `non_constant_identifier_names`

---

analysis_options.yaml
lib/src/rules/avoid_web_libraries_in_flutter.dart
lib/src/rules/diagnostic_describe_all_properties.dart
lib/src/rules/no_runtimeType_toString.dart
lib/src/rules/prefer_for_elements_to_map_fromIterable.dart
lib/src/rules/prefer_iterable_whereType.dart
test/engine_test.dart
test/integration_test.dart
tool/doc.dart
tool/rule.dart

Some tidying up.
/cc @stereotype441

enable `file_names` and `prefer_typing_uninitialized_variables`

---

tool/canonical/assists.json
tool/canonical/scorecard.dart

Follow-up from: https://github.com/dart-lang/linter/issues/2408#issuecomment-758833370

account for lints w/ assists in scoring

---

lib/src/rules/avoid_relative_lib_imports.dart

See: https://github.com/dart-lang/linter/issues/2419

add bug reference

---

tool/canonical/fix_excludes.json

See: https://dart-review.googlesource.com/c/sdk/+/178660

exclude avoid_types_as_parameter_names

---

.github/workflows/build.yaml
tool/travis.sh

enable coverage in a github action

---

CONTRIBUTING.md
doc/RELEASING.md

remove travis references

---

pubspec.yaml
tool/baseline/pana.json

fixed missing dependency

---

analysis_options.yaml
lib/src/rules/avoid_field_initializers_in_const_classes.dart
lib/src/rules/avoid_renaming_method_parameters.dart
lib/src/rules/deprecated_consistency.dart
lib/src/rules/empty_constructor_bodies.dart
lib/src/rules/implementation_imports.dart
lib/src/rules/prefer_final_fields.dart
lib/src/rules/prefer_initializing_formals.dart
lib/src/rules/prefer_is_empty.dart
lib/src/rules/unnecessary_lambdas.dart
lib/src/rules/unnecessary_null_checks.dart
lib/src/util/leak_detector_visitor.dart
test/integration_test.dart
tool/canonical/scorecard.dart

Cheers for these awesome lints @a14n!
Follow-up from https://github.com/dart-lang/linter/pull/2457.

NNBD linting

---

pubspec.yaml

Update collection dependency to stable release

---

lib/src/util/score_utils.dart
tool/crawl.dart
tool/since.dart

nullable list cleanup

---

lib/src/rules/prefer_single_quotes.dart
lib/src/util/condition_scope_visitor.dart
lib/src/util/tested_expressions.dart
tool/bot.sh

soundness fixes

---

lib/src/cli.dart
tool/bot/rule_doc_check.dart

See: #2475 for follow-up on why the bots are wrongly green.

cast fix && formatting

---

lib/src/rules/avoid_setters_without_getters.dart
lib/src/rules/avoid_type_to_string.dart
lib/src/rules/directives_ordering.dart
lib/src/rules/parameter_assignments.dart
lib/src/util/tested_expressions.dart

cast cleanup

---

test/engine_test.dart
test/mocks.dart

I'm not convinced the test is worth saving.

fix rule mock noSuchMethod (and remove test)

---

lib/src/ast.dart
lib/src/rules/avoid_returning_null_for_future.dart
lib/src/rules/avoid_returning_null_for_void.dart
lib/src/rules/avoid_types_as_parameter_names.dart
lib/src/rules/avoid_unused_constructor_parameters.dart
lib/src/rules/parameter_assignments.dart
lib/src/rules/unnecessary_lambdas.dart
pubspec.yaml

update to analyzer 1.1.0 apis

---

lib/src/cli.dart
lib/src/formatter.dart
lib/src/rules/always_use_package_imports.dart
lib/src/rules/annotate_overrides.dart
lib/src/rules/avoid_positional_boolean_parameters.dart
lib/src/rules/avoid_relative_lib_imports.dart
lib/src/rules/avoid_returning_null_for_future.dart
lib/src/rules/avoid_types_as_parameter_names.dart
lib/src/rules/avoid_web_libraries_in_flutter.dart
lib/src/rules/cascade_invocations.dart
lib/src/rules/cast_nullable_to_non_nullable.dart
lib/src/rules/diagnostic_describe_all_properties.dart
lib/src/rules/directives_ordering.dart
lib/src/rules/overridden_fields.dart
lib/src/rules/parameter_assignments.dart
lib/src/rules/prefer_final_in_for_each.dart
lib/src/rules/prefer_final_locals.dart
lib/src/rules/prefer_foreach.dart
lib/src/rules/prefer_function_declarations_over_variables.dart
lib/src/rules/prefer_single_quotes.dart
lib/src/rules/pub/package_names.dart
lib/src/rules/public_member_api_docs.dart
lib/src/rules/recursive_getters.dart
lib/src/rules/unnecessary_getters.dart
lib/src/rules/unnecessary_getters_setters.dart
lib/src/util/condition_scope_visitor.dart
lib/src/util/leak_detector_visitor.dart

Another round of de-null-checking.

null check cleanup

---

lib/src/rules/prefer_interpolation_to_compose_strings.dart
test/rules/prefer_interpolation_to_compose_strings.dart

handle raw strings in prefer_interpolation_to_compose_strings

---

lib/src/cli.dart
lib/src/rules/unnecessary_getters_setters.dart
test/formatter_test.dart
test/rule_test.dart

(Cheers to the new pedantic for the flagging! 🍻 )
/fyi @davidmorgan

delint unnecessary cascades

---

pubspec.yaml
tool/canonical/scorecard.dart
tool/scorecard.dart

migrate to github 8.0.0

---

lib/src/rules/prefer_const_literals_to_create_immutables.dart
lib/src/rules/unnecessary_const.dart

Some work to move away from deprecated APIs.
@scheglov: could you advise on the best approach for `unnecessary_const`?
/cc @scheglov

stop AST manipulation

---

test/experiments_test.dart
test/rule_test.dart
test/util/rule_debug.dart

default rule debugging to true in tests

---

lib/src/rules/use_build_context_synchronously.dart
lib/src/util/flutter_utils.dart

extract a flutter utility method

---

lib/src/rules/use_build_context_synchronously.dart

Follow-up from https://github.com/dart-lang/linter/pull/2508.
/cc @parlough @bwilkerson

add dart code blocks

---

.github/workflows/build.yaml
tool/bot.sh

Fixes: https://github.com/dart-lang/linter/issues/2475.
(The main bot *should* break here.  It's a good thing!)
/cc @bwilkerson @devoncarew

split out coverage into its own bot

---

test/rule_test.dart

Fixes the build.  Easy after all but still the approach is not great so I'll play around with moving bits about.
Thanks for the helpful feedback!

fix lint registry timing

---

lib/src/rules/prefer_mixin.dart
pubspec.yaml
test/rules/experiments/nonfunction-type-aliases/analysis_options.yaml
test/rules/experiments/nonfunction-type-aliases/rules/prefer_mixin.dart

`prefer_mixin` support for nonfunction-type-aliases

---

test/rules/experiments/nonfunction-type-aliases/rules/slash_for_doc_comments.dart

`slash_for_doc_comments` tests for nonfunction type aliases

---

lib/src/cli.dart

todo: migrate cli to `dart analyze`

---

pubspec.yaml
test/_data/public_member_api_docs/pubspec.yaml
test/integration/public_member_api_docs.dart

relax SDK lower-bound

---

test/rules/library_private_types_in_public_api.dart

=> dart test

---

lib/src/rules/library_private_types_in_public_api.dart

Our changes passed like ships in the night!
🚢 

convert final

---

tool/doc.dart
tool/machine.dart

migrate from `list.from` to `list.of`

---

lib/src/rules/prefer_is_empty.dart
lib/src/rules/unnecessary_const.dart
pubspec.yaml

update to analyzer inConstantContext public API

---

lib/src/rules/camel_case_extensions.dart

+ style guide ref

---

lib/src/rules/parameter_assignments.dart
lib/src/rules/tighten_type_of_initializing_formals.dart
lib/src/util/dart_type_utilities.dart
pubspec.yaml
test/rules/unsafe_html.dart

analyzer 1.4.0

---

lib/src/rules/non_constant_identifier_names.dart
test/rules/non_constant_identifier_names.dart

lowerCamelCase check local variables

---

analysis_options.yaml
test/engine_test.dart

+ prefer_null_aware_method_calls

---

analysis_options.yaml
lib/src/rules/avoid_dynamic_calls.dart
lib/src/rules/prefer_const_constructors_in_immutables.dart
lib/src/rules/prefer_contains.dart
lib/src/rules/prefer_int_literals.dart
lib/src/rules/unawaited_futures.dart
lib/src/rules/use_is_even_rather_than_modulo.dart
lib/src/util/dart_type_utilities.dart
lib/src/util/tested_expressions.dart

enable `use_if_null_to_convert_nulls_to_bools`

---

lib/src/rules/prefer_contains.dart

syntax fix

---

AUTHORS

Add Benjamin Li to AUTHORS

---

lib/src/rules/use_build_context_synchronously.dart
test/rules/use_build_context_synchronously.dart

Fixes: #2574
I'm not sure about how (and if) we should be handling `break`s, `continue`, `whiles`s  and `for`-loops.  This doesn't feel complete as is.  (Filling out some test cases would help.)

short circuit await discovery for terminating blocks

---

analysis_options.yaml
lib/src/rules/use_build_context_synchronously.dart
test/integration/use_build_context_synchronously.dart
test/integration_test.dart
test_data/integration/use_build_context_synchronously/analysis_options.yaml
test_data/integration/use_build_context_synchronously/lib/migrated.dart
test_data/integration/use_build_context_synchronously/lib/unmigrated.dart
test_data/integration/use_build_context_synchronously/pubspec.yaml

support mixed mode nullability checks in `use_build_context_synchronously`

---

pubspec.yaml

update SDK constraint

---

tool/doc.dart

Fixes #2623
/cc @bwilkerson @goderbauer

update flutter rule set source location

---

lib/src/util/score_utils.dart

(Previously we only labeled pedantic.)
Sample run:
```
-----------------------------------------------------------------------------
Timings                                                                    ms
-----------------------------------------------------------------------------
avoid_web_libraries_in_flutter [flutter]                                  250
invariant_booleans                                                        116
use_late_for_private_fields_and_variables                                  92
prefer_double_quotes                                                       55
close_sinks                                                                37
flutter_style_todos                                                        34
avoid_dynamic_calls …
```

label rulesets in benchmarks

---

lib/src/rules/use_build_context_synchronously.dart

update `use_build_context_synchronously` to use LinterContext.inTestDir()

---

lib/src/formatter.dart

Accidentally dropped from: https://github.com/dart-lang/linter/pull/2635 😬 

rule set labelling

---

lib/src/rules/await_only_futures.dart

Fixes: https://github.com/dart-lang/linter/issues/2644
/cc @lrhn @davidmorgan @bwilkerson

update `unawaited_futures` docs

---

tool/canonical/scorecard.dart
tool/crawl.dart
tool/doc.dart

Fixes #2634
/cc @goderbauer @bwilkerson

update flutter options URL

---

README.md

Wordsmithing welcome.
/cc @goderbauer @mit-mit @devoncarew

update canonical lint source links

---

analysis_options.yaml
lib/src/formatter.dart
lib/src/rules/avoid_unused_constructor_parameters.dart
lib/src/rules/constant_identifier_names.dart
lib/src/rules/no_adjacent_strings_in_list.dart
lib/src/rules/non_constant_identifier_names.dart
lib/src/rules/overridden_fields.dart
lib/src/rules/parameter_assignments.dart
lib/src/rules/prefer_asserts_in_initializer_lists.dart
lib/src/rules/prefer_final_parameters.dart
lib/src/rules/prefer_single_quotes.dart
lib/src/rules/prefer_typing_uninitialized_variables.dart
lib/src/rules/unnecessary_statements.dart
lib/src/rules/use_late_for_private_fields_and_variables.dart
lib/src/util/leak_detector_visitor.dart
lib/src/util/tested_expressions.dart
pubspec.yaml
test/rule_test.dart
test/util/test_utils.dart
tool/benchmark.dart
tool/canonical/scorecard.dart
tool/doc.dart
tool/scorecard.dart
tool/spelunk.dart

enable recommended lints

---

analysis_options.yaml

remove redundant/deprecated rules

---

AUTHORS

Fixes #2677 
/cc @salihgueler @bwilkerson

+ muhammed

---

analysis_options.yaml
tool/doc.dart

enable `depend_on_referenced_packages` and `noop_primitive_operations`

---

lib/src/utils.dart
test/utils_test.dart

Allow a single trailing underscore in lowerCamelCase
Fixes #2687

Allow a single trailing underscore in lowerCamelCase

---

lib/src/rules/always_specify_types.dart
lib/src/rules/avoid_types_on_closure_parameters.dart

See: https://github.com/dart-lang/sdk/issues/38081#issuecomment-857342932

document incompatible rules

---

lib/src/rules/always_specify_types.dart

remove stale doc

---

tool/github.dart
tool/query.dart
tool/scorecard.dart

Finding this useful personally so I figured I'd share.  Sample run:
```sh
☁  tool [master] ⚡  dart query.dart sort_child_properties_last
https://dart-lang.github.io/linter/lints/sort_child_properties_last.html
contained in: [pedantic]
issue: Investigate new `sort_child_properties_last` diagnostics when relaxed
labels: bug, customer: flutter, customer: g3
https://github.com/dart-lang/linter/issues/2713
```

simple rule query tool

---

tool/doc.dart

Fixes: https://github.com/dart-lang/linter/issues/2624
(EDIT: swapped colors.)
Badges could be made tidier (I just used the generator in shields.io).  Maybe @parlough has ideas for that?
/cc @bwilkerson @parlough

badge core and recommended

---

AUTHORS

See: https://github.com/dart-lang/linter/pull/2725#issuecomment-864312985

+ bernardo

---

lib/src/rules/use_build_context_synchronously.dart
test_data/rules/use_build_context_synchronously.dart

use_build_context_synchronously: support switches; improve flow analysis

---

lib/src/rules/valid_regexps.dart
test_data/rules/valid_regexps.dart

support unicode in `valid_regexps`

---

example/readme.md

update references to canonical lint sources

---

tool/crawl.dart
tool/doc.dart
tool/scorecard.dart
tool/since.dart

Speeds up doc creation considerably.

add github authentication

---

lib/src/rules/avoid_returning_null.dart
test_data/rules/avoid_returning_null.dart
test_data/rules/experiments/nnbd/rules/avoid_returning_null.dart

See: https://github.com/dart-lang/linter/issues/2636

disable `avoid_returning_null` w/ nnbd

---

lib/src/rules/unnecessary_string_interpolations.dart
test_data/rules/unnecessary_string_interpolations.dart

fix false positive in `unnecessary_string_interpolations` w/ nullable interpolated strings

---

pubspec.yaml

/cc @bwilkerson @scheglov @jonasfj

revert meta dep bump

---

lib/src/rules/always_specify_types.dart
test/experiments_test.dart
test_data/rules/experiments/nonfunction-type-aliases/rules/.mock_packages
test_data/rules/experiments/nonfunction-type-aliases/rules/always_specify_types.dart

Maybe too naive? 🤔 
Fixes #2692

support type aliases in `always_specify_types`

---

example/all.yaml
lib/src/formatter.dart
lib/src/rules.dart
lib/src/rules/eol_at_end_of_file.dart
lib/src/rules/unnecessary_getters_setters.dart
test/integration/eol_at_end_of_file.dart
test_data/integration/eol_at_end_of_file/lintconfig.yaml
test_data/integration/eol_at_end_of_file/src/multipleComments.dart
test_data/integration/eol_at_end_of_file/src/multipleNewLines.dart
test_data/integration/eol_at_end_of_file/src/newline.dart
test_data/integration/eol_at_end_of_file/src/noNewline.dart
test_data/rules/eol_at_end_of_file.dart
tool/doc.dart

This PR introduces a new `eol_at_end_of_file` rule.
Fixes #2756

Implement eol_at_end_of_file rule

---

CHANGELOG.md

Update changelog about the new lint.

Update changelog about eol_at_end_of_file

---

CHANGELOG.md
lib/src/rules/curly_braces_in_flow_control_structures.dart
test_data/rules/curly_braces_in_flow_control_structures.dart

Fix curly_braces_in_flow_control_structures when "if" is "else" of previous "if"

---

lib/src/rules/exhaustive_cases.dart

See #2768
/cc @bwilkerson @eernstg

fix docs (E => EnumLike)

---

test/validate_format_test.dart

platform-aware path filtering

---

lib/src/rules/no_logic_in_create_state.dart
test_data/rules/no_logic_in_create_state.dart

Fix no_logic_in_create_state for empty body

---

CHANGELOG.md

add missing entries for `1.8.0`

---

lib/src/rules/cascade_invocations.dart
lib/src/rules/leading_newlines_in_multiline_strings.dart
lib/src/rules/missing_whitespace_between_adjacent_strings.dart

Fix some minor spelling mistakes in lint details

---

tool/since.dart

guard against unparsable versions

---

analysis_options.yaml

fix options (mis)sort

---

lib/src/ast.dart
lib/src/rules/prefer_contains.dart
lib/src/rules/prefer_is_empty.dart

More visitor tidying.
(Also note the constant evaluation issue identified in #2818.)

migrate `prefer_contains` to a binaryExpression visitor

---

lib/src/rules/omit_local_variable_types.dart
test_data/rules/omit_local_variable_types.dart

Fix false positive in `omit_local_variable_types`

---

lib/src/rules/prefer_contains.dart

Follow-up from https://github.com/dart-lang/linter/pull/2819.

fix example

---

lib/src/rules/prefer_void_to_null.dart
test_data/rules/prefer_void_to_null.dart

Fix false positive in `prefer_void_to_null`

---

lib/src/rules/always_use_package_imports.dart
lib/src/rules/avoid_equals_and_hash_code_on_mutable_classes.dart
lib/src/rules/void_checks.dart

This PR removes unused `context` field.

Remove unused field.

---

lib/src/rules/unnecessary_getters_setters.dart
test_data/rules/unnecessary_getters_setters.dart

only flag the getter in `unnecessary_getters_setters`

---

test_data/rules/void_checks.dart

Test case for fixed issue.
Closes #1675
/fyi @jakemac53

test case for (fixed) `void_checks` issue

---

lib/src/rules/prefer_generic_function_type_aliases.dart
test_data/rules/prefer_generic_function_type_aliases.dart

fix `prefer_generic_function_type_aliases` false positive w/ incomplete statements

---

test_data/rules/void_checks.dart

Also fixed by recent changes.
Closes #https://github.com/dart-lang/linter/issues/2685

`void_checks` false positive fix test case

---

test_data/rules/prefer_initializing_formals.dart

Test case for a (previously) fixed false positive.
Closes #2664

`prefer_initializing_formals` false positive fix test case

---

lib/src/rules/prefer_void_to_null.dart
test_data/rules/prefer_void_to_null.dart

fix `prefer_void_to_null` false positive w/ overridden properties

---

test/formatter_test.dart
test/mocks.dart

Follow-up from https://github.com/dart-lang/linter/pull/2866.
A few more tweaks to make our mocks less fragile.

make analyzer mocks less fragile

---

lib/src/rules/avoid_null_checks_in_equality_operators.dart
test_data/rules/avoid_null_checks_in_equality_operators.dart

fix false positive in `avoid_null_checks_in_equality_operators` w/ non-nullable param

---

lib/src/rules/overridden_fields.dart
test_data/rules/overridden_fields.dart

Fixes https://github.com/dart-lang/linter/issues/2874

fix `overridden_fields` false positive w/ static fields

---

.github/ISSUE_TEMPLATE/config.yml

See: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser

support blank issues

---

.github/ISSUE_TEMPLATE/config.yml

+ link to lints issues

---

AUTHORS

Follow-up from: https://github.com/dart-lang/linter/pull/2879
Main bot to be fixed by: #2881

+ davidmartos

---

.github/workflows/build.yaml
tool/baseline/pana.json

~Blocked on: https://github.com/dart-lang/pana/issues/941.~  🦅 
Fixes: #2504
Main bot to be fixed by: #2881

re-enable pana bot (try)

---

lib/src/ast.dart
lib/src/utils.dart
test/utils_test.dart

See: https://github.com/dart-lang/linter/pull/2791#issuecomment-904913681.
Cheers @parlough! 🍻 

disallow reserved words in package names

---

tool/doc.dart

update predefined rulesets

---

test_data/rules/experiments/constructor_tearoffs/rules/always_specify_types.dart

constructor tear-off tests

---

lib/src/rules/prefer_const_literals_to_create_immutables.dart
test/integration_test.dart

This prepares for landing https://dart-review.googlesource.com/c/sdk/+/190360 into the analyzer.

Fix pre-existing HintCode.UNNECESSARY_TYPE_CHECK_TRUE

---

pubspec.yaml
test_data/rules/experiments/constructor_tearoffs/rules/always_specify_types.dart

analyzer update to 2.2.0

---

lib/src/ast.dart
lib/src/rules/always_specify_types.dart
lib/src/rules/prefer_const_constructors.dart
lib/src/rules/unnecessary_overrides.dart
test_data/rules/unnecessary_overrides.dart

element metadata access cleanup

---

.github/workflows/build.yaml

remove stale comment

---

lib/src/rules/unnecessary_lambdas.dart
test_data/rules/experiments/constructor_tearoffs/rules/unnecessary_lambdas.dart

unnecessary_lambdas: constructor tear-off param matching improvements

---

AUTHORS

For #2934
Seems a little overkill for a typo fix, but I'm not complaining 😄

Add self to AUTHORS

---

lib/src/rules/always_specify_types.dart

prep for removal of `NamedType`

---

lib/src/rules/always_specify_types.dart

Revert "prep for removal of `NamedType`"

---

lib/src/rules/null_closures.dart

migrate to Object.hash

---

.github/move.yml
README.md
doc/WritingLints.MD
tool/canonical/scorecard.dart
tool/scorecard.dart

/fyi @athomas 
See also: #2923.

update SDK default branch to "main"

---

test/rule_test.dart

(temp) fix spelunking w/ constructor tearoffs

---

pubspec.yaml
test/rule_test.dart

update to analyzer 2.13.0

---

lib/src/rules/avoid_print.dart
lib/src/util/flutter_utils.dart
test_data/mock_packages/flutter/lib/foundation.dart
test_data/mock_packages/flutter/lib/src/foundation/constants.dart
test_data/rules/avoid_print.dart

Allow print when it is behind the `kDebugMode` flag

---

lib/src/rules/unnecessary_lambdas.dart
test_data/rules/unnecessary_lambdas.dart

fix `unnecessary_lambdas` false positive for  const constructor invocations

---

README.md
tool/crawl.dart
tool/doc.dart
tool/machine.dart
tool/scorecard.dart

remove effective dart ruleset references

---

lib/src/ast.dart

See: https://github.com/dart-lang/sdk/issues/47221#issuecomment-922115669
💎 
/fyi @jcollins-g @eernstg

migrate to a (lazy) cached getter

---

lib/src/ast.dart
lib/src/cli.dart
lib/src/rules/avoid_function_literals_in_foreach_calls.dart
lib/src/rules/implementation_imports.dart
lib/src/rules/no_logic_in_create_state.dart
lib/src/rules/one_member_abstracts.dart
lib/src/rules/prefer_for_elements_to_map_fromIterable.dart
lib/src/rules/prefer_inlined_adds.dart
lib/src/rules/prefer_int_literals.dart
lib/src/rules/prefer_spread_collections.dart
lib/src/rules/slash_for_doc_comments.dart
lib/src/rules/unnecessary_string_interpolations.dart
test/util/rule_debug.dart

tidy up: prefer .first (over [0])

---

test_data/rules/always_declare_return_types.dart
test_data/rules/avoid_bool_literals_in_conditional_expressions.dart
test_data/rules/avoid_catching_errors.dart
test_data/rules/avoid_positional_boolean_parameters.dart
test_data/rules/avoid_returning_this.dart
test_data/rules/avoid_type_to_string.dart
test_data/rules/avoid_unused_constructor_parameters.dart
test_data/rules/cascade_invocations.dart
test_data/rules/comment_references.dart
test_data/rules/control_flow_in_finally.dart
test_data/rules/join_return_with_assignment.dart
test_data/rules/literal_only_boolean_expressions.dart
test_data/rules/one_member_abstracts.dart
test_data/rules/parameter_assignments.dart
test_data/rules/prefer_foreach.dart
test_data/rules/prefer_int_literals.dart
test_data/rules/prefer_spread_collections.dart
test_data/rules/sort_constructors_first.dart
test_data/rules/throw_in_finally.dart
test_data/rules/unnecessary_getters.dart
test_data/rules/unnecessary_lambdas.dart
test_data/rules/unnecessary_overrides.dart
test_data/rules/unnecessary_string_interpolations.dart
test_data/rules/unnecessary_this.dart
test_data/rules/use_string_buffers.dart
test_data/rules/void_checks.dart

Cleanup unwanted test diagnostics

---

test_data/rules/omit_local_variable_types.dart
test_data/rules/prefer_asserts_in_initializer_lists.dart
test_data/rules/prefer_iterable_whereType.dart

diagnostic cleanup

---

test/rules/all.dart
test/rules/prefer_asserts_in_initializer_lists.dart
test/rules/prefer_const_constructors_in_immutables.dart
test/rules/prefer_spread_collections.dart
test/rules/void_checks.dart
test_data/rules/prefer_asserts_in_initializer_lists.dart
test_data/rules/prefer_conditional_assignment.dart
test_data/rules/prefer_const_constructors_in_immutables.dart
test_data/rules/prefer_spread_collections.dart
test_data/rules/prefer_typing_uninitialized_variables.dart
test_data/rules/unnecessary_await_in_return.dart
test_data/rules/void_checks.dart

migrate invalid code snippets to in-memory tests

---

test/rule_test_support.dart
test/rules/avoid_function_literals_in_foreach_calls.dart
test/rules/avoid_init_to_null.dart
test/rules/overridden_fields.dart
test/rules/prefer_asserts_in_initializer_lists.dart
test/rules/prefer_const_constructors_in_immutables.dart
test/rules/prefer_contains.dart
test/rules/prefer_spread_collections.dart
test/rules/void_checks.dart

cleanup asserts in reflective tests

---

lib/src/rules/prefer_collection_literals.dart
test/rules/all.dart
test/rules/prefer_collection_literals.dart

fix `prefer_collection_literals` named typed param false positive

---

test/rule_test_support.dart
test/rules/overridden_fields.dart
test/rules/prefer_collection_literals.dart

Follow-up from https://github.com/dart-lang/linter/pull/2988#discussion_r720427733.

+ assertNoDiagnostics

---

test/integration/avoid_renaming_method_parameters.dart
test/rule_test_support.dart
test/rules/all.dart
test/rules/prefer_const_constructors.dart
test/rules/type_init_formals.dart
test_data/integration/avoid_renaming_method_parameters/lib/a.dart
test_data/rules/avoid_types_as_parameter_names.dart
test_data/rules/avoid_types_on_closure_parameters.dart
test_data/rules/experiments/nnbd/rules/prefer_constructors_over_static_methods.dart
test_data/rules/join_return_with_assignment.dart
test_data/rules/non_constant_identifier_names.dart
test_data/rules/prefer_const_constructors.dart
test_data/rules/prefer_expression_function_bodies.dart
test_data/rules/prefer_final_parameters.dart
test_data/rules/type_init_formals.dart
test_data/rules/unnecessary_overrides.dart
test_data/rules/unnecessary_parenthesis.dart
test_data/rules/unsafe_html.dart

test diagnostic cleanup

---

lib/src/rules/require_trailing_commas.dart

remove `dartfmt` reference

---

AUTHORS

For https://github.com/dart-lang/linter/pull/2986

Add Lucas to AUTHORS

---

lib/src/rules/omit_local_variable_types.dart

Fixes #3054
Copy the description from Effective Dart. Change from "CONSIDER" to
"DON'T" since Effective Dart changed to a stronger position in
https://github.com/dart-lang/site-www/pull/2966

Update justification for omit local variable types

---

test/mocks.dart

prepare for removal of `modificationStamp`

---

lib/src/rules/pub/secure_pubspec_urls.dart

cleanup secure_pubspec_urls docs

---

tool/crawl.dart

Fixes version matches for versions post 1.0.
For example:
And drops a bunch of special case logic for crawling ancient releases.

update and simplify linter version finding

---

lib/src/rules/comment_references.dart
pubspec.yaml
test/integration/secure_pubspec_urls.dart
test/mocks.dart
test/rules/super_goes_last.dart

Fixes https://github.com/dart-lang/linter/issues/3069
/cc @scheglov @bwilkerson 
/fyi @srawlins

migrate to analyzer 2.8.0

---

lib/src/test_utilities/test_resource_provider.dart

clean up unnecessary nullable

---

test/all.dart
test/rule_test.dart
test/unmocked_sdk_rule_test.dart
test_data/rules/unmocked/unsafe_html.dart

support lint test runs against an un-mocked SDK

---

lib/src/rules/avoid_redundant_argument_values.dart

Follow-up from https://github.com/dart-lang/linter/pull/3083#pullrequestreview-822046951.

Tidy param check

---

test/rules/avoid_redundant_argument_values.dart

See: https://github.com/dart-lang/linter/issues/3034

test for a required nullable param false positive

---

analysis_options.yaml
lib/src/rules/avoid_unused_constructor_parameters.dart

remove needless leading underscores

---

analysis_options.yaml
lib/src/ast.dart

+ unnecessary_late

---

lib/src/rules/no_leading_underscores_for_local_identifiers.dart
test_data/rules/no_leading_underscores_for_local_identifiers.dart

allow underscores in default field params

---

tool/baseline/pana.json

(Penalty for lack of platform support is now 20?!?)

lower pana baseline score

---

pubspec.yaml

bump github dep

---

README.md

Update analyze command link

---

test/rules/avoid_init_to_null.dart

super_parameters test for `avoid_init_to_null`

---

lib/src/rules/avoid_final_parameters.dart
test/rule_test_support.dart
test/rules/avoid_final_parameters.dart
test/rules/avoid_init_to_null.dart
test/rules/avoid_redundant_argument_values.dart

super_parameters test for `avoid_final_parameters`

---

test/rules/all.dart
test/rules/deprecated_consistency.dart

super_parameters test for `deprecated_consistency`

---

test/rules/all.dart
test/rules/prefer_equal_for_default_values.dart

super_parameters test for `prefer_equal_for_default_values`

---

lib/src/rules/type_init_formals.dart
pubspec.yaml
test/rules/type_init_formals.dart

super_parameter support for `type_init_formals`

---

lib/src/rules/prefer_asserts_in_initializer_lists.dart
test/rules/prefer_asserts_in_initializer_lists.dart

super_parameter support for `prefer_asserts_in_initializer_lists`

---

lib/src/rules/avoid_annotating_with_dynamic.dart
test/rules/all.dart
test/rules/avoid_annotating_with_dynamic.dart

super_parameter support for `avoid_annotating_with_dynamic`

---

lib/src/rules/tighten_type_of_initializing_formals.dart

add super initializer example

---

lib/src/rules/prefer_asserts_in_initializer_lists.dart

update `prefer_asserts_in_initializer_lists` docs

---

test_data/integration/public_member_api_docs/analysis_options.yaml

remove unnecessary experiment config

---

test/rules/all.dart
test/rules/annotate_overrides.dart

enhanced enum tests for `annotate_overrides`

---

lib/src/rules/hash_and_equals.dart
test/rules/all.dart
test/rules/hash_and_equals.dart

enhanced enum support for `hash_and_equals`

---

test/rules/all.dart
test/rules/prefer_final_fields.dart

enhanced enum test for `prefer_final_fields`

---

lib/src/rules/unnecessary_getters_setters.dart
test/rules/all.dart
test/rules/unnecessary_getters_setters.dart

See: https://github.com/dart-lang/linter/issues/3200

enhanced enum support for `unnecessary_getters_setters`

---

test/rules/all.dart
test/rules/avoid_renaming_method_parameters.dart

enhanced enum tests for `avoid_renaming_method_parameters`

---

lib/src/rules/prefer_final_parameters.dart
test/rules/prefer_final_parameters.dart

Don't require final on super parameters
Fixes #3211

Don't require final on super parameters

---

tool/bot.sh
tool/pana_baseline.dart

migrate to `dart pub`

---

lib/src/rules/public_member_api_docs.dart
test/rules/all.dart
test/rules/public_member_api_docs_test.dart

enhanced enum support for `public_member_api_docs`

---

lib/src/rules/avoid_implementing_value_types.dart
lib/src/rules/library_private_types_in_public_api.dart
lib/src/rules/prefer_const_constructors.dart
lib/src/rules/prefer_mixin.dart
pubspec.yaml
test/rules/avoid_returning_this_test.dart
test/rules/prefer_generic_function_type_aliases_test.dart

Note that the test failures are *mostly* expected and I'll follow-up to fix them next.

update to analyzer 3.3.0 apis

---

test/rules/annotate_overrides_test.dart
test/rules/prefer_final_fields_test.dart
test/rules/unnecessary_getters_setters_test.dart

enum test updates for analyzer 3.3.0

---

lib/src/rules/hash_and_equals.dart
pubspec.yaml
test/rules/annotate_overrides_test.dart
test/rules/avoid_equals_and_hash_code_on_mutable_classes_test.dart
test/rules/hash_and_equals_test.dart
test/rules/unnecessary_overrides_test.dart

Closes #3097, closes #3195, closes #3094, closes #3093.

enum test updates

---

test/rules/avoid_renaming_method_parameters_test.dart

test update

---

lib/src/rules/sort_unnamed_constructors_first.dart
test/rules/all.dart
test/rules/sort_unnamed_constructors_first.dart

enhanced enum support for `sort_unnamed_constructors_first`

---

lib/src/rules/library_private_types_in_public_api.dart
test/rules/library_private_types_in_public_api_test.dart

enhanced enum support for `library_private_types_in_public_api`

---

lib/src/rules/avoid_shadowing_type_parameters.dart
test/rules/avoid_shadowing_type_parameters_test.dart

enhanced enum support for `avoid_shadowing_type_parameters`

---

test_data/rules/always_specify_types.dart

Test case for https://github.com/dart-lang/linter/issues/3275.
/cc @bwilkerson @stereotype441

test for type inference issue

---

lib/src/rules/use_super_parameters.dart
test/rules/use_super_parameters_test.dart

See: https://dart-review.googlesource.com/c/sdk/+/237502

fix `use_super_parameters` false positive w/ referenced params

---

lib/src/rules/use_super_parameters.dart
test/rules/use_super_parameters_test.dart

See: https://dart-review.googlesource.com/c/sdk/+/237600

fix `use_super_parameters` false positive w/ field formal params

---

lib/src/rules/use_key_in_widget_constructors.dart
test_data/rules/experiments/super_parameters/analysis_options.yaml
test_data/rules/experiments/super_parameters/rules/.mock_packages
test_data/rules/experiments/super_parameters/rules/use_key_in_widget_constructors.dart

See: https://github.com/flutter/flutter/issues/100297.
(Note that we don't have Flutter mocked for our rule tests so I resorted to "old-school" testing.)

fix super.key false positive for `use_key_in_widget_constructors`

---

lib/src/util/condition_scope_visitor.dart
pubspec.yaml
tool/rule.dart

update to lints v 2.0.0

---

analysis_options.yaml

remove rules duplicated in lints:2.0.0

---

lib/src/rules/use_super_parameters.dart
test/rules/use_super_parameters_test.dart

This addresses all the issues I could reproduce from #3306.
Let me know if you see any test cases I missed.
Thanks!

fix `use_super_parameters` false positives

---

lib/src/util/condition_scope_visitor.dart

https://github.com/dart-lang/linter/issues/3264

Fix ConditionScope variance null safety.

---

AUTHORS
lib/src/rules/flutter_style_todos.dart

The regex did not accept Github usernames starting with digits.
// TODO(myname): would work
// TODO(1nf0rmatix): would not
Fixes #3331

Fixing a bug where GitHub usernames starting with a digit where not accepted

---

.github/ISSUE_TEMPLATE/lint-proposal.md

Fixes #3335
/cc @asashour @bwilkerson

fix link typo

---

.github/ISSUE_TEMPLATE/lint-proposal.md

update proposal description to allow modifications

---

AUTHORS
lib/src/rules/tighten_type_of_initializing_formals.dart

tighten_type_of_initializing_formals typo fixed at line 40

tighten_type_of_initializing_formals.dart typo

---

lib/src/rules/no_leading_underscores_for_local_identifiers.dart
test_data/rules/no_leading_underscores_for_local_identifiers.dart

allow just underscores in `no_leading_underscores_for_local_identifiers`

---

lib/src/rules/avoid_init_to_null.dart
test/rules/avoid_init_to_null_test.dart

Fixes: #3349 
I don't love reaching into `Impl` classes so if there's a better way, I'd welcome it!

fix `avoid_init_to_null` w/ super initializing non-null defaults

---

lib/src/rules/no_leading_underscores_for_local_identifiers.dart
test_data/rules/no_leading_underscores_for_local_identifiers.dart

fix local functions in `no_leading_underscores_for_local_identifiers`

---

lib/src/rules/no_leading_underscores_for_local_identifiers.dart

fix visitor over-registration

---

lib/src/ast.dart
lib/src/rules/avoid_print.dart

Follow-up from: https://github.com/dart-lang/linter/pull/3379#discussion_r867170225
/cc @scheglov @a14n

add isDartCorePrint extension method

---

pubspec.yaml

See: https://dart-review.googlesource.com/c/sdk/+/243922

remove stale dep on `package:glob`

---

analysis_options.yaml
lib/src/formatter.dart
lib/src/rules/cancel_subscriptions.dart
lib/src/rules/close_sinks.dart
lib/src/rules/iterable_contains_unrelated_type.dart
lib/src/rules/list_remove_unrelated_type.dart
lib/src/rules/unnecessary_overrides.dart
lib/src/rules/use_enums.dart
pubspec.yaml
tool/benchmark.dart

bump to 2.17 && super.params

---

lib/src/rules/package_api_docs.dart

remove `DartProject` references

---

tool/bot.sh

Follow-up from: https://github.com/dart-lang/coverage/issues/382
/cc @liamappelbe @bwilkerson

remove deprecated `--packages` coverage flag

---

lib/src/rules/no_leading_underscores_for_local_identifiers.dart

(This is implementing already by `LintRule`.)

remove unnecessary interface

---

lib/src/rules/unawaited_futures.dart
test_data/rules/unawaited_futures.dart

`unawaited_futures` to handle string interpolation

---

lib/src/analyzer.dart
lib/src/rules/unnecessary_lambdas.dart
lib/src/rules/unnecessary_overrides.dart
pubspec.yaml
test/rule_test_support.dart

update to analyzer `4.1.0` APIs

---

lib/src/rules/prefer_final_parameters.dart
test/rules/prefer_final_parameters_test.dart

`prefer_final_parameters` to handle `DefaultFormalParameter`

---

analysis_options.yaml
tool/checks/driver.dart
tool/grind.dart

stop discarding futures

---

lib/src/rules/use_build_context_synchronously.dart
test_data/rules/use_build_context_synchronously.dart

Warn on `if (await condition) func2(context);`
Fixes #3457

use_build_context_synchronously: handling of await in if conditions

---

lib/src/rules/avoid_empty_else.dart
lib/src/rules/avoid_relative_lib_imports.dart
lib/src/rules/avoid_types_as_parameter_names.dart
lib/src/rules/hash_and_equals.dart
lib/src/rules/iterable_contains_unrelated_type.dart
lib/src/rules/list_remove_unrelated_type.dart
lib/src/util/unrelated_types_visitor.dart

This is a small sample of the changes to messages that I'm proposing to make. Feedback is absolutely welcome on both the messages themselves and on the process (for example, if it would be easier to put all the messages in a doc than in a PR).

Rework problem and correction messages

---

lib/src/rules/avoid_empty_else.dart
lib/src/rules/avoid_relative_lib_imports.dart
lib/src/rules/avoid_shadowing_type_parameters.dart
lib/src/rules/avoid_types_as_parameter_names.dart
lib/src/rules/await_only_futures.dart
lib/src/rules/camel_case_extensions.dart
lib/src/rules/camel_case_types.dart
lib/src/rules/curly_braces_in_flow_control_structures.dart
lib/src/rules/depend_on_referenced_packages.dart
lib/src/rules/empty_catches.dart
lib/src/rules/file_names.dart
lib/src/rules/hash_and_equals.dart
lib/src/rules/iterable_contains_unrelated_type.dart
lib/src/rules/list_remove_unrelated_type.dart
lib/src/rules/no_duplicate_case_values.dart
lib/src/rules/unrelated_type_equality_checks.dart
lib/src/rules/valid_regexps.dart
test/integration/depend_on_referenced_packages.dart

As before, I'm very interested in feedback on the actual message, though all feedback is welcome.

Rework messages, part 2

---

lib/src/formatter.dart
lib/src/rules/prefer_int_literals.dart
lib/src/test_utilities/test_resource_provider.dart

remove stale todos

---

.gitignore
lib/src/test_utilities/test_resource_provider.dart
test/integration/prefer_const_constructors.dart
test/integration/prefer_mixin.dart
test_data/rules/.dart_tool/package_config.json
test_data/rules/.mock_packages

https://github.com/dart-lang/linter/pull/3486 didn't quite fix CI with analyzer 4.2.0. The goal of this is to finish that work.
Related to #3485

Scrap more packages

---

.github/labeler.yml
.github/workflows/labeler.yml
lib/src/rules/camel_case_types.dart

testing PR auto-labeling 🤞

---

lib/src/rules/use_if_null_to_convert_nulls_to_bools.dart

+ effective dart link

---

.github/ISSUE_TEMPLATE/lint-proposal.md
.github/workflows/build.yaml
.github/workflows/gh-pages.yml
.github/workflows/scorecards-analysis.yml
CONTRIBUTING.md
README.md
doc/RELEASING.md
doc/WritingLints.MD
example/readme.md
lib/src/util/score_utils.dart
tool/canonical/readme.md
tool/canonical/scorecard.dart
tool/crawl.dart
tool/doc.dart

migrate to "main" branch

---

CONTRIBUTING.md
tool/canonical/gh_labels.dart
tool/canonical/readme.md
tool/doc.dart
tool/github.dart
tool/query.dart

"github" => "GitHub"

---

lib/src/ast.dart
test/rules/public_member_api_docs_test.dart

improve extension declaration diagnostic highlighting

---

tool/doc.dart

add "hasFix" article link

---

tool/canonical/gh_labels.dart

update to new label names

---

lib/src/ast.dart
lib/src/rules/avoid_classes_with_only_static_members.dart
lib/src/rules/avoid_implementing_value_types.dart
lib/src/rules/avoid_type_to_string.dart
lib/src/rules/deprecated_consistency.dart
lib/src/rules/implementation_imports.dart
lib/src/rules/missing_whitespace_between_adjacent_strings.dart
lib/src/rules/overridden_fields.dart
lib/src/rules/prefer_asserts_in_initializer_lists.dart
lib/src/rules/prefer_const_constructors.dart
lib/src/rules/prefer_const_constructors_in_immutables.dart
lib/src/rules/prefer_for_elements_to_map_fromIterable.dart
lib/src/rules/prefer_initializing_formals.dart
lib/src/rules/prefer_is_not_empty.dart
lib/src/rules/prefer_relative_imports.dart
lib/src/rules/unawaited_futures.dart
lib/src/rules/unnecessary_lambdas.dart
lib/src/rules/unnecessary_null_aware_operator_on_extension_on_nullable.dart
lib/src/rules/unnecessary_this.dart
lib/src/rules/unsafe_html.dart
lib/src/rules/use_enums.dart
lib/src/rules/use_key_in_widget_constructors.dart
lib/src/rules/use_named_constants.dart
lib/src/rules/valid_regexps.dart
lib/src/util/dart_type_utilities.dart
pubspec.yaml
tool/checks/rules/visit_registered_nodes.dart

update to analyzer 4.3.0 APIs

---

lib/src/rules/prefer_contains.dart
test/rules/prefer_contains_test.dart

fix `prefer_contains` when start index is non-zero

---

lib/src/rules/prefer_inlined_adds.dart
lib/src/rules/prefer_iterable_whereType.dart

fix doc example syntax

---

pubspec.yaml
test/rules/prefer_contains_test.dart

update test expectations

---

AUTHORS

> @nilsreichardt: could you follow-up with a PR to add yourself to AUTHORS?
From https://github.com/dart-lang/linter/pull/3553#issuecomment-1195795413

Add "Nils Reichardt" to `AUTHORS`

---

lib/src/rules/always_require_non_null_named_parameters.dart
lib/src/rules/avoid_positional_boolean_parameters.dart
lib/src/rules/avoid_returning_null.dart
lib/src/rules/null_closures.dart
lib/src/util/condition_scope_visitor.dart
test/integration_test.dart

clean up some unnecessary nullables

---

lib/src/rules/use_key_in_widget_constructors.dart

update doc to use super params

---

lib/src/rules/use_super_parameters.dart
test/rules/use_super_parameters_test.dart

check for repeated super param refs

---

tool/canonical/scorecard.dart
tool/doc.dart
tool/scorecard.dart

Fix requested: https://github.com/dart-lang/sdk/issues/49616
/fyi @a14n

clean up some no-op toString()s

---

pubspec.yaml

(NOTE that this is slightly ahead of what's in DEPS but I think compatible.)
https://github.com/dart-lang/sdk/blob/main/DEPS#L128
/cc @srawlins

bump to latest markdown

---

AUTHORS

I lost access to my previous email, even though I've only solved a typo, I figured I should replace it.

Update AUTHORS lost email

---

test/rules/non_constant_identifier_names_test.dart

See: https://github.com/dart-lang/linter/issues/3621 and https://github.com/dart-lang/linter/issues/3622.

[non_constant_identifier_names] + tests for record fields and types

---

test/rules/all.dart
test/rules/constant_identifier_names_test.dart

See: https://github.com/dart-lang/linter/issues/3630

constant_identifier_names test for records

---

tool/baseline/pana.json

From a recent CI run:
```
{grantedPoints: 130, maxPoints: 130}
Baseline check passed ✅
... you have a new baseline! 🎉 Consider updating tool/baseline/pana.json to match.
```

bump baseline

---

lib/src/rules/avoid_redundant_argument_values.dart
test/rules/avoid_redundant_argument_values_test.dart
test_data/rules/avoid_redundant_argument_values.dart

Visit enum declaration for `avoid_redundant_argument_values`

---

lib/src/rules/overridden_fields.dart

Anticipating deprecation in analyzer 5.0.

prep for analyzer 5.0

---

lib/src/extensions.dart
lib/src/rules/annotate_overrides.dart
lib/src/rules/avoid_renaming_method_parameters.dart
lib/src/rules/public_member_api_docs.dart
pubspec.yaml
test/rules/constant_identifier_names_test.dart
test/rules/public_member_api_docs_test.dart

analyzer 5.0.0 prep

---

test/rules/all.dart
test/rules/unnecessary_const_test.dart

See: https://github.com/dart-lang/linter/issues/3629

+ record expression test

---

README.md

remove pedantic reference

---

lib/src/rules/unreachable_from_main.dart

Replace `traverseNodesInDFS` with a `SimpleAstVisitor` which visits the relevant nodes.
This improves the benchmark time of `unreachable_from_main`, on my computer, from 120ms to 50ms. It is otherwise a no-op.

Use a SimpleAstVisitor in unreachable_from_main

---

lib/src/rules/join_return_with_assignment.dart

I was looking to fix bugs in join_return_with_statement, but all I ended up with was this tidying.
A visitor is not needed when we are only considering immediate children of certain nodes.
I also re-ordered some early-return conditions to avoid work until early-return conditions have been checked.
This speeds up the lint rule on my machine from 11ms to 5ms in the benchmark suite. Not sure if that is within the margin-of-error.

Simplify and speed up join_return_with_statement

---

lib/src/rules/non_constant_identifier_names.dart
test/rules/non_constant_identifier_names_test.dart

Fixes #3621
(+Tests for #3622.)

[non_constant_identifier_names] check records

---

test/rules/constant_identifier_names_test.dart

[constant_identifier_names] records test

---

lib/src/rules/unnecessary_const.dart
test/rules/unnecessary_const_test.dart

[unnecessary_const] records support

---

test/rules/all.dart
test/rules/prefer_const_declarations_test.dart

See: #3626 
Failing test details described in https://github.com/dart-lang/linter/issues/3626#issuecomment-1238722021.

[prefer_const_declarations] recordLiterals test

---

lib/src/rules/exhaustive_cases.dart
test_data/rules/exhaustive_cases.dart

Check parenthesized cases.
Fixes https://github.com/dart-lang/linter/issues/3677
Also I formatted the test data and added periods to comments.

check parenthesized cases

---

lib/src/analyzer.dart
pubspec.yaml
test/rule_test.dart
tool/spelunk.dart

update to analyzer 5.0.0

---

lib/src/rules/non_constant_identifier_names.dart
test/rules/non_constant_identifier_names_test.dart

check record type annotation field names

---

AUTHORS
lib/src/rules/flutter_style_todos.dart
test/rules/all.dart
test/rules/flutter_style_todos_test.dart
test_data/rules/flutter_style_todos.dart

⚡️ Ignore case sensitive for `flutter_style_todos`

---

lib/src/rules/unnecessary_brace_in_string_interps.dart
test/rules/all.dart
test/rules/unnecessary_brace_in_string_interps_test.dart

fix unnecessary_brace_in_string_interps for this expressions

---

lib/src/rules/cascade_invocations.dart

Modest gains, but I'd like to deprecate `traverseNodesInDFS()` since it performs poorly in general (and terribly in pathological cases).
/cc @srawlins

migrate `cascade_invocations` from `traverseNodesInDFS()`

---

lib/src/rules/tighten_type_of_initializing_formals.dart

**BEFORE** 
**AFTER**
A pretty big win!

reduce (needless) iteration in `tighten_type_of_initializing_formals`

---

lib/src/rules/cascade_invocations.dart

Follow-up from https://github.com/dart-lang/linter/pull/3718.

`cascade_invocations` visitor fixes

---

lib/src/rules/avoid_returning_null.dart

Note that this rule is slated for removal down the line (since it makes little sense in an NNBD world -- https://github.com/dart-lang/linter/issues/2636).  Since we're testing mostly with NNBD, the measured perf boost will be minimal but still gets us closer to deprecating `traverseNodesInDFS`.

migrate `avoid_returning_null` from `traverseNodesInDFS`

---

.github/workflows/build.yaml
.github/workflows/gh-pages.yml
.github/workflows/issue-labeler.yml
.github/workflows/labeler.yml

- update the workflows to default to read-only permissions
- let issue-labeler.yml write to issues
- and labeler.yml write to pull requests

have the workflows default to read-only permissions

---

tool/doc.dart
tool/machine.dart
tool/since.dart

Followup to https://github.com/dart-lang/linter/pull/3762

Add since information to machine generated json

---

lib/src/rules/unnecessary_overrides.dart
test/rules/unnecessary_overrides_test.dart
test_data/rules/unnecessary_overrides.dart

See: https://dart-review.googlesource.com/c/sdk/+/264961
/fyi @srawlins

`unnecessary_overrides` fix false positive for commented super calls

---

lib/src/rules/avoid_positional_boolean_parameters.dart

parameter checking code de-duping

---

lib/src/extensions.dart
lib/src/rules/invariant_booleans.dart
lib/src/util/condition_scope_visitor.dart
lib/src/util/leak_detector_visitor.dart

deprecate `traverseNodesInDFS`

---

lib/src/rules/implementation_imports.dart

Fix implementation_imports example

---

lib/src/rules/always_declare_return_types.dart
lib/src/rules/always_put_control_body_on_new_line.dart
lib/src/rules/always_put_required_named_parameters_first.dart
lib/src/rules/always_specify_types.dart
lib/src/rules/always_use_package_imports.dart
lib/src/rules/avoid_annotating_with_dynamic.dart
lib/src/rules/avoid_as.dart
lib/src/rules/avoid_bool_literals_in_conditional_expressions.dart
lib/src/rules/avoid_dynamic_calls.dart
lib/src/rules/avoid_function_literals_in_foreach_calls.dart
lib/src/rules/avoid_returning_null_for_future.dart
lib/src/rules/avoid_slow_async_io.dart
lib/src/rules/avoid_type_to_string.dart
lib/src/rules/cancel_subscriptions.dart
lib/src/rules/close_sinks.dart
lib/src/rules/comment_references.dart
lib/src/rules/literal_only_boolean_expressions.dart
lib/src/rules/no_adjacent_strings_in_list.dart
lib/src/rules/prefer_relative_imports.dart
lib/src/rules/pub/sort_pub_dependencies.dart

Adds explicit lint codes for more rules.

Add lint codes for more rules

---

lib/src/rules/type_annotate_public_apis.dart

Fix dead link in type_annotate_public_apis

---

.github/workflows/linkcheck.yml

Follow-up from https://github.com/dart-lang/linter/pull/3840 -- automate link-checking.
@srawlins @bwilkerson

add linkcheck workflow

---

lib/src/extensions.dart
lib/src/rules/avoid_catches_without_on_clauses.dart
lib/src/rules/avoid_catching_errors.dart
lib/src/rules/avoid_classes_with_only_static_members.dart
lib/src/rules/avoid_equals_and_hash_code_on_mutable_classes.dart
lib/src/rules/avoid_escaping_inner_quotes.dart
lib/src/rules/avoid_field_initializers_in_const_classes.dart
lib/src/rules/avoid_final_parameters.dart
lib/src/rules/avoid_implementing_value_types.dart
lib/src/rules/avoid_js_rounded_ints.dart
lib/src/rules/avoid_multiple_declarations_per_line.dart
lib/src/rules/avoid_positional_boolean_parameters.dart
lib/src/rules/avoid_private_typedef_functions.dart
lib/src/rules/avoid_redundant_argument_values.dart
lib/src/rules/avoid_returning_null.dart
lib/src/rules/avoid_returning_this.dart
lib/src/rules/avoid_setters_without_getters.dart
lib/src/rules/avoid_types_on_closure_parameters.dart
lib/src/rules/avoid_unused_constructor_parameters.dart
lib/src/rules/avoid_void_async.dart
lib/src/rules/pub/secure_pubspec_urls.dart
lib/src/rules/test_types_in_equals.dart
lib/src/rules/unnecessary_statements.dart
lib/src/rules/unsafe_html.dart

Also fixes a typo in a comment that I noticed while adding the codes.

Add explicit lint codes to more lints

---

.github/workflows/linkcheck.yml

The workflow is working so I think we can do without the debug flag.
This also makes the name lowercase like other workflow names.

quiet verbose link checking output

---

lib/src/rules/avoid_escaping_inner_quotes.dart
test/rules/all.dart
test/rules/avoid_escaping_inner_quotes_test.dart

Add missing arguments to the `avoid_escaping_inner_quotes_code_args` error code

---

tool/doc.dart

I'll think about adding some proper tests (`doc_test` is a smoke test) but I did some manual verification too.

look at unique names when checking fix status

---

tool/doc.dart

Currently...
😬 
/fyi @parlough

ensure rule indices are sorted by name

---

test/rules/avoid_init_to_null_test.dart
test/rules/library_names_test.dart
test/rules/parameter_assignments_test.dart
test/rules/prefer_equal_for_default_values_test.dart

Not sure what's up with pana but will investigate that elsewhere.

test fixes for >= 2.19

---

lib/src/rules/avoid_init_to_null.dart

Takes what is in [Effective Dart](https://dart.dev/guides/language/effective-dart/usage#dont-explicitly-initialize-variables-to-null) with some small adjustments.

Update avoid_init_to_null description for null safety

---

doc/releasing.md

As per our conversation.
/cc @srawlins

releasing doc updates

---

test/integration/close_sinks.dart

remove unneeded `--packages` test arg

---

lib/src/rules/unnecessary_null_aware_operator_on_extension_on_nullable.dart

removed unnecessary paren

---

lib/src/rules/prefer_collection_literals.dart
test/rules/prefer_collection_literals_test.dart

remove support for the default `List` constructor

---

analysis_options.yaml
tool/canonical/scorecard.dart
tool/labeler/issue_config.dart
tool/labeler/pr_config.dart
tool/query.dart

remove implicit casts option use

---

tool/doc.dart

fix state label

---

lib/src/rules/deprecated_consistency.dart

add docs for super initializer semantics

---

lib/src/rules/use_enums.dart

mark `use_enums` stable

---

lib/src/rules/dangling_library_doc_comments.dart

fix comment typo

---

lib/src/rules/avoid_field_initializers_in_const_classes.dart

remove unsafe null-check from `avoid_field_initializers_in_const_classes`

---

example/all.yaml
lib/src/rules/always_require_non_null_named_parameters.dart
lib/src/rules/avoid_returning_null.dart
lib/src/rules/avoid_returning_null_for_future.dart
lib/src/rules/prefer_equal_for_default_values.dart

3.0 deprecations

---

analysis_options.yaml
lib/src/ast.dart
pubspec.yaml

enable `dangling_library_doc_comments`

---

lib/src/rules/constant_identifier_names.dart
test/rules/constant_identifier_names_test.dart

check declared var patterns in `constant_identifier_names`

---

analysis_options.yaml
lib/src/ast.dart
pubspec.yaml

2.19.0 isn't on the CI yet. 😬 

Revert `dangling_library_doc_comments`

---

tool/rule.dart

update rule template stub to define a LintCode

---

lib/src/rules/avoid_renaming_method_parameters.dart
lib/src/rules/combinators_ordering.dart
lib/src/rules/diagnostic_describe_all_properties.dart
lib/src/rules/discarded_futures.dart
lib/src/rules/enable_null_safety.dart
lib/src/rules/implicit_call_tearoffs.dart
lib/src/rules/prefer_final_locals.dart
lib/src/rules/public_member_api_docs.dart
lib/src/rules/sized_box_shrink_expand.dart
lib/src/rules/unnecessary_getters.dart
lib/src/rules/unreachable_from_main.dart
lib/src/rules/use_is_even_rather_than_modulo.dart
lib/src/rules/use_setters_to_change_properties.dart
lib/src/rules/use_string_in_part_of_directives.dart

After this, there are only 7 lints remaining that don't have a `LintCode` defined.

Add lint codes to a few more lints

---

lib/src/util/leak_detector_visitor.dart

If we're not into the sorting, I can un-sort.

Rename methods in leak detector and sort

---

test/integration/always_require_non_null_named_parameters.dart
test/integration/cancel_subscriptions.dart
test/integration/close_sinks.dart
test/integration/use_build_context_synchronously.dart
test/rule_test.dart
test/rules/avoid_redundant_argument_values_test.dart
test/rules/enable_null_safety_test.dart
test/rules/null_closures_test.dart
test/rules/only_throw_errors_test.dart

flip the `noSoundNullSafety` flag for tests

---

lib/src/rules/unreachable_from_main.dart

fix lint code name

---

lib/src/rules/void_checks.dart
test/rules/void_checks_test.dart

fix `void_checks` false positive

---

lib/src/analyzer.dart
lib/src/rules/always_require_non_null_named_parameters.dart
lib/src/rules/avoid_as.dart
lib/src/rules/avoid_returning_null.dart
lib/src/rules/avoid_returning_null_for_future.dart
lib/src/rules/enable_null_safety.dart
lib/src/rules/invariant_booleans.dart
pubspec.yaml

fix state since bounds

---

tool/doc.dart

Migrate removed state header to use language version

---

lib/src/rules/implicit_call_tearoffs.dart

fix lint code

---

lib/src/rules/control_flow_in_finally.dart
lib/src/rules/throw_in_finally.dart

Fixes #4058
/cc @jakemac53  @bwilkerson

convert mixed in abstract class to a proper mixin

---

pubspec.yaml

bump `package:markdown`

---

lib/src/rules/unnecessary_parenthesis.dart
test/rules/unnecessary_parenthesis_test.dart

fix `unnecessary_parenthesis` over-reporting on constant patterns

---

AUTHORS
lib/src/rules/only_throw_errors.dart
test/rules/only_throw_errors_test.dart

[only_throw_errors] don't report on values of type Never

---

test/rules/prefer_const_literals_to_create_immutables_test.dart

fix lint rule referrence

---

tool/doc.dart

stop indexing removed lints

---

lib/src/rules/prefer_final_locals.dart
test/rules/all.dart
test/rules/prefer_final_locals_test.dart

Fixes: https://github.com/dart-lang/linter/issues/4120

support record and list patterns in `prefer_final_locals`

---

lib/src/rules/unnecessary_final.dart
test/rules/all.dart
test/rules/unnecessary_final_test.dart

declared variable pattern support for `unnecessary_final`

---

lib/src/rules/no_duplicate_case_values.dart

Fixes #3674
I chose not to go on about exhaustiveness though we could.
In any event, word-smithing welcome!

add 3.0 doc to `no_duplicate_case_values`

---

lib/src/rules/unnecessary_breaks.dart

Fixes #4131
Feedback, word-smithing welcome.
/cc @goderbauer @bwilkerson @parlough

doc patterns requirement in `unnecessary_breaks`

---

lib/src/rules/invalid_case_patterns.dart

`invalid_case_patterns` TODOs

---

test/rules/prefer_final_parameters_test.dart

`prefer_final_parameters` test for declared variable patterns

---

lib/src/rules/use_build_context_synchronously.dart
test_data/rules/use_build_context_synchronously.dart

Fix #4165 by visiting SwitchPatternCase

---

.github/workflows/build.yaml
.github/workflows/gh-pages.yml

- switch to the latest published version of the setup-dart action

switch to the latest published version of the setup-dart action

---

test/rules/prefer_final_parameters_test.dart

Addresses: https://github.com/dart-lang/linter/pull/4182#discussion_r1143937411
/cc @scheglov @srawlins

test cleanup

---

pubspec.yaml
test/rule_test_support.dart
test/rules/no_duplicate_case_values_test.dart
test/rules/prefer_final_parameters_test.dart

This release had a few affects on switches. Check it out.

Support analyzer 5.9.0

---

lib/src/rules/unnecessary_nullable_for_final_variable_declarations.dart
test/rules/all.dart
test/rules/unnecessary_nullable_for_final_variable_declarations_test.dart

declared variable pattern support for `unnecessary_nullable_for_final_variable_declarations`

---

lib/src/rules/unnecessary_final.dart
test/rules/unnecessary_final_test.dart

fix `unnecessary_final` case clause false positive

---

test/rules/unnecessary_final_test.dart

more object pattern test cases for `unnecessary_final`

---

test/rules/prefer_final_locals_test.dart

See: https://github.com/dart-lang/linter/issues/4174

if pattern-object tests for `prefer_final_locals`

---

test/rules/all.dart
test/rules/prefer_void_to_null_test.dart

`prefer_void_to_null` cast pattern tests

---

tool/baseline/pana.json

See: #4204
For now, we just lower the baseline.

lower pana baseline

---

test/rules/all.dart
test/rules/use_named_constants_test.dart

`use_named_constants` constant pattern tests

---

lib/src/rules/parameter_assignments.dart
test/rules/parameter_assignments_test.dart

pattern assignment support for `parameter_assignments`

---

lib/src/rules/non_constant_identifier_names.dart
test/rules/non_constant_identifier_names_test.dart

don't wildcard patterns w/ `non_constant_identifier_names`

---

test/rules/unnecessary_final_test.dart

`unnecessary_final` record pattern tests

---

test/rules/prefer_final_locals_test.dart

No other changes, just a sort.

Sort prefer_final_locals test cases

---

lib/src/rules/implicit_reopen.dart
test/rules/implicit_reopen_test.dart

`implicit_reopen` class type alias awareness

---

README.md

As we're on a publishing hiatus, there's no reason to draw attention to stale package pushes.

remove pub badges

---

test/rules/exhaustive_cases_test.dart
test/rules/unrelated_type_equality_checks_test.dart

See: #4256
/fyi @stereotype441

remove breaking `NON_EXHAUSTIVE_SWITCH` error code references

---

lib/src/rules/no_leading_underscores_for_library_prefixes.dart
lib/src/rules/no_leading_underscores_for_local_identifiers.dart
lib/src/util/ascii_utils.dart
lib/src/utils.dart

hasLeadingUnderscore extension cleanup

---

test/engine_test.dart

Fixes #4284
/cc @srawlins @bwilkerson 
/fyi @oprypin

fix Dart3 unsafe mixing in

---

lib/src/rules/prefer_final_locals.dart
test/rules/prefer_final_locals_test.dart

fix `prefer_final_locals` false positive for records in foreach loops

---

lib/src/extensions.dart
lib/src/rules/prefer_final_locals.dart
lib/src/rules/unnecessary_final.dart
test/rules/unnecessary_final_test.dart

`unnecessary_final` support for `ForEachPartsWithPattern`s

---

lib/src/rules/unnecessary_final.dart

tidy up formal parameter inspection

---

test/rules/prefer_final_in_for_each_test.dart

Adds ok variant to tests added in #4291 to avoid regressions

prefer_final_in_for_each_test for final records

---

lib/src/rules/no_leading_underscores_for_local_identifiers.dart
test/rules/no_leading_underscores_for_local_identifiers_test.dart

fix `no_leading_underscores_for_local_identifiers` pattern field over-reporting

---

lib/src/extensions.dart
lib/src/rules/constant_identifier_names.dart
lib/src/rules/no_leading_underscores_for_local_identifiers.dart
test/rules/constant_identifier_names_test.dart

fix `constant_identifier_names` pattern field over-reporting

---

lib/src/rules/non_constant_identifier_names.dart
test/rules/non_constant_identifier_names_test.dart

fix `non_constant_identifier_names` pattern field over-reporting

---

tool/machine.dart

/fyi @parlough (is this still being used?)

add fix status to machine output

---

test/rules/null_check_on_nullable_type_parameter_test.dart

enable test failing in resolver

---

test/rules/exhaustive_cases_test.dart
test/rules/unrelated_type_equality_checks_test.dart

update NON_EXHAUSTIVE_SWITCH error codes

---

CHANGELOG.md

The rule name is actually `implicit_reopen`.

Fix mistake on CHANGELOG.md

---

lib/src/rules/unnecessary_statements.dart
test/rules/all.dart
test/rules/unnecessary_statements_test.dart

fix `unnecessary_statements` pattern assignment false positive

---

lib/src/rules/prefer_final_fields.dart
test/rules/prefer_final_fields_test.dart

fix `prefer_final_fields` false positive for inherited setters

---

lib/src/rules/unnecessary_null_checks.dart

fix `unnecessary_null_checks` example

---

test/rules/use_build_context_synchronously_test.dart

No other changes; just sorting

Sort use_build_context_synchronously tests

---

lib/src/rules/literal_only_boolean_expressions.dart
test/rules/literal_only_boolean_expressions_test.dart

fix `literal_only_boolean_expressions` if-case false positives

---

tool/checks/driver.dart
tool/checks/rules/no_solo_tests.dart

Make `@soloTest`s break the build.
Follow-up from https://github.com/dart-lang/linter/pull/4371#discussion_r1199420285.

check for soloed tests

---

lib/src/rules/prefer_final_in_for_each.dart
test/rules/prefer_final_in_for_each_test.dart

fix `prefer_final_in_for_each` in "collection fors"

---

test/rules/all.dart
test/rules/unnecessary_this_test.dart

`unnecessary_this` shadowing in pattern false positive test

---

lib/src/rules/unreachable_from_main.dart
test/rules/unreachable_from_main_test.dart

This reverts commit b56190503725de2125b626ff1b3423192fa1f7ae.
Also: Add support for test_reflective_loader

Revert "Revert "unreachable_from_main: Report unreachable constructors (#4162)" (#4253)"

---

lib/src/rules/prefer_final_in_for_each.dart
test/rules/prefer_final_in_for_each_test.dart

pattern support for `prefer_final_in_for_each`

---

test/rule_test_support.dart
test/rules/always_specify_types_test.dart
test/rules/always_use_package_imports_test.dart
test/rules/exhaustive_cases_test.dart
test/rules/implicit_reopen_test.dart
test/rules/join_return_with_assignment_test.dart
test/rules/literal_only_boolean_expressions_test.dart
test/rules/no_duplicate_case_values_test.dart
test/rules/non_adjacent_strings_in_list_test.dart
test/rules/null_check_on_nullable_type_parameter_test.dart
test/rules/omit_local_variable_types_test.dart
test/rules/one_member_abstracts_test.dart
test/rules/parameter_assignments_test.dart
test/rules/prefer_final_locals_test.dart
test/rules/prefer_final_parameters_test.dart
test/rules/prefer_mixin_test.dart
test/rules/prefer_void_to_null_test.dart
test/rules/unnecessary_final_test.dart
test/rules/unnecessary_null_checks_test.dart
test/rules/unnecessary_nullable_for_final_variable_declarations_test.dart
test/rules/unnecessary_statements_test.dart
test/rules/unnecessary_this_test.dart
test/rules/unrelated_type_equality_checks_test.dart
test/rules/use_late_for_private_fields_and_variables_test.dart
test/rules/use_named_constants_test.dart
test/rules/void_checks_test.dart

🧹 remove unneeded `LanguageVersion300Mixin`

---

lib/src/rules/unreachable_from_main.dart

I've done all my TODOs and now my watch has ended.

Mark unreachable_from_main stable

---

test/all.dart
test/verify_checks_test.dart
tool/bot.sh
tool/checks/driver.dart

migrate custom check verification to a test

---

pubspec.yaml

Mark the package as not intended for publishing

---

tool/bot.sh

migrate to `dart test`

---

lib/src/rules/use_build_context_synchronously.dart
test/rules/use_build_context_synchronously_test.dart

The `visitIfStatement` body was really hard to understand, and in addressing a TODO, I saw that I had implemented a lot of the logic exactly backwards:
In the previous code, when the BuildContext expression was in a node that _follows_ an if/then statement, then we _first_ check the AsyncState of the condition, and _then_ look at the AsyncStates of the then-body and the else-body. The much simpler path is to first examine the then-body and the else-body. Then only under certain conditions do we need to keep looking backwards, to the AsyncState of the condition.
The bug highlighted by the TODO is seen in the two tests which are added.
CC @scheglov @keertip

use_build_context: Address TODO with async in if/else bodies

---

lib/src/rules/deprecated_member_use_from_same_package.dart

Fixes #4450
/cc @parlough @MaryaBelanger @bwilkerson @atsansone

use `@Deprecated` consistently

---

lib/src/rules/use_build_context_synchronously.dart
test/rules/use_build_context_synchronously_test.dart

This PR does not change any behavior. The only changes to the impl are to make some classes public, so that they can be unit tested.
The thrust of this PR is to convert most of the `use_build_context_synchronously` tests into unit tests of the primary visitor, `AsyncStateVisitor`. There are only a handful of _new_ tests; most are just converted tests, which are simplified to not concern themselves with lint reports, but with the question: "What is the async state between these two nodes." I think these tests help a lot in improving the understandability of this rule.

AsyncStateVisitor unit tests

---

lib/src/rules/prefer_conditional_assignment.dart

Here's a crack at a reword.
Feedback welcome.
Fixes #4398
/cc @bwilkerson @hixie

tweak `prefer_conditional_assignment` messaging

---

lib/src/rules/empty_statements.dart
test/rules/all.dart
test/rules/empty_statements_test.dart

stop flagging empty statements in switch pattern cases

---

tool/canonical/gh_labels.dart
tool/gh/get_labels.dart
tool/github.dart
tool/query.dart
tool/scorecard.dart

Don't rely on nullable authentication

---

README.md
doc/writing-lints.md

Contributes to https://github.com/dart-lang/linter/issues/4460 and https://github.com/dart-lang/site-www/issues/4499

Update more site links to point to dart.dev

---

.github/workflows/gh-pages.yml
tool/doc.dart

It's currently unused and won't continue to work in the future. We can consider reintroducing similar functionality in the future if we need it.
Closes #4459 
Contributes to https://github.com/dart-lang/linter/issues/4424

Remove markdown doc generation functionality

---

lib/src/rules/library_private_types_in_public_api.dart
test/rules/library_private_types_in_public_api_test.dart

Follow-up on #4533.
Fixes #4470

handle `library_private_types_in_public_api` false positives for modified classes

---

lib/src/rules/public_member_api_docs.dart
test/rules/public_member_api_docs_test.dart

fix `public_member_api_docs` overreporting on effectively private constructors

---

lib/src/extensions.dart
lib/src/rules/library_private_types_in_public_api.dart
lib/src/rules/public_member_api_docs.dart
test/rules/public_member_api_docs_test.dart

Fixes: #4521
Takes care of a bit of code duplication too (though there are more opportunities).
(Sorry for the sorting churn.)

fix `public_member_api_docs` to not overreport elements marked @internal

---

lib/src/rules/prefer_final_locals.dart
test/rules/prefer_final_locals_test.dart

fix `prefer_final_locals` forLoop over-reporting

---

lib/src/rules/use_build_context_synchronously.dart
test/rules/use_build_context_synchronously_test.dart

This one is tricky because of fall-through, but the tests highlight a few fixed situations:
* The async state of a case-statements does not affect a case-when-clause.
* The async state of cases that follow one case does not affect it.
* The async state of earlier case-when-clauses can affect later case-statements.
* Mounted checks can take into account fall-through.

Better handle awaits and mounted checks in fall-through switch cases

---

lib/src/rules/deprecated_member_use_from_same_package.dart
test/rules/deprecated_member_use_from_same_package_test.dart

Fixes https://github.com/dart-lang/linter/issues/4541

Report deprecated extension use

---

tool/move_legacy_test.dart

This PR adds a feature to this script which allows it to update existing new-style tests.
It makes an assumption that the last line in the existing script containing `^}` is the last line of the test class. If there are local helper functions or something similar that may not fit. 🤷  We'll see.

Support existing new-style tests in move_legacy_test.dart

---

doc/use_build_context_synchronously.md

Since this is an exceptionally complex rule, I thought I'd write up a separate doc for it's design. I'd love love feedback, especially notes of where things still don't make sense, and I should add more notes, or examples.

A doc for use_build_context_synchronously

---

test/rules/void_checks_test.dart
test_data/rules/void_checks.dart

This one is a big test data file, so I only move some test cases in this PR.

Move _some_ void_checks tests

---

lib/src/cli.dart
lib/src/extensions.dart
test/all.dart
test/util/annotation_test.dart
test/verify_reflective_test_suites.dart

This reverts commit 15b8ad7cd8c9bbd1ef659eb0aaf14620cfc40af4.
I fumbled a git command and accidentally committed the above w/o a review. 😬 

Revert "misc. cleanup"

---

lib/src/cli.dart
lib/src/extensions.dart
test/all.dart
test/annotation_test.dart
test/verify_reflective_test_suites.dart

Misc. cleanup.
* refactored to an extension
* de-orphaned a test
* updated a test constant ref

misc. tidying up

---

tool/scorecard.dart

Follow-up from: https://github.com/dart-lang/linter/issues/4460#issuecomment-1666039837
/cc @parlough @bwilkerson @srawlins

update lint rule link

---

doc/lint-lifecycle.md
doc/use_build_context_synchronously.md
lib/src/rules/avoid_redundant_argument_values.dart
lib/src/rules/prefer_final_fields.dart
lib/src/rules/use_build_context_synchronously.dart
test/rules/unnecessary_string_interpolations_test.dart
test/rules/void_checks_test.dart
test_data/mock_packages/meta/lib/meta.dart

tidy up spelling

---

lib/src/rules/avoid_return_types_on_setters.dart
lib/src/rules/curly_braces_in_flow_control_structures.dart
lib/src/rules/prefer_generic_function_type_aliases.dart
lib/src/rules/slash_for_doc_comments.dart
lib/src/rules/test_types_in_equals.dart
lib/src/rules/unnecessary_const.dart
lib/src/rules/unnecessary_new.dart
lib/src/rules/unnecessary_string_escapes.dart
lib/src/rules/use_function_type_syntax_for_parameters.dart
pubspec.yaml
test/rule_test.dart
test/rules/prefer_const_constructors_test.dart

Fixes https://github.com/dart-lang/linter/issues/3389

Bump to analyzer 6.1.0

---

lib/src/rules/library_private_types_in_public_api.dart
lib/src/rules/public_member_api_docs.dart
test/rules/library_private_types_in_public_api_test.dart

extension type support for `library_private_types_in_public_api`

---

test/rules/directives_ordering_test.dart
test/rules/overridden_fields_test.dart
test/rules/use_string_buffers_test.dart

cleanup old test string metadata

---

lib/src/rules/prefer_final_fields.dart
test/rules/prefer_final_fields_test.dart

extension type support for `prefer_final_fields`

---

test/rules/unnecessary_this_test.dart

extension type support for `unnecessary_this`

---

lib/src/rules/avoid_private_typedef_functions.dart
test/rules/avoid_private_typedef_functions_test.dart

fix `avoid_private_typedef_functions` falses positive for records

---

pubspec.yaml
test/rules/hash_and_equals_test.dart
test/rules/library_private_types_in_public_api_test.dart
test/rules/prefer_final_fields_test.dart
test/rules/public_member_api_docs_test.dart
test/rules/sort_unnamed_constructors_first_test.dart
test/rules/unnecessary_constructor_name_test.dart
test/rules/use_late_for_private_fields_and_variables_test.dart

bump to analyzer 6.2.0

---

CHANGELOG.md
README.md
pubspec.yaml

One last publish to update the readme, description and links on pub.dev

prepare v1.30.1 discontinue release
