dart-lang/linter

bin/linter.dart, lib/src/analysis.dart
This option causes the linter to show results for all libraries
reachable from the project via import and export directives.
=> Add "--visit-transitive-closure" command line option.

lib/src/analysis.dart
This syntax won't be available until Dart 1.9.
=> Don't use "yield" in AnalysisDriver._getAllUnitSources().

bin/linter.dart, lib/src/formatter.dart
This suppresses output of the individual lint warnings, but preserves
the summary and statistics output.
=> Add a --quiet option.

lib/src/rules/one_member_abstracts.dart, test/rules/one_member_abstracts.dart
=> Exclude getters/setters from one_member_abstracts lint.  Fix #64.

lib/src/linter.dart
Catch-all group for lints that catch possible coding errors.
@danschultz @bwilkerson
=> Error group.

pubspec.yaml
(Required in order to use ^ syntax.)
=> Fixed SDK constraint [TBR].

pubspec.yaml
The only breaking change in analyzer 0.26 is to
UriResolver.resolveUri(), which linter doesn't use.
@pq
=> Widen analyzer constraint to include analyzer version 0.26.

lib/src/config.dart, lib/src/linter.dart, test/config_test.dart
Specifically, allows for
* groups to be unspecified and
* rules to enumerated in simple lists (rather than maps from names to enablement state).
=> Support for shorthand options.

lib/src/config.dart, test/config_test.dart
Corrects a typo: `'enabled:'` => `'enabled'` that breaks enablement via options files.
=> Fix rule enablement arg setting.

lib/src/rules/overriden_field.dart, test/rules/overriden_field.dart
When overriding a field, don't lint if the overriden field is inherited through an interface (implements keyword).
dart-lang/linter#230
=> False positive fix for overriden_field rule.

bin/linter.dart
I didn't know how to specify the `--lints` option, and had to attempt it a few times before it worked. So here's some more help text. Prints as:
```
$ dart bin/linter.dart --help
Lints Dart source files and pubspecs.
Usage: linter <file>
-h, --help                             Show usage information.
-s, --stats                            Show lint statistics.
--[no-]visit-transitive-closure    Visit the transitive closure of imported/exported libraries.
-q, --[no-]quiet                       Don't show individual lint errors.
--machine                          Print results in a format suitable for parsing.
-c, --config                           Use configuration from this file.
--dart-sdk                         Custom path to a Dart SDK.
--lints                            A list of …
```
=> Tweak help text

lib/src/rules.dart, lib/src/rules/unawaited_futures.dart, test/rules/unawaited_futures.dart
Triggers on Future non-assignment expression statements inside async
bodies, with small, reasonable exceptions found in real codebases.
Ported from scissors:
https://github.com/google/dart-scissors/blob/7d7b1ab384fbd3b86e1f66181b54884c5967fe19/lib/src/checker/transformer.dart
=> Add an unawaited_futures lint (#164)

lib/src/rules/iterable_contains_unrelated_type.dart
Dynamic types should return null when finding the iterable type argument. In particular superclass and allSupertypes properties are not defined for those types and NPE will be thrown during analysis.
=> Bugfix: iterable_contains_unrelated_type

lib/src/rules.dart, lib/src/rules/close_sinks.dart, test/_data/close_sinks/src/a.dart, test/integration_test.dart
First attempt, I am facing a problem I don't know how to solve, which is I can't run the test, I get the following:
```
± |185_close_sinks {2} ✓| → dart test/util/solo_test.dart close_sinks
unittest-suite-wait-for-done
Task failed: GenerateLintsTask for source /home/alexeieleusis/development/dart/linter/test/rules/close_sinks.dart
ERROR: close_sinks
Test failed: Caught AnalysisException: Cannot compute DART_ERRORS for /home/alexeieleusis/development/dart/linter/test/rules/close_sinks.dart
Caused by Unexpected exception while performing GenerateLintsTask for source /home/alexeieleusis/development/dart/linter/test/rules/close_sinks.dart
...
```
If I instead run the linter directly, I get the expected lints
```
± |185_close_sinks {2} ✓| → dart ~/development/dart/linter/bin/linter.dart …
```
=> Close instances of dart.core.Sink

lib/src/rules.dart, lib/src/rules/list_remove_unrelated_type.dart, lib/src/util/unrelated_types_visitor.dart, test/rules/list_remove_unrelated_type.dart
=> Linter should catch cases of passing a non-T value to List.remove().

lib/src/rules/cancel_subscriptions.dart, lib/src/rules/close_sinks.dart, lib/src/rules/iterable_contains_unrelated_type.dart, lib/src/rules/list_remove_unrelated_type.dart, lib/src/rules/only_throw_errors.dart, lib/src/rules/overridden_fields.dart, lib/src/rules/unrelated_type_equality_checks.dart
These have been in use for a while and some tools require not being experimental to loudly report instances.
=> Remove experimental flag from a few rules.

lib/src/linter.dart, lib/src/util.dart, test/rule_test.dart, test/rules/camel_case_types.dart
Closes: https://github.com/dart-lang/linter/issues/287
I am not yet _terribly_ familiar with all of the lints, but I think I modified the two lints (and added simple test cases) that we would run into. Both `camel_case_types, `constant_identifier_names`, and `non_constant_identifier_names` should allow the `$` character in between case changes.
i.e., now valid:
- `camel_case_types`: `Foo$Bar`
- `constant_identifier_names` and `non_constant_identifier_names`: `foo$Bar`
=> Ignore '$' in identifiers; we use in generated code.

lib/src/rules.dart, lib/src/rules/invariant_booleans.dart, lib/src/rules/literal_only_boolean_expressions.dart, lib/src/util/boolean_expression_utilities.dart, lib/src/util/dart_type_utilities.dart, lib/src/util/leak_detector_visitor.dart, lib/src/util/tested_expressions.dart, test/rules/invariant_booleans.dart, test/rules/literal_only_boolean_expressions.dart
I would like to think of this as the first pass implementation (or even first draft) since is quite complex to figure out false things and I am not an expert in either parsing, deducting, logic programming or whatsoever. I am open to discuss the feature and approach and I am aware that might be too complex to be included in the linter. Still I think adds a lot of value since it is very common to break this rule as you can see in the metrics here https://nemo.sonarqube.org/
Ran this rule in the following projects dart-lang/sdk, dart-lang/markdown and dart-lang/reflectable and these were the only occurrences reported, there are some debatable false positives that rely on side effects. SDK at commit 8caa5a6dcb9f35a101516460d6b0abf12affeaf5
``` …
```
=> Conditions should not unconditionally evaluate to "TRUE" or to "FALSE"

test/util/rule_debug.dart
As per conversation in https://github.com/dart-lang/linter/pull/303.
/cc @kevmoo
=> Restore solo test debugger.

lib/src/util.dart, test/rule_test.dart
I missed a couple of use cases with https://github.com/dart-lang/linter/pull/290.
This covers any rule that uses `identifier` or `lowerCamelCase` RegExp checks, including:
- constant_identifier_names
- non_constant_identifier_names
This solves generated code issues in Angular (@ferhatb)
=> Cover more use cases where '$' may be used

lib/src/rules/prefer_final_fields.dart, test/rules/prefer_final_fields.dart
fixes https://github.com/dart-lang/linter/issues/325
=> prefer_final_fields: Don't report fields that are used in the same library.

lib/src/rules.dart, lib/src/rules/recursive_getter.dart, test/rules/recursive_getter.dart
Flag getters recursively returning themselves.
Ran the rule with no problems on SDK and Flutter codebases.
Fixes https://github.com/dart-lang/sdk/issues/27704
=> New rule: recursive_getter.

lib/src/util/leak_detector_visitor.dart, test/_data/cancel_subscriptions/cancel_subscriptions.dart, test/_data/close_sinks/src/a.dart, test/integration_test.dart
Fixes https://github.com/dart-lang/linter/issues/317
=> LeakDetectorVisitor: When analyzing places where a node is referenced, include the whole library.

lib/src/util/leak_detector_visitor.dart, test/_data/close_sinks/src/a.dart
Fixes https://github.com/dart-lang/linter/issues/336
=> LeakDetectorVisitor: Use elements instead of strings when resolving identifiers.

lib/src/rules.dart, lib/src/rules/no_adjacent_strings_in_list.dart, test/rules/no_adjacent_strings_in_list.dart
Simple rule, but can be useful in some cases.
There're no such lints in SDK and Flutter.
=> No adjacent strings in list. Fixes #225.

lib/src/util/leak_detector_visitor.dart, test/_data/close_sinks/src/a.dart
Fixes https://github.com/dart-lang/linter/issues/341
This goes on top of https://github.com/dart-lang/linter/pull/343, so this needs that to be merged before merging, and only consider the last commit when reviewing.
=> LeakDetectorVisitor: Include cascade operators when searching for invocations on variable.

lib/src/rules/cascade_invocations.dart, test/rules/cascade_invocations.dart
Fixes https://github.com/dart-lang/linter/issues/349
=> cascade_invocations: Exclude method invocations with all operator but (.) and (..).

lib/src/rules/cascade_invocations.dart, test/rules/cascade_invocations.dart
Fixes https://github.com/dart-lang/linter/issues/350
=> cascade_invocations: Exclude top level function invocations in aliased imported library.

lib/src/rules/cascade_invocations.dart, test/rules/cascade_invocations.dart
Fixes https://github.com/dart-lang/linter/issues/356
=> cascade_invocations: Exclude static method invocations.

lib/src/rules.dart, lib/src/rules/no_duplicate_case_values.dart, test/rules/no_duplicate_case_values.dart
This rule has found 4 lints (2 x 2 duplicated cases) in SDK and 0 in Flutter.
Here's the thing with SDK:
KeyCode.WIN_KEY_LEFT and KeyCode.META have same value, so _convertKeyCodeToKeyName will return _KeyName.META instead of _KeyName.WIN for first constant as may be expected.
Check html_dart2js.dart lines 41086 and 41100, and html_dartium.dart line 45611 and 45625.
=> Add no_duplicate_cases rule (#354)

BUILD.gn
This is necessary for correctly running the dart analyzer cli for fuchsia.
=> Add BUILD.gn to linter package

pubspec.yaml
* alpha to pickup `invariant_booleans` fix.
@bwilkerson @scheglov
=> Linter 0.1.30-alpha.1.

lib/src/rules/invariant_booleans.dart
Sample code uses boolean, most probably as a relic of the original C++ rule.
=> Fix example code

lib/src/ast.dart, lib/src/rules/annotate_overrides.dart, lib/src/rules/implementation_imports.dart, lib/src/rules/invariant_booleans.dart, lib/src/rules/no_duplicate_case_values.dart, lib/src/rules/package_prefixed_library_names.dart, lib/src/rules/prefer_final_fields.dart, lib/src/rules/public_member_api_docs.dart, lib/src/rules/test_types_in_equals.dart, lib/src/rules/unawaited_futures.dart, lib/src/rules/unrelated_type_equality_checks.dart, lib/src/rules/valid_regexps.dart, lib/src/util/leak_detector_visitor.dart, lib/src/util/unrelated_types_visitor.dart
This will allow analyzer's AST to be decoupled from its element model.
=> Modify linter to make use of analyzer's new "resolution map" interface.

tool/doc.dart
Currently, the link to `options/options.html` is hard to find, even if you know what you're looking for. This change:
- Makes the link much more visible
- Clearly explains how to use it.
=> Make the auto-generated options list more visible

tool/doc.dart
In favor of just referencing the dartlang doc as the single source of truth.
Follow-up from: https://github.com/dart-lang/linter/pull/384#pullrequestreview-19956393
@zoechi @filiph @danrubel
=> Stop mentioning .analysis_options by name (#384).

.analysis_options, lib/src/analyzer.dart, lib/src/ast.dart, lib/src/formatter.dart, lib/src/rules/annotate_overrides.dart, lib/src/rules/empty_catches.dart, lib/src/rules/empty_constructor_bodies.dart, lib/src/rules/no_duplicate_case_values.dart, lib/src/rules/package_api_docs.dart, lib/src/rules/package_prefixed_library_names.dart, lib/src/rules/pub/package_names.dart, lib/src/rules/public_member_api_docs.dart, lib/src/rules/unnecessary_brace_in_string_interp.dart
* roundup all non-API calls
* enable `implementation_imports` lint
Fixes: #394 
@bwilkerson
=> Bring all non-API accesses into analyzer facade (#394).

lib/src/rules.dart, lib/src/rules/prefer_is_empty.dart, test/mock_sdk.dart, test/rules/prefer_is_empty.dart
Prefer using `isEmpty` or `isNotEmpty` over comparison of length with 0.
Description from [Effective Dart](https://www.dartlang.org/guides/language/effective-dart/usage#dont-use-length-to-see-if-a-collection-is-empty).
There are 11 lints in SDK and 1 in Flutter.
=> Rule prefer_is_empty.

lib/src/rules/invariant_booleans.dart, test/rules/invariant_booleans.dart
This allows each fact to be available individually when looking for contradictions.
FIXES: https://github.com/dart-lang/linter/issues/373
=> Split conjunctions when creating collections with known facts deduced  from the conditions in ancestor nodes.

lib/src/rules/invariant_booleans.dart, lib/src/util/tested_expressions.dart, test/rules/invariant_booleans.dart
FIXES #372
N.B. Only the last commit fixes the bug, the other two are the commits in https://github.com/dart-lang/linter/pull/402 and https://github.com/dart-lang/linter/pull/401
=> invariant_booleans: Extend rule to analyze simple identifiers.

tool/rule.dart
* update copyright
* add an import of `linter/src/analyzer.dart` to encourage proper access to analyzer APIs
@bwilkerson
=> Tweak rule codegen bits.

lib/src/rules.dart, lib/src/rules/prefer_contains.dart, test/mock_sdk.dart, test/rules/prefer_contains.dart
Prefer `contains` over `indexOf() != -1` in Lists and Strings.
Closes #364.
Very similar to PR #353.
There's 6 such lints in SDK (2 on lists and 4 on strings) and 0 in Flutter.
=> Rule prefer_contains.

.analysis_options, bin/linter.dart, lib/src/formatter.dart, lib/src/rules/invariant_booleans.dart, lib/src/rules/sort_constructors_first.dart, lib/src/rules/unnecessary_getters_setters.dart, lib/src/util/dart_type_utilities.dart, lib/src/util/leak_detector_visitor.dart, test/engine_test.dart, test/formatter_test.dart, test/rule_test.dart, tool/doc.dart
Disabled `prefer_final_locals` because it has too many occurrences and `cascade_invocations` because it was linting the tests.
Also, my team disabled the rule because the way is implemented is not really useful for us so I might rewrite it to be aligned with usages that look like builder/fluent api.
Some changes are just dartfmt being run.
FIXES https://github.com/dart-lang/linter/issues/407
=> Cleanup linter warnings.

lib/src/rules.dart, lib/src/rules/directives_ordering.dart, test/_data/directives_ordering/dart_imports_go_first/bad.dart, test/integration_test.dart
Verify that all package:dart imports go first. From https://www.dartlang.org/guides/language/effective-dart/style#do-place-dart-imports-before-other-imports
=> New rule: dart_imports_go_first

lib/src/rules/directives_ordering.dart, test/_data/directives_ordering/package_imports_before_relative/bad.dart, test/integration_test.dart
In this second commit we verify that all package: imports go before relative. 
From https://www.dartlang.org/guides/language/effective-dart/style#do-place-package-imports-before-relative-imports
=> Extend rule: directives_ordering with package: imports before relative. 

lib/src/rules/directives_ordering.dart, test/_data/directives_ordering/lint_one_node_no_more_than_once/bad.dart, test/_data/directives_ordering/third_party_package_imports_before_own/bad.dart, test/integration_test.dart
Extend rule: directives_ordering
In this third commit we verify that all third-party package: imports go before own. From https://www.dartlang.org/guides/language/effective-dart/style#prefer-placing-third-party-package-imports-before-other-imports
Also take care of linting each node at most once.
=> Third party package imports before own

lib/src/rules/directives_ordering.dart, test/_data/directives_ordering/export_directives_after_import_directives/bad.dart, test/integration_test.dart
In this fourth commit we verify that exports directives go after import directives. From https://www.dartlang.org/guides/language/effective-dart/style#do-specify-exports-in-a-separate-section-after-all-imports
=> Extend rule: directives_ordering

lib/src/rules/directives_ordering.dart, test/_data/directives_ordering/sort_directive_sections_alphabetically/bad.dart, test/_data/directives_ordering/third_party_package_imports_before_own/bad.dart, test/integration_test.dart
In this fifth commit we verify that each directive section must be sorted alphabetically. From https://www.dartlang.org/guides/language/effective-dart/style#do-sort-sections-alphabetically
=> Extend rule: directives_ordering with directive sections sorted alphabetically

lib/src/rules/prefer_final_fields.dart, test/rules/prefer_final_fields.dart
Fixes https://github.com/dart-lang/linter/issues/441
=> Modify rule: prefer_final_fields to not lint if field never initializes.

lib/src/rules.dart, lib/src/rules/use_adjacent_strings_to_concatenate_literals.dart, test/rules/use_adjacent_strings_to_concatenate_literals.dart
In this commit we implement this rule from: https://www.dartlang.org/guides/language/effective-dart/usage#do-use-adjacent-strings-to-concatenate-string-literals
=> New rule: adjacent_strings_to_concatenate_literals

lib/src/rules.dart, lib/src/rules/prefer_interpolation_to_compose_strings.dart, lib/src/util/dart_type_utilities.dart, test/rules/prefer_interpolation_to_compose_strings.dart, test/rules/use_adjacent_strings_to_concatenate_literals.dart
In this commit we implement this rule from: https://www.dartlang.org/guides/language/effective-dart/usage#prefer-using-interpolation-to-compose-strings-and-values
Fixes https://github.com/dart-lang/linter/issues/448
=> New rule: prefer_interpolation_to_compose_strings

lib/src/rules.dart, lib/src/rules/avoid_function_literal_in_foreach_method.dart, test/rules/avoid_function_literal_in_foreach_method.dart
Fixes https://github.com/dart-lang/linter/issues/457
=> New rule: avoid_function_literal_in_foreach_method

lib/src/rules/invariant_booleans.dart, test/rules/invariant_booleans.dart
Fixes https://github.com/dart-lang/linter/issues/337
=> invariant_boolean: When searching for references reassignment include PostfixExpression and similar, e.g. variable++.

lib/src/rules/unnecessary_lambdas.dart, test/rules/unnecessary_lambdas.dart
Fixes:
1.- Check that arguments and parameters lengths are equal
2.- Check if there is a ? operator in the target of a method invocation
=> Fix rule: unnecessary_lambda

tool/doc.dart
Net-net:
dart tool/doc.dart -o $path_to_docs
will work if `$path_to_docs` is the lint rule subdir (as designed) but also if it’s the parent (a common mistake).
@bwilkerson @alexeieleusis
=> Update `doc` tool to be more outdir-flexible.

lib/src/rules/do_not_check_for_null_in_equality_operators.dart, test/rules/do_not_check_for_null_in_equality_operators.dart
Fixes #530
This was caused by `node.parameters.parameters` on getters.
=> Fix rule: do_not_check_for_null_in_equality_operators

lib/src/rules.dart, lib/src/rules/always_put_control_body_on_new_line.dart, test/rules/always_put_control_body_on_new_line.dart
This addresses [Flutter style: Separate the 'if' expression from its statement](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#separate-the-if-expression-from-its-statement) that is present in #142
=> add always_put_control_body_on_new_line

pubspec.yaml
Pulls in _Driver enableAssertInitializer backport_ (https://github.com/dart-lang/sdk/commit/fbafaf05303e224a41cf8c551fa536c46e6dc5af).
Should unblock: https://github.com/dart-lang/linter/pull/630
@bwilkerson 
FYI @a14n
=> Bump analyzer dep to `0.29.11`

test/rules/prefer_adjacent_string_concatenation.dart
This test got missed in a rename and so was orphaned. 😢 
@bwilkerson @alexeieleusis
=> Un-orphan `prefer_adjacent_string_concatenation` test.

lib/src/rules/cascade_invocations.dart, test/rules/cascade_invocations.dart
For other invocations it may hurt readability anyways.
Fixes https://github.com/dart-lang/linter/issues/661
=> cascade_invocations: Method invocations should be linted only if target is simple identifier.

lib/src/rules/literal_only_boolean_expressions.dart, test/rules/invariant_booleans.dart, test/rules/literal_only_boolean_expressions.dart
Fixes https://github.com/dart-lang/linter/issues/658
=> literal_only_boolean_expressions: Only check literals on left side for ??.ˆ

CHANGELOG.md, tool/travis.sh
* enables all the lints for benchmarking
* (note that `all.yaml` is guaranteed to be complete by the 'all.yaml' test in `integration_test.dart`)
Follow-up from https://github.com/dart-lang/linter/pull/670.
@devoncarew
=> Run lint benchmarks w/ all the lints.

bin/linter.dart, lib/src/analyzer.dart, lib/src/formatter.dart, tool/travis.sh
New benchmark mode that prints lint stats based on the best of 10 runs.
Follow-up from: https://github.com/dart-lang/linter/issues/669
@devoncarew @bwilkerson
=> Add `--benchmark` support.

analysis_options.yaml, example/all.yaml, lib/src/rules.dart, lib/src/rules/prefer_single_quotes.dart, test/rules/prefer_single_quotes.dart
Do not suggest double quotes for
- strings with ' in them naturally
- strings containing other strings ie "foo ${'bar'}"
- strings within other strings (we check 'bar' in the case above!)
Also be careful for the difference between interpolated and non
interpolated strings.
cc @mk13
=> Add a lint rule for preferring single quote strings

lib/src/rules/directives_ordering.dart, test/_data/directives_ordering/export_directives_after_import_directives/bad.dart, test/_data/directives_ordering/export_directives_after_import_directives/dummy4.dart, test/integration_test.dart
Currently the `directives_ordering` lint is fine with 
```
import 'package:a/a.dart';
export 'package:b/b.dart';
```
but complains with the message _"Specify exports in a separate section after all imports."_  if a file contains a part directive.
```
import 'package:a/a.dart';
export 'package:b/b.dart';
part 'c.dart';
```
The language requires that export come before part directives but the linter didn't consider that case. This PR assumes the part directives (if present) will be after the export directives when considering the order of imports and exports.
=> Skip part directives in export after import lint

lib/src/rules/prefer_asserts_in_initializer_list.dart, test/_data/prefer_asserts_in_initializer_list/lib.dart, test/integration_test.dart, test/rules/prefer_asserts_in_initializer_list.dart
With this change the lint is on individual `assert` and it checks that the `assert` can be moved into initializer list (no access to field, method, this)
=> update prefer_asserts_in_initializer_list to lint individual asserts

lib/src/rules/recursive_getters.dart, test/rules/recursive_getters.dart
=> recirsive_getter: Fix false positives when returning the same property on a different instance.

lib/src/rules/cascade_invocations.dart, test/rules/cascade_invocations.dart
Fixes https://github.com/dart-lang/linter/issues/701
=> cascade_invocations: Don't lint cases where assignment expression is conditional

lib/src/rules/cascade_invocations.dart, test/rules/cascade_invocations.dart
Fixes https://github.com/dart-lang/linter/issues/694
=> cascade_invocations: Don't lint static properties.

bin/linter.dart, pubspec.yaml, test/_data/directives_ordering/export_directives_after_import_directives/bad.dart, test/engine_test.dart, test/integration_test.dart, test/mock_sdk.dart, test/rule_test.dart
See: #743
**NOTE:** build greenness depends on a new version of analyzer w/ the corresponding engine changes to be published (https://github.com/dart-lang/sdk/issues/30239). I'll update the pubspec once that's published. 👍 
@scheglov @bwilkerson
=> Update linter to use new driver-based engine (#743).

lib/src/rules/annotate_overrides.dart, lib/src/rules/avoid_init_to_null.dart, lib/src/rules/hash_and_equals.dart, lib/src/rules/invariant_booleans.dart, lib/src/rules/literal_only_boolean_expressions.dart, lib/src/rules/no_adjacent_strings_in_list.dart, lib/src/rules/no_duplicate_case_values.dart, lib/src/rules/only_throw_errors.dart, lib/src/rules/package_api_docs.dart, lib/src/rules/prefer_single_quotes.dart, lib/src/rules/public_member_api_docs.dart, lib/src/rules/slash_for_doc_comments.dart, lib/src/rules/sort_unnamed_constructors_first.dart, lib/src/rules/unnecessary_null_aware_assignments.dart, lib/src/rules/unnecessary_null_in_if_null_operators.dart, lib/src/rules/use_rethrow_when_possible.dart, test/rule_test.dart
* new test asserting rule descriptions are ‘.’ terminated
* fixes for ill-formed descriptions
@bwilkerson
=> Ensure rule descriptions are well-formed.

test/engine_test.dart
(`expect` automatically wrappers values in `equals` matchers.)
@bwilkerson
=> Remove gratuitous `equals` matcher calls.

test/rules/literal_only_boolean_expressions.dart
Addressing missed cases flagged by coveralls:
https://coveralls.io/builds/12658358/source?filename=lib%2Fsrc%2Frules%2Fliteral_only_boolean_expressions.dart
@bwilkerson @alexeieleusis
=> Test cases for `literal_only_boolean_expressions`.

test/rules/use_string_buffers.dart
@bwilkerson 
As discussed, I'm exploring (and may open an issue to track) why `s = s + 'foo'` is OK in the foreach case.  In the meantime, this at least gets the logic better under coverage.
=> Improve `use_string_buffer` test coverage.

lib/src/analyzer.dart, lib/src/ast.dart, lib/src/rules/always_specify_types.dart, lib/src/rules/camel_case_types.dart, lib/src/rules/constant_identifier_names.dart, lib/src/rules/empty_catches.dart, lib/src/rules/library_names.dart, lib/src/rules/library_prefixes.dart, lib/src/rules/literal_only_boolean_expressions.dart, lib/src/rules/non_constant_identifier_names.dart, lib/src/rules/pub/package_names.dart, lib/src/rules/type_annotate_public_apis.dart, lib/src/utils.dart, test/rule_test.dart, test/rules/constant_identifier_names.dart, test/rules/library_prefixes.dart
* Updates library prefix matching to allow leading `_`s.
* Inlines matcher regexps (decoupling from analyzer; see also, https://github.com/dart-lang/sdk/commit/1c5101e4a65484c2f3f28e4d11c1fee48c9b4c51).
Fixes: #684
Fixes: #769
@bwilkerson 
FYI @natebosch
=> Update library prefix matcher; inline APIs (#684,#769).

lib/src/utils.dart, test/rule_test.dart, test/rules/library_prefixes.dart
=> Update library prefix checking to allow leading `$`s (#294).

.travis.yml
Making the default explicit, silences this build spam:
https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming?utm_source=web&utm_medium=banner&&utm_campaign=trusty-default
@bwilkerson
=> Make trusty default distro explicit.

example/all.yaml, lib/src/rules.dart, lib/src/rules/unnecessary_statements.dart, test/rules/unnecessary_statements.dart
Allow expression statements which clearly have side effects, and allow
expression statements being used as control flow for expressions that
have side effects.
=> New rule to detect (usually) unnecessary statements (no clear effects)

lib/src/rules/comment_references.dart, test/rules/comment_references.dart
Update `comment_references` to check for keywords that are not treated as references by the parser but should be flagged by the linter.
Fixes: #808.
@bwilkerson
=> Fix comment_references to flag keywords (#808).

lib/src/rules/avoid_returning_this.dart, test/rules/avoid_returning_this.dart
This modifies the avoid_returning_this rule to ignore MethodDeclaration nodes when they are defining operators.  See issue #791 for discussion.
=> Have avoid_returning_this rule ignore operators

example/all.yaml, lib/src/rules.dart, lib/src/rules/avoid_unused_constructor_parameters.dart, test/rules/avoid_unused_constructor_parameters.dart
This rule, as per #799, lints instances within constructors where parameters are defined but not used.
=> Create rule avoid_unused_constructor_parameters

lib/src/utils.dart, test/rules/non_constant_identifier_names.dart
Better late than never!
@srawlins.
Fixes: #687.
=> Allow underscores around numbers in `non_constant_identifier_names`.

lib/src/rules/comment_references.dart, test/rules/comment_references.dart
=> Fix `comment_references` in the face of incomplete references (#819)

lib/src/rules/avoid_positional_boolean_parameters.dart, test/rules/avoid_positional_boolean_parameters.dart
Fix false positive for `avoid_positional_boolean_parameters` on `[]=` ops.
Fixes: #803.
@a14n @bwilkerson
=> Fix false positive for `avoid_positional_boolean_parameters` on `[]=`

lib/src/rules/public_member_api_docs.dart
- fix an exception in the public_member_api_docs (in `uri.toFilePath()`; fix https://github.com/dart-lang/linter/issues/822)
@pq @scheglov @bwilkerson
=> fix an issue with the public_member_api_docs lint

lib/src/rules/prefer_interpolation_to_compose_strings.dart, test/rules/prefer_interpolation_to_compose_strings.dart
Allow concatenation of two non-literal strings in `prefer_interpolation_to_compose_strings`.
Fixes: #735
@bwilkerson @alexeieleusis
=> Allow two non-literals in `prefer_interpolation_to_compose_strings`

lib/src/rules/avoid_as.dart, lib/src/rules/avoid_init_to_null.dart, lib/src/rules/directives_ordering.dart, lib/src/rules/implementation_imports.dart, lib/src/rules/package_api_docs.dart
=> Fix broken markdown doc links (#840).

test/rules/always_specify_types.dart
See: https://github.com/dart-lang/linter/issues/851
@bwilkerson
=> Test to verify optionalTypeArgs are respected in generic methods.

lib/src/rules/avoid_unused_constructor_parameters.dart, test/rules/avoid_unused_constructor_parameters.dart
=> Handle external constructor in avoid_unused_constructor_parameters

lib/src/util/tested_expressions.dart
There is a question about whether LinkedHashSet will implement HashSet, in Dart 2.0. To reduce the friction, and just for more standard typing, we should type variables, parameters, and return values to Set, rather than HashSet, when there's no reason to hold these objects to act like HashMaps.
CC @lrhn @keertip
=> Type variables, parameters, and return values as Set, not HashSet

tool/doc.dart
Currently:
but should be consistent with the homepage:
This tweak makes it so!
@bwilkerson
=> Fix title and header for lint index.html.

test/engine_test.dart, test/mocks.dart
mockito has changed, but I don't see why we were using it in this case anyway, so I converted this mock to not use it in order to get around a type error.
=> Fix a type error related to mocks

pubspec.yaml, tool/grind.dart
Fixes: https://github.com/dart-lang/linter/issues/886
While this works, the ergonomics aren't great.
I'd prefer `grind rule foo` but I think that's not how grind works.  Also: it would be great to not lose `valueHelp`.
@devoncarew: can you point me to any examples that show help for args?  How is that done in the "new" world?
cc @bwilkerson
=> Fix grind.dart

lib/src/util/condition_scope_visitor.dart, test/rules/invariant_booleans.dart
They become meaningless outside the body of the for loop.
Fixes https://github.com/dart-lang/linter/issues/811
=> invariant_booleans: Exclude propositions with variables declared in for statements

lib/src/rules/prefer_single_quotes.dart, lib/src/rules/unawaited_futures.dart, lib/src/rules/unnecessary_getters_setters.dart, lib/src/utils.dart, test/all.dart, test/formatter_test.dart, test/validate_format_test.dart
Fail build if `dartfmt` does not report clean on all but test data files.
Sample output:
```
package:test                         expect
test/validate_format_test.dart 11:5  main.<fn>
===== asynchronous gap ===========================
dart:async                           _Completer.completeError
test/validate_format_test.dart       main.<fn>
===== asynchronous gap ===========================
dart:async                           _asyncThenWrapperHelper
test/validate_format_test.dart 6:47  main.<fn>
Expected: empty
Actual: ['lib/src/utils.dart']
Some files need formatting. 
Run `dartfmt` and (re)commit.
```
Follow-up from: https://github.com/dart-lang/linter/pull/897#discussion_r168846347
@bwilkerson
=> Add source formatting validation to test/all.

pubspec.yaml
Track `analyzer` SDK constrain lower bound.
Follow-up from: https://github.com/dart-lang/linter/pull/911#issuecomment-369888397.
@bwilkerson @a14n
=> Bump SDK constraint to >=2.0.0-dev

lib/src/rules/prefer_const_literals_to_create_immutables.dart, test/rules/prefer_const_literals_to_create_immutables.dart
The rule prefer_const_literals_to_create_immutables is throwing an exception when presented with invalid code involving an instance creation expression for which the class could not be resolved. This fixes that.
=> Handle undefined classes in rule (sdk issue 32494)

.travis.yml
Quality of life updates for travis here:
* Use a pub cache to make "pub get" a bit faster.
* Only run travis on [master], to avoid 2 builds per PR
=> Tender-loving-care: Travis Edition

test/utils_test.dart
Adds test case supplied by @davidmorgan.
See:  #940.
@bwilkerson
=> Follow-up test for underscores in library prefixes.

lib/src/rules/avoid_types_as_parameter_names.dart, test/rules/avoid_types_as_parameter_names.dart
Generic function types were not handled correctly
=> fix issue with avoid_types_as_parameter_names

lib/src/rules/avoid_double_and_int_checks.dart
I've tweaked the example to add a GOOD case with `x is num` as an alternative. This could be a helpful suggestion in some cases.
=> Improve avoid_double_and_int_checks doc example

test/rule_test.dart
This sorts the list of actual errors, making it easier to compare the actual and expected lists when they don't agree.
=> Improve the failure message when tests fail

example/all.yaml, lib/src/rules.dart, lib/src/rules/avoid_field_initializers_in_const_classes.dart, test/rules/avoid_field_initializers_in_const_classes.dart
Lint created from https://github.com/dart-lang/sdk/issues/32789#issuecomment-379657135:
>Also, you should never have a final field with an initializer expression in a const class. Instead of `final x = const expr;`, you should write `get x => const expr;` and not allocate a useless field.
=> add avoid_field_initializers_in_const_classes

test/formatter_test.dart, test/mocks.dart
This reduces linters dependencies on analyzer and makes it possible for this part of analyzer's API to move forward.
=> Remove MockLineInfo

test/mocks.dart
There is no functional change, since the analyzer re-exports the Token
class from the front end.  This keeps the module organization cleaner,
by avoiding a dependency directly from linter to front_end.
=> Change test/mocks.dart to import Token from the analyzer.

lib/src/rules/prefer_final_locals.dart
```
var options = parser.parse(args);
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
=>
```
var options = parser.parse(args);
^^^^^^^
```
@bwilkerson @a14n
=> Improve reporting of `prefer_final_locals`

lib/src/rules/void_checks.dart
Without this fix, benchmarking reporting an exception:
```
Exception while using a TimedAstVisitor to visit a InstanceCreationExpressionImpl in ArgumentListImpl in MethodInvocationImpl in CascadeExpressionImpl in ExpressionStatementImpl in BlockImpl in BlockFunctionBodyImpl in FunctionExpressionImpl in FunctionDeclarationImpl in CompilationUnitImpl
```
which we traced back to accessing `parameters` on an unresolved node.
@a14n
=> Fix no such method call in `void_checks`.

lib/src/rules/prefer_final_fields.dart
This makes this lint use about `750 ms` vs. `4500 ms` it used to use during analyzing Flutter repo, i.e. 6 times faster.
But using AST visitor is not really cheap itself, it just better than what was used before. For comparison, if we don't run this visitor at all, the lint uses just `51 ms`. The way to avoid running the whole new visitor is to repeat what we did with lints - run a single AST visitor and let all lints to participate in pre-preprocessing CompilationUnit before running lints generation. More complexity, yes, but faster.
=> Rewrite collecting mutated fields in 'prefer_final_fields' to use AST visitor.

CHANGELOG.md, lib/src/rules/unrelated_type_equality_checks.dart, test/rules/unrelated_type_equality_checks.dart, test/util/fake_fixnum.dart
This suggestion for the unrelated_type_equality_checks lint follows analysis of a large body of Dart code; 80% of the failures for this lint were false positives related to `Int64` or `Int32`, the most common form by far being a check for whether an `Int64` value `== 0`.
The remaining 20% of failures were almost all useful, so with this tweak the lint has a very low false positive rate.
=> Add special cases for fixnum to unrelated_type_equality_checks.

CHANGELOG.md, pubspec.yaml
The only differences between master and this branched version was updates to the changelog and the pubspec.yaml.
It seems to me that the fork of 0.1.51 into a separate branch was unintentional, just because the commit with title 0.1.51 was missing the changelog and pubspec changes.  Feel free to revert this merge's effect on the tree if it isn't desired.
* `unrelated_type_equality_checks` now allows comparison between `Int64` or `Int32` and `int`
* `unnecessary_parenthesis` improved to handle cascades _in_ cascades
=> Merge version 0.1.51 back into master

lib/src/rules/void_checks.dart, test/rules/void_checks.dart
This was breaking at:
```dart
void main() {
void foo() {}
foo(0);
}
```
=> Fix void_checks when argument is not resolved to a parameter.

lib/src/rules/unnecessary_statements.dart, test/rules/unnecessary_statements.dart
=> Tweak unnecessary_statements lint to ignore getters; they may have side effects.

bin/linter.dart, test/engine_test.dart, test/integration_test.dart, test/rule_test.dart
We're in a funny state where some tests enable `previewDart2` while others don't.  This flips the bit everywhere.  (Soon enough this will be on by default and we can remove all of these explicit settings.)
Note that this introduces a break in `prefer_const_constructors`, which I think is right; see also: #1035.
=> Enable `previewDart2` everywhere.

lib/src/rules/prefer_is_empty.dart, test/rules/prefer_is_empty.dart
We found false positives where it's perfectly reasonable to compare length to a constant; the constant may change, and it doesn't make sense to force the code to change at the same time.
=> Weaken prefer_is_empty lint; don't evaluate constants beyond int literals.

lib/src/formatter.dart, lib/src/rules/always_specify_types.dart, tool/doc.dart
This also formats and sorts a couple of unrelated files. The only substantive change is in `lib/src/rules/always_specify_types.dart`.
=> Prevent an NPE when dealing with incomplete/invalid code

CHANGELOG.md, example/all.yaml, lib/src/rules.dart, lib/src/rules/prefer_void_to_null.dart, test/rules/prefer_void_to_null.dart
To help encourage people to use void, and discourage use of the academic
& suprising Null type now that void is here to better replace it and
serve its functions.
=> New lint: prefer_void_to_null

README.md, example/effective-dart.yaml
As is described in #288, I have tried to set a list of options describing Effective Dart analysis options. I have also included (in comments) unuses options so it will be simplier to see what can be added / what is missing.
All rules are sorted in sections and subsections according to Effective Dart, so it will be easier to sync the rules in time.
=> Add Effective Dart analysis options list

lib/src/rules/void_checks.dart, test/rules/void_checks.dart
See #1107. This is likely too strict and should be relaxed.
=> Relax void checks: allow T Function() to be assigned to void Function().

lib/src/rules/unawaited_futures.dart, test/rules/unawaited_futures.dart
During a refactor of some of our code we changed some functions which returned a void to now return a `Future<void>`. The code which called this method was used in a cascade like this:
```dart
object
..write('foo') // originally synchronous
..save();
```
After the migration, the above example did not trigger the unwaited_futures lint rule and showed up as a bug in our code because we were expecting `write` to finish before `save`. With the change `write` became a future which needed to finish before `save`.
This lint rule visits cascades to verify that there are no unwaited futures which could result in unexpected bugs. The rule still only triggers if you are inside of an async function to match the existing functionality.
=> update unwaited_futures to check cascades

example/all.yaml, lib/src/rules.dart, lib/src/rules/avoid_void_async.dart, test/mock_sdk.dart, test/rules/avoid_void_async.dart
Fix #1122.
As per discussion there, this is a *new* rule, not part of void_checks,
because it is much more likely to have low false positives.
In my experince, void_checks is very strict. It serves a useful purpose
in pushing people away from the more complex Null type by making void
useful in a way Null used to be used. However, void_checks is not
required for soundness, and it seems uncommon that the theory here
misses something practical.
For that reason, make a new rule. Users interested in making void behave
as if it were Null in certain ways can enable that, while users who just
want to make sure no async functions are declared wrong can enable this.
@eernstg
=> New rule: avoid_void_async. `void f() async`, suggest `Future<void>`.

lib/src/rules/unawaited_futures.dart
Not sure quite how you want to word this, but it'd be nice to have a reference to package:pedantic in there somewhere.
Ideally we want it to be in the lint message itself, as a call to action.
That said it's not clear if we want to push for external use of `package:pedantic` yet, so if you prefer we could tweak the error message when we post process analyzer output, and not mention it externally for now.
Please let me know. Thanks!
=> Improve unawaited_futures docs; point to package:pedantic.

pubspec.yaml, test/mock_sdk.dart
The analyzer only supports strong mode now, and analyzer version
0.33.* will remove this constructor parameter.  As of analyzer version
0.32.5, the parameter is optional, so we can stop passing it now.
=> Stop passing strong parameter to SummaryBuilder constructor.

lib/src/ast.dart
This complements https://dart-review.googlesource.com/c/sdk/+/73283 to fix the linter part of the https://github.com/dart-lang/sdk/issues/33612
=> Include CONST_WITH_TYPE_PARAMETERS into HasConstErrorListener.

analysis_options.yaml
Disable a lint that was accidentally enabled. We can't use the new mixin syntax yet because it isn't fully supported, so there's no way to "fix" the linted code.
=> Disable prefer_mixin

test/mocks.dart
These methods are needed when working with any version of the analyzer
including https://github.com/dart-lang/sdk/commit/abb392fc0d816b548e8ae69126f4e68e85e0ca3e.
They should be safe to use against earlier versions of the analyzer as
well, so there's no need to update the linter pubspec.
=> Add missing pubspec mock methods.

lib/src/rules/avoid_renaming_method_parameters.dart
https://github.com/dart-lang/sdk/issues/34570
We could use `ClassOrMixinDeclaration`, but it is not available in `linter` yet.
=> Issue 34570. MethodDeclaration can be also in MixinDeclaration.

pubspec.yaml
Make pub happy:
```
Missing requirements:
* ^ version constraints aren't allowed for SDK constraints since older versions of pub don't support them.
```
=> expand SDK constraint

lib/src/rules/sort_constructors_first.dart, test/rules/sort_constructors_first.dart
According to [Flutter style guide: Constructors come first in a class](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#constructors-come-first-in-a-class).
>The default (unnamed) constructor should come first, then the named constructors. They should come before anything else (including, e.g., constants or static methods).
=> sort_constructors_first applies for all members

lib/src/rules/avoid_field_initializers_in_const_classes.dart, lib/src/util/unrelated_types_visitor.dart, test/rules/avoid_field_initializers_in_const_classes.dart
I can't fix the second issue until we publish a new version of analyzer, but I left a TODO so we wouldn't forget. It needs to be fixed before 2.1, but not as high a priority as getting this fix in. I'd like to get this published and pulled into the SDK asap.
=> Fix mixin related bug in avoid_field_initializers_in_const_classes

lib/src/rules/null_closures.dart
This improves the speed of NullClosures, especially instance method checks, largely by comparing method names first. Also by using a Map so that all instance methods do not need to be walked.
=> Refactor NullClosures to be more performant, checking method names first

lib/src/rules/await_only_futures.dart
Because the expression following the keyword can be arbitrarily large, it would be better to highlight just the keyword.
=> Highlight a smaller range for violations of await_only_futures

test/integration_test.dart
When debugging an integration test, it is much more helpful to see that the _output_ is unexpected (without seeing the exitCode) than it is to see that the _exitCode_ is unexpected (without getting to see what the output is).
=> Move integration exitCode checks to be after output checks.

test/rules/prefer_const_constructors.dart
... to ensure lint does not complain about non-const type-variabled constructor. Related to #628
=> Add tests for prefer_const_constructors

CHANGELOG.md, example/all.yaml, lib/src/rules.dart, lib/src/rules/prefer_int_literals.dart, test/rules/prefer_int_literals.dart
First cut at a prefer int literals lint. There are more situations in which this lint should report a double literal that should be converted, but AFAIK there are no false positives.
=> Prefer int literals over double literals

lib/src/rules/prefer_int_literals.dart, test/rules/prefer_int_literals.dart
This improves the prefer_int_literal lint to detect double literals that can be converted in argument lists and binary expressions.
=> Improve prefer_int_literal lint

lib/src/rules/prefer_foreach.dart, lib/src/rules/public_member_api_docs.dart
Fixes: #1241.
/cc @scheglov @stereotype441
=> migrate `prefer_foreach` and `public_member_api_docs` to NodeLintRule (#1241)

example/all.yaml, lib/src/rules.dart, lib/src/rules/use_function_type_syntax_for_parameters.dart, test/rules/use_function_type_syntax_for_parameters.dart
Ensure effective dart rule: [CONSIDER using function type syntax for parameters.](https://www.dartlang.org/guides/language/effective-dart/design#consider-using-function-type-syntax-for-parameters)
Fixes #1204
=> add lint use_function_type_syntax_for_parameters

lib/src/rules/use_function_type_syntax_for_parameters.dart
fixes build:
https://travis-ci.org/dart-lang/linter/jobs/451058523
/cc @stereotype441
=> update rule to use `NodeLintRuleWithContext`

lib/src/rules/unnecessary_await_in_return.dart, test/rules/unnecessary_await_in_return.dart
Contrary to what I thought [an issue in flutter](https://github.com/dart-lang/linter/pull/1252#issuecomment-436586241) was not due to `Future<dynamic>` but it was because it is not safe to replace `return await f` by `return f` when the return statement is in a try block. It completly changes the behaviour.
=> fix false positive for unnecessary_await_in_return

CONTRIBUTING.md
Adds a github contributors badge to the contributors readme.
=> contrib badge

tool/doc.dart
Generates a lint count badge as part of lint document generation.
This will work like badges in https://shields.io/#/ and can be used in the `README`, etc.
=> generate lint count badge as part of doc gen

bin/linter.dart, lib/src/analyzer.dart, lib/src/cli.dart, lib/src/formatter.dart, lib/src/rules/avoid_slow_async_io.dart, test/mocks.dart, test/rules/await_only_futures.dart, test/validate_headers_test.dart, tool/doc.dart
* fixed override in `await_only_futures.dart`
* removed unneeded `dart:async` imports
=> async cleanup

tool/doc.dart
Emphasize non-stable lints in their generated docs
* adds doc styling to emphasize deprecated and experimental lints
* adds blurb about deprecated lints to lint index description
Red and pink may be a subtle distinction but I do want them to pop.
/cc @bwilkerson @srawlins @a14n
=> emphasize non-stable lints in docs

lib/src/util/dart_type_utilities.dart, test/rules/unrelated_type_equality_checks.dart
Fixes #1085 and https://github.com/dart-lang/sdk/issues/32522
The `unrelated_type_equality_checks` lint, to avoid false positives, treats types that _might_ be related as good enough, such as `fn<A, B>(A a, B b) => a == b`; no lint. This rule was not applied to generics, so the following types on either side of `==` were reported:
* `List<dynamic>` and `List<String>`
* `Future<dynamic>` and `Future<T>`
* `List<A>` and `List<B>` for unbound `A` and `B`.
=> Fix unrelated type checks of generic types

lib/src/rules/unnecessary_parenthesis.dart, test/rules/unnecessary_parenthesis.dart
=> Allow ! arg to be wrapped in parens, even if not required by precedence

lib/src/rules/cascade_invocations.dart, test/rules/cascade_invocations.dart
Fixes #1323 
The lint rule uses `getCanonicalElementFromIdentifier` to see if two statements act on the same element, in order to report that they can be combined with a cascade. But unless the expressions are simple, up to a point, the rule cannot know that one statement acts on `b1.a` and the second acts on `b2.a`, even though both act on `A get a`.
=> Fix cascade_invocations false positive when examining complicated expressions

lib/src/rules/avoid_shadowing_type_parameters.dart, test/rules/avoid_shadowing_type_parameters.dart
Partial fix for #1027 but I suspect not the whole story...
=> Report shadowed type parameters in generic typedefs

pubspec.yaml, tool/crawl.dart, tool/scorecard.dart
WIP but at a reasonable checkpoint.  Ultimately this may generate a publishable report (or inform badging) but for now it dumps a table that can be used for informal scoring.
fyi @devoncarew 
---
| name | fix | flutter user | flutter repo | pedantic | stagehand | status | bug refs |
| :--- | :---: | :---:| :---: | :---: | :---: | :---: | :--- |
| `always_declare_return_types` | | | ✅ | | | |  |
| `always_put_control_body_on_new_line` | | | ✅ | | | |  |
| `always_put_required_named_parameters_first` | | | | | | |  |
| `always_require_non_null_named_parameters` | 💡 | | ✅ | | | |  |
| `always_specify_types` | | | ✅ | | | |  |
| `annotate_overrides` | 💡 | | ✅ | | | |  |
| `avoid_annotating_with_dynamic` | 💡 | | | | | | #1162 |
| …
=> Scorecard (work in progress).

tool/doc.dart
Follow-up from https://github.com/dart-lang/linter/pull/1352#issuecomment-452087141.
Before:
After:
Thanks for the feedback!
/cc @kwalrath @chalin
=> Dart SDK info format tweaks.

lib/src/ast.dart, lib/src/rules/hash_and_equals.dart, test/rules/hash_and_equals.dart
=> fix `hash_and_equals` to respect hashCode fields

tool/crawl.dart
Adds handling for `-dev` suffixed linter versions.
=> improve minor # parsing

tool/doc.dart
Fixes: #1379.
/cc @bwilkerson @jwren
=> remove deprecated lints from all options sample

test/integration_test.dart
Noticed when scanning our test coverage:
Missed enabling this in: https://github.com/dart-lang/linter/pull/1249.
/cc @bwilkerson @srawlins @a14n
=> re-enable sort_pub_dependencies test

lib/src/rules/prefer_const_declarations.dart, test/rules/prefer_const_declarations.dart
Work-in-progress fixes for #1427.
Note that these tests are not expected to pass on travis until a new `analyzer` package is published w/ set-literals support on by default (https://github.com/dart-lang/sdk/issues/35905).
=> fixes for const typed literals

lib/src/rules/prefer_collection_literals.dart, test/mock_sdk.dart, test/rules/prefer_collection_literals.dart
Fixes: https://github.com/dart-lang/linter/issues/1425
=> Collection literals fixes

lib/src/rules/prefer_collection_literals.dart, test/rules/prefer_collection_literals.dart
Fixes a false-positive identified while trying to migrate flutter.
=> fix collection literals false positive for expression bodies

lib/src/rules/unnecessary_parenthesis.dart, test/rules/unnecessary_parenthesis.dart
The unnecessary_parenthesis rule has  some exceptions for unary operators next to whitespace-y keywords, but was still complaining about this:
```dart
!(const [7]).contains(42);
```
This fixes that.
=> Add another corner relaxation for unnecessary_parenthesis

lib/src/rules/prefer_is_not_empty.dart, test/rules/prefer_is_not_empty.dart
While there is a lint rule for unnecessary parentheses, (a) we can't expect everyone has it enabled, and (b) it allows some exceptions. But that shouldn't allow these `!isEmpty` cases to hide!
=> Add support for reporting on parenthesized !isEmpty / !isNotEmpty

lib/src/rules/prefer_collection_literals.dart
The class ListLiteral2 is being removed in favor of changes that will allow existing code to continue to use ListLiteral after converting to use a new getter to get the contents. But we can't remove it until linter no longer references it.
After this PR is merged we'll need to pull in a new version (or commit) of linter.
=> Remove references to ListLiteral2 so that it can be removed from analyzer

pubspec.yaml, test/configs/control-flow-collections/analysis_options.yaml, test/rule_test.dart
Plumbing for running test configurations.
Currently failing badly but that's unsurprising and so runs are disabled until control-flow-collections are further along.
See: https://github.com/dart-lang/linter/issues/1438
=> support for running tests w/ experiments enabled

lib/src/version.dart, test/all.dart, test/version_test.dart
Stores version number in a string for pushing to analyzer for caching w/ summary cache signatures.
See: #1440 
/cc @scheglov
=> export a version string

lib/src/rules/avoid_shadowing_type_parameters.dart, test/rules/avoid_shadowing_type_parameters.dart
Fixes #1447 with a null-aware property access.
=> Fix crash in avoid_shadowing_type_parameters

lib/src/util/unrelated_types_visitor.dart, test/rules/iterable_contains_unrelated_type.dart
I'm looking into #1307 and #414, but it took me forever to understand how UnrelatedTypesProcessors works.
I thought I'd commit my doc comments and a bit of tidying first before mailing a large refactoring.
=> Document and tidy UnrelatedTypesProcessors

lib/src/rules/always_specify_types.dart, lib/src/rules/prefer_const_literals_to_create_immutables.dart, lib/src/rules/prefer_void_to_null.dart, lib/src/rules/unnecessary_const.dart, pubspec.yaml, test/rules/always_specify_types.dart
Migrates to new `SetOrMapLiteral` API.
A few notes on the unification:
* `always_specify_types` was missing the opportunity to flag set literals; this fixes that 👍 
* I added TODOs in places where existing logic was preserved but might better be widened to include Set literals too 🤔 
* I'm not sure what to do about the test for `node is MapLiteralEntry`:  will that interface go away too?
(A similar migration for `ForStatement2 ` to follow.)
/cc @stereotype441 @bwilkerson
=> migrate to new SetOrMapLiteral API

.travis.yml, tool/baseline/pana.json, tool/pana_baseline.dart, tool/travis.sh
The output is a little spammy but serviceable as a first cut.
Essentially, this:
* adds a new `pana_baseline` bot, that
* checks current pana scores against a
* baseline stored in `'tool/baseline/pana.json'`
Sample run [here](https://travis-ci.org/dart-lang/linter/jobs/502145908).
Fixes #1463.
/cc @devoncarew @bwilkerson 
/fyi @isoos @jonasfj
=> add a pana baseline bot

tool/scorecard.dart
Adds doc links to rule names in the scorecard.
| name | linter | dart sdk | fix | pedantic | flutter user | flutter repo | status | bug refs |
| :--- | :--- | :--- | :---: | :---: | :---: | :---: | :---: | :---  |
|  [always_declare_return_types](https://dart-lang.github.io/linter/lints/always_declare_return_types.html) | 0.1.4 | 2.0.0 | | | | ✅ | |  |
|  [always_put_control_body_on_new_line](https://dart-lang.github.io/linter/lints/always_put_control_body_on_new_line.html) | 0.1.31 | 2.0.0 | | | | ✅ | |  |
|  [always_put_required_named_parameters_first](https://dart-lang.github.io/linter/lints/always_put_required_named_parameters_first.html) | 0.1.33 | 2.0.0 | | | | | |  |
|  [always_require_non_null_named_parameters](https://dart-lang.github.io/linter/lints/always_require_non_null_named_ …
=> add rule doc links to scores

lib/src/rules/prefer_asserts_in_initializer_lists.dart
As this landed for real in Dart 2.0, I think we can safely remove the caveat?
Related to: https://github.com/dart-lang/linter/issues/1372
=> remove experimental warning from prefer_asserts_in_initializer_lists

tool/scorecard.dart
Improve fix parsing
* updates parsing to be more robust
* emits a warning for name mismatches
* adds a fix count
Note: this flags the two currently mismatching lints in server 👍 
```
WARNING: unrecognized lint in fixes: unnecessary_brace_in_string_interp
WARNING: unrecognized lint in fixes: unnecessary_override
```
=> improve parsing of lints with fixes

lib/src/rules/unnecessary_parenthesis.dart
This is safe since linter depends on analyzer `^0.35.3`, in which `precedence2` is introduced.
=> Migrate off deprecated precedence property

lib/src/rules/unnecessary_parenthesis.dart, test/rules/unnecessary_parenthesis.dart
Fixes #1473. This is a rather broad fix 🙁 For example the unnecessary_parenthesis rule would no longer complain about:
```dart
class C {
C(int a) : a = (1 + 2);
}
```
in which the parens are definitely unnecessary and kind of silly. But taking a look at our two real world examples:
```dart
class UnnecessaryParenthesis {
final value;
// https://github.com/dart-lang/linter/issues/1395
UnnecessaryParenthesis() : value = (ClassWithFunction()..f = () => 42); // OK
// https://github.com/dart-lang/linter/issues/1473
UnnecessaryParenthesis.named(Function value)
: this.value = (value ?? (_) => 42); // OK
}
```
The offending  arrow which leaps downwards (I think) in precedence is not easy to find... The cascade there is a hint that users could totally put that thing deep.
=> Fix #1473 by looking at constructor field initializers

lib/src/rules/file_names.dart, lib/src/utils.dart, test/_data/file_names/non-strict.css.dart, test/integration_test.dart, test/utils_test.dart
Allow (`.css.dart`, `.g.dart`, etc.).
Fixes: #1486
/cc @kevmoo @bwilkerson @matanlurey @davidmorgan
=> update `file_names` to skip extension-prefixed .dart files

example/all.yaml, lib/src/rules.dart, lib/src/rules/prefer_inlined_adds.dart, lib/src/rules/prefer_spread_collections.dart, test/mock_sdk.dart, test/rules/prefer_inlined_adds.dart, test/rules/prefer_spread_collections.dart
Introduces `prefer_inlined_adds` and updates `prefer_spread_collections` to no longer flag `addAll` calls that can be inlined.
See also: https://dart-review.googlesource.com/c/sdk/+/99040
=> add prefer_inlined_adds; update prefer_spread_collections

example/all.yaml, lib/src/rules.dart, lib/src/rules/diagnostic_describe_all_properties.dart, lib/src/rules/sort_child_properties_last.dart, lib/src/util/flutter_utils.dart, test/rules/sort_child_properties_last.dart
Adds new lint `sort_child_properties_last`.
Currently limited to `child` and `children` properties but after some analysis we could consider broadening.
Fixes #1542
/cc @jacob314 @a14n @bwilkerson
=> add sort_child_properties_last

lib/src/rules/prefer_null_aware_operators.dart, test/rules/prefer_null_aware_operators.dart
Remove restriction on `prefer_null_aware_operators` (was only applied for local variables).
=> widen application of prefer_null_aware_operators

lib/src/rules/curly_braces_in_flow_control_structures.dart, lib/src/rules/literal_only_boolean_expressions.dart, lib/src/rules/omit_local_variable_types.dart, lib/src/rules/prefer_final_in_for_each.dart, lib/src/rules/prefer_foreach.dart, lib/src/rules/unnecessary_statements.dart, lib/src/rules/use_string_buffers.dart, pubspec.yaml
Since analyzer version 0.36.0, we no longer need to override
visitForStatement2.  visitForStatement is equivalent.
=> Stop using deprecated analyzer API left over from "UI as code" migration.

lib/src/rules/omit_local_variable_types.dart, test/rules/omit_local_variable_types.dart
=> allow dynamic locals

lib/src/rules/prefer_initializing_formals.dart, test/rules/prefer_initializing_formals.dart
If the argument is a named argument only lint if the name is the same as to avoid changes to the API to either fix the field or the name arguments for more details see the issue provided below.
Fixes # http://go/gh/dart-lang/linter/issues/1587
=> Avoid prefer_initializing_formals when parameter is named and the name is different from the field

CONTRIBUTING.md
While following the documentation I run into this error:
git@github.com:dart-lang/linter/linter.git
vs
git@github.com:dart-lang/linter.git
@pq
=> Correct the git linter Uri in the contributing doc

lib/src/rules/prefer_final_fields.dart, test/rules/prefer_final_fields.dart
The current lint only covers fields which have a default value set to them which excludes cases like:
```dart
class AssignedInAllConstructors {
var _label; // Currently OK
AssignedInAllConstructors(this._label);
AssignedInAllConstructors.withDefault() : _label = 'Hello';
}
```
These change tries to aim for linting fields assigned only once (either by default or in all the constructors)"
Fixes #1606
@pq @bwilkerson
=>  Adjust the 'prefer_final_fields' lint to cover more cases

lib/src/rules/prefer_collection_literals.dart, test/rules/prefer_collection_literals.dart
The current implementation of the lint handles LinkedHashSet as follows:
```dart
var ss5 = LinkedHashSet<int>(); // LINT
Set<int> ss5 = LinkedHashSet<int>(); // LINT
LinkedHashSet<int> ss6 = LinkedHashSet<int>(); // OK
```
The last one is precisely to avoid the type error but following the same this change includes function calls to follow the same:
```dart
printSet(Set()); // LINT
printSet(LinkedHashSet<int>()); // LINT
printHashSet(LinkedHashSet<int>()); // OK
void printSet(Set<int> ids) => ...
void printHashSet(LinkedHashSet<int> ids) => ...
```
@pq @bwilkerson
=> Make LinkedHashSet method call behave the same as field assignment

lib/src/rules/prefer_collection_literals.dart, test/rules/prefer_collection_literals.dart
Currently `LinkedHashSet` excludes the following cases for the lint:
```dart
void main() {
LinkedHashSet<int> linkedHashSet =  LinkedHashSet.from([1, 2, 3]); // OK
LinkedHashSet<String> sss1 = <int, LinkedHashSet<String>>{}.putIfAbsent(3, () => LinkedHashSet<String>()); // OK
printSet(LinkedHashSet<int>()); // LINT
printHashSet(LinkedHashSet<int>()); // OK
}
void printSet(Set<int> ids) => print('$ids!');
void printHashSet(LinkedHashSet<int> ids) => printSet(ids);
```
For consistency we want the same cases to be expected for `LinkedHashMap`:
```dart
void main() {
LinkedHashMap linkedHashMap = LinkedHashMap(); // OK
LinkedHashMap<String, String> lhm = <int, LinkedHashMap<String,String>>{}.putIfAbsent(3, () => LinkedHashMap<String, String>()); // OK
printMap(LinkedHashMap<int, int>()); // …
```
=> Apply the same restrictions for LinkedHashMap as the ones for LinkedHashSet

example/all.yaml, lib/src/rules.dart, lib/src/rules/avoid_print.dart, test/rules/avoid_print.dart
(Nearly) the simplest possible lint for `print`s.
Refinements welcome.
(In particular, do we want to allow calls in `Logger`s?)
Fixes #88
=> avoid_print

tool/rule.dart
This is gets added to all rule stubs and is usually unnecessary.
=> remove (usually) unneeded import

lib/src/rules/avoid_implementing_value_types.dart
This will be needed in order to rework the element model, but I won't merge it until we know we need it.
=> Add a cast that will be necessary as of the next published version of analyzer

lib/src/rules/unsafe_html.dart, test/mock_sdk.dart
The unsafe_html error message currently does not state what about a given statement is "unsafe." This makes it clearer, per HTML field, and allows tools to filter violations per error code.
Also fix missing classes etc in the mock_sdk.
=> Split the unsafe_html errorCodes

test/rule_test.dart
We should fail, not print, on an unregistered rule in the rule_test. This in fact uncovered a bug:
The package_names lint rule test was not being executed!, because the 'pub' group was misconfigured.
Additionally, since  `unnecessary_getters` is not registered in rules.dart, it cannot be tested, so I hard-coded a skip. If this is not super discovereable, we could rename the  file to something like `SKIP_unnecessary_getters.dart`, and check for file names beginning with `SKIP_`, or set the first line of the  file to, e.g. `SKIP SKIP SKIP`, and check for files starting with that. I'm open.
=> In rule_test, fail on unregistered rule

lib/src/rules/iterable_contains_unrelated_type.dart, lib/src/rules/list_remove_unrelated_type.dart, lib/src/rules/unrelated_type_equality_checks.dart, lib/src/util/dart_type_utilities.dart, lib/src/util/unrelated_types_visitor.dart
All type operations in general should be done using `TypeSystem`.
We want to remove duplicate, older implementations in `DartTypeImp`.
=> Replace DartType.isMoreSpecificThan() with TypeSystem.isSubtypeOf().

lib/src/rules/prefer_bool_in_asserts.dart, lib/src/rules/void_checks.dart
Continue replacing `DartType` methods with corresponding `TypeSystem` methods.
=> Replace DartType.isAssignableTo() with TypeSystem.isAssignableTo().

lib/src/rules/prefer_is_empty.dart, lib/src/rules/unnecessary_await_in_return.dart, test/mock_sdk.dart
All type operations in general should be done using `TypeSystem`.
We want to remove duplicate, older implementations in `DartTypeImpl`.
=> Replace DartType.isSubtypeOf() with TypeSystem.isSubtypeOf().

lib/src/rules/unnecessary_parenthesis.dart, test/rules/unnecessary_parenthesis.dart
Currently the unnecessary_parenthesis rule reports the following statement:
```dart
({1, 2, 3}).forEach(print);
```
But Dart cannot parse the statement if the parens are removed; it thinks an anonymous block is being declared, and fails to parse.
This PR stops reporting that case.
=> Do not report parens around set-or-map literal as method target

lib/src/rules/unnecessary_parenthesis.dart, tool/travis.sh
Fixes a cast issue and updates travis to make sure it breaks for things like this in the future.
(Not clear why `dartanalyzer` wasn't failing on this and I'm researching that separately.
=> cast fix; travis build fix

lib/src/rules/avoid_slow_async_io.dart, test/mock_sdk.dart, test/rules/avoid_slow_async_io.dart
Fixes #1671
/cc @bwilkerson @danrubel
=> flag async directory methods

test/rules/experiments/always_declare_return_types/always_declare_return_types.dart, test/rules/experiments/always_declare_return_types/analysis_options.yaml, test/rules/experiments/experiments.dart
First of a set of tests that validate behavior w/ extension-methods enabled.
=> extension-method test for always_declare_return_types

lib/src/rules/prefer_constructors_over_static_methods.dart, test/rules/experiments/experiments.dart, test/rules/experiments/prefer_constructors_over_static_methods/analysis_options.yaml, test/rules/experiments/prefer_constructors_over_static_methods/prefer_constructors_over_static_methods.dart
=> ensure `prefer_constructors_over_static_methods` works with extensions

lib/src/util/dart_type_utilities.dart
Protects utilities from calls against methods defined on extensions.
See: #1683 
=> make type utils extension-safe

lib/src/rules/prefer_for_elements_to_map_fromIterable.dart, lib/src/rules/prefer_is_empty.dart, pubspec.yaml
https://github.com/dart-lang/linter/pull/1725 is in a strange state where it is blocked, because Travis runs it with analyzer `0.38.3`, but the PR decided to not upgrade to `0.38.3` because it itself does not have to. So, here is a separate PR to upgrade and fix deprecations.
=> Upgrade to analyzer 0.38.3 and fix deprecation warnings.

lib/src/rules/annotate_overrides.dart, lib/src/rules/avoid_equals_and_hash_code_on_mutable_classes.dart, lib/src/rules/avoid_implementing_value_types.dart, lib/src/rules/avoid_positional_boolean_parameters.dart, lib/src/rules/avoid_returning_this.dart, lib/src/rules/diagnostic_describe_all_properties.dart, lib/src/rules/overridden_fields.dart, lib/src/rules/prefer_asserts_in_initializer_lists.dart, lib/src/rules/prefer_const_constructors.dart, lib/src/rules/prefer_const_constructors_in_immutables.dart, lib/src/rules/prefer_constructors_over_static_methods.dart, lib/src/rules/prefer_void_to_null.dart, lib/src/rules/public_member_api_docs.dart, lib/src/rules/unawaited_futures.dart, lib/src/util/unrelated_types_visitor.dart, pubspec.yaml
We are deprecating this getter, and want the clients to use more appropriate ways to access types. In case of the linter there is usually no reason to get the type from an element, instead already set types can be used.
=> Stop using Element.type

lib/src/rules/unnecessary_statements.dart
It does not access the corresponding deprecated 'bestElement' property from Analyzer, but just does not mean anything now, and I stumbled upon it while searching in google3.
=> Stop using 'bestElement' name.

lib/src/rules/await_only_futures.dart
On behalf of a googler without a github account :)
The more detailed message is useful for us in cleaning up google3 because we need to fix awaiting a method that returns `void` differently from everything else. That can actually have an effect, and we then need to check if it was intended that the method return `Future<void>`.
What do you think, please?
=> Make await_only_futures mention the incorrectly-awaited type.

lib/src/rules/avoid_positional_boolean_parameters.dart
We want to stop setting `staticType` for Identifier(s) that are used not as expressions, e.g. names of types, names of declarations (classes, functions, parameters).
=> Get the type of a FormalParameter from the declared element.

lib/src/rules/unnecessary_lambdas.dart, test/rules/unnecessary_lambdas.dart
We used to represent all invocations like `foo()` as `MethodInvocation`(s). But this is not ideal, because if `foo` is not a `FunctionElement` or a `MethodElement`, but a `PropertyAccessorElement`, then it is not `foo` that is invoked, but the result returned from `foo` is invoked instead. This is what `FunctionExpressionInvocation` should represent.
This PR also changes `final notRelevantQuestionPeriod = (p) => array[x?.m1].m2(p);` from LINT to OK. The reason is that `IndexExpression` is basically a method invocation, so can return different values at different times.
=> Fix unnecessary_lambdas for coming MethodInvocation vs. FunctionExpressionInvocation changes.

lib/src/rules/avoid_print.dart, test/rules/avoid_print.dart
The lint rule `avoid_print` is not catching the scenario when `print` function passed as an argument. This PR includes code that added additional check to validate function arguments for `print`.
Fixes #1696
=> Fixed - avoid_print rule fails to catch tear-off usage

pubspec.yaml, test/configs/extension_methods/analysis_options.yaml
As of `0.38.5` enabled by default in analyzer so no need for an extra run of tests.
/cc  @bwilkerson @stereotype441
=> remove extension-methods test config

test/rule_test.dart, test/rules/experiments/nnbd/analysis_options.yaml, test/rules/experiments/nnbd/rules/avoid_init_to_null.dart, test/rules/experiments/nnbd/rules/null_closures.dart, test/rules/experiments/nnbd/rules/unnecessary_null_in_if_null_operators.dart
Adds a test harness that runs rule tests with the `non-nullable` experiment enabled.
To start, I ported a few tests from the `pedantic` ruleset.  These tests are currently identical to those being tested w/o nnbd.
My intention is to evolve them to include nnb-migrated code so we can get early feedback on possible issues.
/cc @scheglov @srawlins
=> nnbd test harness

lib/src/rules/avoid_init_to_null.dart, test/rules/experiments/nnbd/rules/avoid_init_to_null.dart
First cut.
Lint description: http://dart-lang.github.io/linter/lints/avoid_init_to_null.html
(Used in `pedantic` and `flutter`.)
Test ideas and suggestions welcome!
See: #1770 
/cc @stereotype441 @scheglov 
/fyi @munificent
=> basic nnbd awareness for `avoid_init_to_null`

example/all.yaml, lib/src/rules.dart, lib/src/rules/prefer_is_not_operator.dart, test/rules/prefer_is_not_operator.dart
Fixed #1522 
When checking if the object has not specified type, it is preferable to use 'is!' operator.
**BAD:**
```
if (!(foo is Foo)) {
...
}
```
**GOOD:**
```
if (foo is! Foo) {
...
}
```
=> New lint: prefer_is_not_operator

lib/src/rules/avoid_returning_null_for_void.dart
Relax `avoid_returning_null_for_void` to check only `null` literal (and not expression having Null type)
Fixes #1787
=> avoid_returning_null_for_void only checks null literal

lib/src/rules/always_specify_types.dart, lib/src/rules/avoid_returning_null_for_void.dart, lib/src/rules/void_checks.dart, lib/src/util/dart_type_utilities.dart, lib/src/util/flutter_utils.dart
I'd like to remove it, and ask clients to use `InterfaceType` and `FunctionType` directly.
=> Stop referencing ParameterizedType.

lib/src/rules/avoid_web_libraries_in_flutter.dart, test/integration_test.dart
Limit web library access to Flutter plugin packages.
See: https://github.com/dart-lang/sdk/issues/38691
/cc @devoncarew @bwilkerson 
/fyi @yjbanov @hterkelsen
=> dissallow web lib access from flutter web packages

test/engine_test.dart
This unblocks crash reporting where we previously had a plethora of ways to report errors which no longer are relevant, including the AnalysisLogger.
=> Remove unnecessary logging tests; these loggers aren't used by linter

tool/crawl.dart, tool/doc.dart, tool/scorecard.dart
This PR adds effective dart badge to lints, similarly to pedantic and flutter. (Discussed in https://github.com/dart-lang/linter/pull/1781)
I tested to build pages on local, and everything works as expected (except I don't have styles and images – mentioned bellow).
I do not know where to save the badge for the effective dart. In `tools/doc.dart:174` there is mentioned `<img alt="effective_dart" src="style-effective_dart.svg">`, which is just a copy from pedantic, but I do not know where it is stored.
I would like to use this [badge](https://github.com/tenhobi/effective_dart/#badge) (https://img.shields.io/badge/style-effective_dart-40c4ff.svg).
cc @pq
=> Add effective_dart to linter page

test/rules/type_annotate_public_apis.dart
Abstract methods are disallowed in extensions.
/cc @MichaelRFairhurst @bwilkerson
=> fix test parse error

lib/src/ast.dart, lib/src/rules/avoid_renaming_method_parameters.dart, lib/src/rules/prefer_relative_imports.dart, lib/src/rules/public_member_api_docs.dart
Fixes: #1786
Should also make `prefer_relative_imports` and `public_member_api_docs` google3-friendly.
Bonus: makes `avoid_renaming_method_parameters` way more performant.
Before:
After:
🏅 🏅 🏅 
/cc @bwilkerson @scheglov 
/fyi @a14n
=> use workspace package to locate `lib/`

lib/src/rules/prefer_relative_imports.dart, test/_data/prefer_relative_imports/_packages, test/_data/prefer_relative_imports/bin/bin.dart, test/_data/prefer_relative_imports/lib/main.dart, test/integration_test.dart
Speed up `prefer_relative_imports` and make it google3-friendly by querying the workspace package (and forgoing any pubspec parsing).
Before:
After:
Definitely **_faster_**...  Still need to convince myself that it's correct.  (A few TODOs to consider.)
See also: #1810.
=> 👟👟👟 `prefer_relative_imports`: stop parsing pubspecs (query ws package for self-references)

example/all.yaml, lib/src/rules.dart, lib/src/rules/unnecessary_final.dart, test/rules/unnecessary_final.dart
This lint is more or less the opposite of `prefer_final_locals` plus `prefer_final_in_foreach`, plus checking parameters. (There isn't a `prefer_final_parameters`).
What do you think, please? This seems much closer to common usage. I'm not sure we'll ever get around to enforcing it, but it's nice to have a lint that matches what people do, so that people aren't just citing the existence of those lints as an argument :)
=> Add new lint: unnecessary_final.

lib/src/rules/avoid_function_literals_in_foreach_calls.dart, test/rules/avoid_function_literals_in_foreach_calls.dart
Loosens the lint to allow chained calls such as:
```dart
people
.where((person) => person != null)
.map((person) => '$person!')
.forEach((person) => print(person)); // OK
Person()
.children
.firstWhere((person) => person != null)
.children
.forEach((person) => print(person)); // OK
Person().children.first.children.forEach((person) => print(person)); // OK
```
Fixes #365 
@pq @munificent
=> Loosen `avoid_function_literals_in_foreach_calls` to allow method chained calls

README.md
See: https://github.com/dart-lang/linter/issues/1833.
=> remove (stale) appveyor badge

lib/src/rules/always_require_non_null_named_parameters.dart
=> improve perf for `always_require_non_null_named_parameters`

lib/src/rules/avoid_private_typedef_functions.dart, test/rules/avoid_private_typedef_functions.dart
Nested `TypeName`s in the AST were being ignored due to a missing call to super. This results in false positives for `avoid_private_typedef_functions` in cases such as type parameters on generic types.
Fixes https://github.com/dart-lang/linter/issues/1856
=> Consider nested TypeNames when counting uses.

lib/src/ast.dart
Fixes: #1862 #1863 .
Looking closer at call sites, it's possible for `package` to be null so we need to guard against that.
/fyi @scheglov
=> check for null packages in "isInLibDir" check

lib/src/rules/always_require_non_null_named_parameters.dart, test/rules/always_require_non_null_named_parameters.dart
=> bail on first non-assert in `always_require_non_null_named_parameters`

lib/src/rules/null_closures.dart, test/rules/null_closures.dart
null_closures erroneously did not flag the `orElse` named parameter of [Iterable.singleWhere](https://api.dartlang.org/stable/2.7.0/dart-core/Iterable/singleWhere.html).
=> Fix null_closures bug with Iterable.singleWhere

lib/src/rules/slash_for_doc_comments.dart, test/rules/slash_for_doc_comments.dart
This lint was not checking the doc comments on mixins. It was updated for extensions, but mixins were missed.
It seems unlikely that it will create problems when rolling into Flutter, but I haven't verified that. If you think we should hold off until that's been checked I'm happy to wait.
=> Check doc comments for mixins in slash_for_doc_comments

lib/src/rules/always_put_required_named_parameters_first.dart
I believe that this rule needs to be updated to recognize the to-be-added `required` keyword as a way of marking parameters as being required.
=> Update always_put_required_parameters_first for nnbd

tool/doc.dart
Updates to docs generated to: http://dart-lang.github.io/linter/lints/.
Current:
With this proposed change:
/cc @bwilkerson @tenhobi
=> add ruleset pointers

lib/src/rules/prefer_single_quotes.dart
Fixes #1954 
Changed slightly from the text on the issue, which was
`Only use double quotes if the string contains single quotes.`
in this PR I use
`Only use double quotes for strings containing single quotes.`
but, happy to tweak it either way :)
Thanks.
=> Improve prefer_single_quotes message.

lib/src/rules/unnecessary_final.dart
Per feedback on #1953 
I gave up figuring out how to get to the `final` keyword in all cases for `FormalParameterList`. Suggestions welcome ;)
=> Make unnecessary_final lint report on the `final` keyword.

lib/src/rules/avoid_unused_constructor_parameters.dart, test/rules/avoid_unused_constructor_parameters.dart
The rule `avoid_unused_constructor_parameters` should not produce a lint for parameters that are deprecated because it's appropriate that they are not referenced.
=> Allow unused parameters when they are deprecated

example/all.yaml, lib/src/rules.dart, lib/src/rules/unnecessary_string_interpolations.dart, test/rules/unnecessary_string_interpolations.dart
This lint catches `'$stringExpresion'` ; it can be replaced by `stringExpression` directly (modulo null handling)
=> unnecessary_string_interpolations

tool/doc.dart
Example:
Fixes: https://github.com/dart-lang/linter/issues/1967
=> generate docs for incompatible rules

lib/src/rules/no_duplicate_case_values.dart
We don't need to access these private parts of analyzer.
=> [no_duplicate_case_values] Use DartObject and hasKnownValue.

lib/src/rules/diagnostic_describe_all_properties.dart, test/mock_packages/flutter/lib/src/foundation/diagnostics.dart, test/rules/diagnostic_describe_all_properties.dart
Flutter is planning to deprecate `Diagnosticable` in favor of `DiagnosticableMixin`, so this is just a preemptive change to make that deprecation a non-issue for the linter. This change will also make it possible for Flutter to change all of the classes that use "extends Diagnosticable" to switch to "with DiagnosticableMixin" without triggering the lint.
The implementation of `Diagnosticable` in Flutter is already using `DiagnosticableMixin`, even on the stable channel.
=> Use DiagnosticableMixin instead of Diagnosticable

example/all.yaml, lib/src/rules.dart, lib/src/rules/unnecessary_string_escapes.dart, test/rules/unnecessary_string_escapes.dart
According to https://github.com/dart-lang/linter/issues/2002#issuecomment-588253987 this PR rename `unnecessary_escapes_in_string` to `unnecessary_string_escapes`.
=> rename unnecessary_escapes_in_string to unnecessary_string_escapes

example/all.yaml, lib/src/rules.dart, lib/src/rules/unnecessary_raw_strings.dart, test/rules/unnecessary_raw_strings.dart
Use raw string only when needed.
**BAD:**
```
var s1 = r'a';
```
**GOOD:**
```
var s1 = 'a';
var s2 = r'$a';
var s3 = r'\a';
```
=> unnecessary_raw_strings

pubspec.yaml, test/rule_test.dart, test/util/annotation.dart, test/util/annotation_test.dart
This PR allow to mark lints in test file on another line:
```dart
// LINT [+1] lint on the following line
var x = y;
// LINT [+3] lint 3 lines after this line
var x = '''
''';
var x = y;
// LINT [-1] lint on the above line
```
The previous pattern `// LINT [column:length] message` still works and you can combine them with `// LINT [lineDelta,column:length] message`
=> allow LINT to reference a relative line

lib/src/ast.dart, lib/src/rules/unnecessary_getters_setters.dart, test/rules/unnecessary_getters_setters.dart
Fixes: https://github.com/dart-lang/linter/issues/1992
/fyi @srawlins
=> ignore unnec. getter/setter if deprecated

lib/src/rules/non_constant_identifier_names.dart, test/rules/non_constant_identifier_names.dart
=> allow underscores for constructor names

lib/src/rules/avoid_shadowing_type_parameters.dart, test/rules/avoid_shadowing_type_parameters.dart
=> support mixins and extensions in `avoid_shadowing_type_parameters`

lib/src/rules/sort_child_properties_last.dart
The GOOD example both violated the lint and did not correspond to the same layout as the BAD example. This makes the GOOD example match the existing BAD example, and moves the floatingActionButton above child so that it passes the lint.
=> Fix sort_child_properties_last example

lib/src/rules/unsafe_html.dart, test/rules/unsafe_html.dart
Three new unsafe APIs from `dart:html` have been identified:
* `IFrameElement.srcdoc=`
* `Element.createFragment`
* `Element.setInnerHtml`
=> Add three new unsafe APIs to the unsafe_html rule

lib/src/rules/sized_box_for_whitespace.dart, test/rules/sized_box_for_whitespace.dart
Following [my comment on the initial PR](https://github.com/dart-lang/linter/pull/2049#issuecomment-607491147) there are some cases with behaviour changes. For instance the following change doesn't display the same thing (you can try it in dartpad):
```diff
import 'package:flutter/material.dart';
void main() => runApp(MyApp());
class MyApp extends StatelessWidget {
@override
Widget build(BuildContext context) {
return MaterialApp(
title: 'Flutter Demo',
debugShowCheckedModeBanner: false,
theme: ThemeData(
primarySwatch: Colors.blue,
),
home: Column(
children: [
-          ColoredBox(color: Colors.red, child: Container(height: 80)),
+          ColoredBox(color: Colors.red, child: SizedBox(height: 80)),
SizedBox(height: 80),
-          ColoredBox(color: Colors.blue, child: Container(height: …
```
=> reduce false positive for sized_box_for_whitespace

lib/src/rules/unsafe_html.dart, test/rules/unsafe_html.dart
Lint rules which report on security-related issues should not be ignorable via comments like `// ignore:` or `// ignore_for_file:`. Upgrading unsafe_html from LintCode to SecurityLintCode prevents exactly this. If a developer writes:
```dart
// ignore: unsafe_html
IFrameElement()..srcdoc = 'foo';
```
then the analyzer will still report the unsafe_html violation.
=> Switch unsafe_html to be a SecurityLintCode

example/all.yaml, lib/src/rules.dart, lib/src/rules/use_is_even_rather_than_modulo.dart, test/rules/use_is_even_rather_than_modulo.dart
Add a lint check to advice users to replace the use of "%2==0" with intValue.isEven and intValue.isOdd.
This also takes into account "!=" and all the comparator operator.
Fixes #2065
=> [Lint] Prefer intValue.isEven check

lib/src/rules/exhaustive_cases.dart, test/rules/exhaustive_cases.dart
=> `exhaustive_cases`: don’t flag missing cases that are defaulted

lib/src/rules/unnecessary_statements.dart, test/rules/unnecessary_statements.dart
Fixes #2163
I considered some fancy  footwork to  check for really side-effecting expressions but opted instead for the simpler  implementation which I think will ultimately serve us better in the long run (esp. post  NNBD migration).
/cc @bwilkerson @MichaelRFairhurst
=> Don’t lint as expressions.

lib/src/rules/unnecessary_lambdas.dart, test/_data/unnecessary_lambdas/lintconfig.yaml, test/_data/unnecessary_lambdas/src/a.dart, test/_data/unnecessary_lambdas/src/b.dart, test/integration_test.dart
=> skip deferred functions in unnecessary_lambdas

lib/src/rules/unawaited_futures.dart
The function is being moved from `package:pedantic` to `package:meta`. There do not appear to be any required coding changes (the lint doesn't care which function the future is passed to), but there are a couple of minor doc changes.
This PR should not be merged until after a version of `package:meta` has been published that contains the new function.
@davidmorgan
=> Reference the function unawaited from the meta package

lib/src/rules/unawaited_futures.dart
This reverts commit 83a6f4f3cd6a46e98787f534a50535d5fb820996.
We decided to back out the move of unawaited from pedantic to meta, so
the advice should be restored.
=> Revert "Reference the function unawaited from the meta package"

lib/src/analyzer.dart
I would like to remove these exports from analyzer in the next breaking change.
https://dart-review.googlesource.com/c/sdk/+/154123
=> Stop relying on exports from resolver.dart, use libraries directly.

lib/src/analyzer.dart, pubspec.yaml
Update to latest analyzer release.
Note the  failing tests: https://travis-ci.org/github/dart-lang/linter/jobs/708226853.
For context, integration tests live in `test/integration_test`.  For example here:
https://github.com/dart-lang/linter/blob/300531dce438c71e93cd447ed3acb2e69cf37299/test/integration_test.dart#L682-L693
With associated data files in `test/_data`, like:
https://github.com/dart-lang/linter/blob/300531dce438c71e93cd447ed3acb2e69cf37299/test/_data/prefer_relative_imports/lib/main.dart#L1
=> Bump analyzer

lib/src/rules/unnecessary_string_escapes.dart
Previous versions of pkg:analyzer didn't give the correct offsets for
even simple interpolation strings such as "$foo". This prompted the
workaround code here. However, the workaround code here doesn't handle
unclosed quotes:
```dart
"foo$bar
```
The analyzer API has been fixed, and supports this error recovery, so we
can drop the workaround and that will fix the RangeError we've been
seeing.
=> Fix RangeError in unnecessary_string_escapes

lib/src/rules/diagnostic_describe_all_properties.dart, pubspec.yaml, test/rules/diagnostic_describe_all_properties.dart
Essentially a revert of https://github.com/dart-lang/linter/pull/2003 as `Diagnosticable` is here to stay.
/fyi @gspencergoog 
=> Check for `Diagnosticable`s (over `DiagnosticableMixin`s)

lib/src/rules/prefer_asserts_in_initializer_lists.dart
This is to fix the bug reported in #2198.
There isn't a test for it, though I suspect it happens when there's code of the form
```dart
class C {
C(this.x);
}
```
(a field initializer for a non-existent field).
I'm happy to add a test, but I'm not sure of the best approach.
=> Fix an NPE in prefer_asserts_in_initializer_lists

example/all.yaml, lib/src/rules.dart, lib/src/rules/unnecessary_nullable_for_final_variable_declarations.dart, test/rules/experiments/nnbd/rules/unnecessary_nullable_for_final_variable_declarations.dart, test/rules/unnecessary_nullable_for_final_variable_declarations.dart
Use non-nullable type for final variable initialized with non-nullable value.
**BAD:**
```
final int? i = 1;
```
**GOOD:**
```
final int i = 1;
```
Fixes #2203
=> add lint unnecessary_nullable_for_final_variable_declarations

example/all.yaml
Travis is unhappy with the ordering of `example/all.yaml` from #2208.
=> Fix example/all.yaml ordering to make Travis happy

example/all.yaml, lib/src/rules.dart, lib/src/rules/avoid_type_to_string.dart, test/rules/avoid_type_to_string.dart
This rule would suggest users avoid calling `toString()` on objects of type `Type` (declared in `dart:core`), since the result may be minified by some compilers in release mode.
This was inspired by a recent post on an internal mailing list. No official verdict on whether this is a good idea has been reached at the time of writing, but it seemed useful so I decided to try implementing it for fun. If people want to move forward with this lint rule, then this PR could be a good starting point.
Credit for the idea and reasoning goes to @matanlurey 
**Should this be further discussed on this PR, a new issue, or the mailing list?**
> \<Type\>.toString() does not contractually return the user-defined name of the Type (or underlying class ). What that means in practice is that development mode …
=> Lint proposal: avoid_type_to_string

pubspec.yaml
When there's a new analyzer that supports `cli_util` 0.2.0, after this our pana baseline should be fixed.
=> widen github deps

tool/travis.sh
Modernize coverage reporting to mimic how `dart-lang/coverage` self-reports.
/fyi @grouma
=> migration from dart_coveralls

example/all.yaml, lib/src/rules.dart, lib/src/rules/null_check_on_nullable_type_parameter.dart, lib/src/rules/unnecessary_null_checks.dart, test/rules/experiments/nnbd/rules/null_check_on_nullable_type_parameter.dart, test/rules/experiments/nnbd/rules/unnecessary_null_checks.dart
Don't use null check on a potentially nullable type parameter.
**BAD:**
```dart
T run<T>(T callback()) {
T? result;
(() { result = callback(); })();
return result!;
}
```
**GOOD:**
```dart
T run<T>(T callback()) {
T? result;
(() { result = callback(); })();
return result as T;
}
```
Fixes #2243
In this PR I also extended `unnecessary_null_checks` to return cases.
=> add null_check_on_nullable_type_parameter

example/all.yaml
**EDIT:** build fixed w/ #2253.
---
Oddly, travis is not reporting a failure
but the integration tests are broken:
https://travis-ci.org/github/dart-lang/linter/jobs/731431247
This should fix it but we do need to figure out what's up with the build...
---
=> sort all.yaml

lib/src/rules/public_member_api_docs.dart, test/_data/public_member_api_docs/test/b.dart
See false positives: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8867784516868845056/+/steps/analyze_flutter_flutter/0/stdout.
=> fix overreporting on generic type aliases

lib/src/ast.dart, lib/src/rules/prefer_asserts_in_initializer_lists.dart, lib/src/rules/prefer_final_fields.dart, lib/src/rules/prefer_initializing_formals.dart, lib/src/rules/unnecessary_null_checks.dart, lib/src/rules/unnecessary_overrides.dart, lib/src/rules/unnecessary_this.dart, lib/src/rules/unsafe_html.dart, lib/src/rules/use_late_for_private_fields_and_variables.dart, lib/src/rules/use_setters_to_change_properties.dart, lib/src/rules/use_string_buffers.dart, lib/src/rules/void_checks.dart, lib/src/util/condition_scope_visitor.dart, lib/src/util/dart_type_utilities.dart, lib/src/util/leak_detector_visitor.dart, pubspec.yaml
I have a version of analyzer that stops setting `SimpleIdentifier.staticElement/staticType` when the identifier is the final identifier of the LHS of an assignment (or increment/decrement). This will happen in a new breaking changes version of `analyzer`. This PR prepares the `linter` for using `CompoundAssignmentExpression` instead.
=> Use analyzer 0.40.4 and CompoundAssignmentExpression.

lib/src/rules/always_use_package_imports.dart, lib/src/rules/avoid_renaming_method_parameters.dart, lib/src/rules/prefer_relative_imports.dart
=> short-circuit node processor registration when not in `lib`

lib/src/rules/type_init_formals.dart, test/rules/experiments/nnbd/rules/type_init_formals.dart, test/rules/type_init_formals.dart
If the type of the field formal parameter is different from the field type, it has implications, and should be left alone.
Fixes #2192
=> type_init_formals: Allow types not equal to the field type

lib/src/util/dart_type_utilities.dart, test/rules/experiments/nnbd/rules/unrelated_type_equality_checks.dart
Nullability should be ignored when considering "relatedness". It is valid to compare `num` and `int?` objects.
Fixes #2196
=> unrelated_type_equality_checks: ignore nullability

test/_data/sort_pub_dependencies/pubspec.yaml, test/integration_test.dart
The false positive was mis-reported but did identify some untested cases.
Fixes #2271 
=> + `sort_pub_dependencies` test cases

lib/src/rules/avoid_escaping_inner_quotes.dart, lib/src/rules/avoid_redundant_argument_values.dart, lib/src/rules/avoid_type_to_string.dart, lib/src/rules/avoid_unnecessary_containers.dart, lib/src/rules/camel_case_extensions.dart, lib/src/rules/do_not_use_environment.dart, lib/src/rules/exhaustive_cases.dart, lib/src/rules/leading_newlines_in_multiline_strings.dart, lib/src/rules/missing_whitespace_between_adjacent_strings.dart, lib/src/rules/no_default_cases.dart, lib/src/rules/no_logic_in_create_state.dart, lib/src/rules/no_runtimeType_toString.dart, lib/src/rules/sized_box_for_whitespace.dart, lib/src/rules/unnecessary_null_checks.dart, lib/src/rules/unnecessary_raw_strings.dart, lib/src/rules/unnecessary_string_escapes.dart, lib/src/rules/unnecessary_string_interpolations.dart, lib/src/rules/use_is_even_rather_than_modulo.dart, lib/src/rules/use_key_in_widget_constructors.dart, lib/src/rules/use_late_for_private_fields_and_variables.dart, lib/src/rules/use_raw_strings.dart, tool/rule.dart
(`LinterContext` is no longer optional.)
=> update `registerNodeProcessors` calls

lib/src/rules/always_require_non_null_named_parameters.dart
This lint should not run in a Null Safety library; the "required" rules cover this in static analysis done by the Analyzer.
Without this new check, the new test results in an incorrect lint report.
Fixes #2236
=> always_require_non_null_named_parameters: skip in Null Safety

lib/src/rules/prefer_constructors_over_static_methods.dart, test/rules/prefer_constructors_over_static_methods.dart
Compare the method's return _type_ with it's parent class's _type_ rather than
comparing _elements_ to account for generics (don't report a method which
returns `A<int>`).
And don't report any generic method, because it might use the type parameters
in its parameters, which a constructor cannot do.
Fixes #2149
=> prefer_constructors_over_static_methods: take generics into account

test/integration/always_require_non_null_named_parameters.dart, test/integration/avoid_private_typedef_functions.dart, test/integration/avoid_relative_lib_imports.dart, test/integration/avoid_renaming_method_parameters.dart, test/integration/avoid_web_libraries_in_flutter.dart, test/integration/cancel_subscriptions.dart, test/integration/close_sinks.dart, test/integration/directives_ordering.dart, test/integration/exhaustive_cases.dart, test/integration/file_names.dart, test/integration/flutter_style_todos.dart, test/integration/lines_longer_than_80_chars.dart, test/integration/only_throw_errors.dart, test/integration/overridden_fields.dart, test/integration/packages_file_test.dart, test/integration/prefer_asserts_in_initializer_lists.dart, test/integration/prefer_const_constructors_in_immutables.dart, test/integration/prefer_relative_imports.dart, test/integration/public_member_api_docs.dart, test/integration/sort_pub_dependencies.dart, test/integration/unnecessary_lambdas.dart, test/integration/unnecessary_string_escapes.dart, test/integration_test.dart
Running individual integration tests is tedious and the integration test library unwieldy.  To help remedy, this defines dedicated test groups for core and rule tests and further extracts rule tests into their own individually runnable libraries.
=> refactor integration tests

lib/src/rules/void_checks.dart, test/rules/experiments/nnbd/rules/void_checks.dart, test/rules/void_checks.dart
The type of `() {}` changed to `Null Function()` (from `void Function()` in Null Safety. The check performed in void_checks must then compare assignability with `Future<dynamic>?`.
Fixes #2185
=> void_checks: Specify individual types which a FutureOr<void> target can accept

.github/install-dart.sh, .github/workflows/build.yaml
- add support for github actions
This add support for github actions. This is more or less a straight port of the existing travis.yaml file (https://github.com/dart-lang/linter/blob/master/.travis.yml). We may need to land this PR to see the actions run as there aren't any existing actions for the repo.
It would be great to evolve dart support for actions a bit so that a per-repo install-dart.sh isn't required. Perhaps there's some creative use of the std. dart docker container which would make the install script not needed.
=> add support for github actions

test/_data/lines_longer_than_80_chars/a.dart, test/integration/lines_longer_than_80_chars.dart
~With analyzer 0.40.5, comma-separated ignores appear to no longer allow for spaces. I'm not sure if this is a big (@bwilkerson?) but this fix updates our newly failing test:~
https://travis-ci.org/github/dart-lang/linter/jobs/740287956#L438-L462
**EDIT:** real issue was new diagnostics.
=> fix failing lines_longer_than_80_chars integration test

.travis.yml
I was hoping todays dev release would have the required fix but apparently not...
(HOLDING for the next one.)
See: https://github.com/dart-lang/sdk/issues/44027
=> re-enable dev on travis

lib/src/util/dart_type_utilities.dart, tool/scorecard.dart
Address lint.
Tempting to move this to `EnumLikeClassDescription` but  that'd be technically API breaking 😬.
=> ignore prefer_constructors_over_static_methods

test/rules/experiments/nnbd/rules/prefer_constructors_over_static_methods.dart
The NNBD case appears to have been addressed by the `typeSystem.isAssignableTo` check added in #2333.
@bwilkerson: correct me if I've missed any  cases?
Closes: #2280.
=> nullable return type test case

lib/src/test_utilities/test_resource_provider.dart
- change from subclassing PhysicalResourceProvider
We'd like to change the constructor for PhysicalResourceProvider (to not take any required args); this refactor will make the change a little easier.
=> Change from subclassing PhysicalResourceProvider

CHANGELOG.md, lib/src/rules/prefer_collection_literals.dart, lib/src/version.dart, pubspec.yaml, test/rules/prefer_collection_literals.dart
Check the parameter element type for the specific collection
instantiation argument rather than check the parameter type of the first
argument.
=> Fix false negative for collections as parameters

CHANGELOG.md, lib/src/rules/prefer_collection_literals.dart, test/rules/prefer_collection_literals.dart
Previously the lint would allow passing a `LinkedHashSet` instantiation
if the static type wasn't `Set`, and similarly for `LinkedHashMap`. This
allowed cases where the literal would also work when passed or assigned
to something requiring any supertype like `Object`, `dynamic`, or
`Iterable`.
Invert the condition used for the `typeCheck` callback and add checks
looking specifically for the `LinkedHash` variants of the static type.
Add tests demonstrating the new places the lint will trigger.
=> Fix false negatives for collection assignments

pubspec.yaml, test/mocks.dart
This is a step to do https://dart-review.googlesource.com/c/sdk/+/174322
=> The first step to migrate to ErrorCode constructor with named parameters

tool/machine.dart
Sample (snipped) output:
```json
[
{
"name": "always_use_package_imports",
"description": "Avoid relative imports for files in `lib/`.",
"group": "errors",
"details": "*DO* avoid relative imports for files in `lib/`.\n\nWhen mixing relative and absolute imports it's possible to create confusion\nwhere the same member gets imported in two different ways. One way to avoid\nthat is to ensure you consistently use absolute imports for files withing the\n`lib/` directory.\n\nThis is the opposite of 'prefer_relative_imports'.\nMight be used with 'avoid_relative_lib_imports' to avoid relative imports of\nfiles within `lib/` directory outside of it. (for example `test/`)\n\n**GOOD:**\n\n```\nimport 'package:foo/bar.dart';\n\nimport 'package:foo/baz.dart';\n\nimport …
=> simple machine readable rule listing

lib/src/cli.dart, tool/travis.sh
Migrate from `dartanalyzer` in build.
Sample of a breakage:
/cc @bwilkerson @devoncarew
=> prefer `dart analyze`

tool/doc.dart, tool/machine.dart
Follow-up from #2359, adds machine json to the published docs.
See: https://dart-lang.github.io/linter/lints/machine/rules.json
Ultimate format and desired metadata still TBD.
(If desired we could pull this into `tools_metadata` as well but doing the work here feels right.)
/fyi @csells
/cc @devoncarew
=> publish machine json

CONTRIBUTING.md, lib/src/rules/empty_statements.dart, lib/src/rules/lines_longer_than_80_chars.dart
=> prefer `dart format` in docs

README.md
=> update docs to prefer `dart analyze` (over `dartanalyzer`)

styles.css
A small change, but since we are using it for inline code text, the lack of 700 makes it slightly blurry.
The change is minor and I tried to include screenshots but compression makes the difference hard to tell.
=> Add font-weight 700 for Roboto Mono

README.md
Probably not a great idea to keep a soon to be deprecated lint in the `README` example. 😬 
See: #1401 
=> remove `avoid_as` example

lib/src/util/dart_type_utilities.dart
The mentioned issue has since been fixed and the lint is no longer incorrectly being flagged here.
=> Remove todo that his since been fixed

lib/src/formatter.dart
We already have `charcode` as a dependency, so might as it well use it here(plus we get the added benefit of them being const). 
I also moved the `benchmarksRuns` declaration below what seems to be its corresponding comment.
=> Use charcode instead of codeUnitAt for const chars

tool/machine.dart
Adds maturity and rule set info to machine json.
```json
{
"name": "avoid_empty_else",
"description": "Avoid empty else statements.",
"group": "errors",
"maturity": "stable",
"sets": [
"flutter",
"pedantic"
],
"details": "\n**AVOID** empty else statements.\n\n**BAD:**\n```\nif (x > y)\n  print(\"1\");\nelse ;\n  print(\"2\");\n```\n\n"
},
```
See: #2359.
=> add maturity and rule set info to machine json output

lib/src/rules/avoid_type_to_string.dart
The version of `analyzer` at the time did not yet have `addArgumentList` so this TODO was left. I've gone ahead and switched to the new method and removed the TODO.
Refer to https://github.com/dart-lang/linter/pull/2209#discussion_r465171453 for context.
Cc @bwilkerson
=> Switch to addArgumentList and remove TODO

tool/canonical/scorecard.dart
Stats gathering and punch-list generation for scored lints support.  This will evolve.
Sample run:
| name | fix | score | recommend | bug refs |
| :--- | :---: | :---: | :---: | :---  |
|  [avoid_empty_else](https://dart-lang.github.io/linter/lints/avoid_empty_else.html) | 💡 | ✅ | |  |
|  [avoid_relative_lib_imports](https://dart-lang.github.io/linter/lints/avoid_relative_lib_imports.html) | 💡 | ✅ | |  |
|  [avoid_shadowing_type_parameters](https://dart-lang.github.io/linter/lints/avoid_shadowing_type_parameters.html) | | ✅ | |  |
|  [avoid_types_as_parameter_names](https://dart-lang.github.io/linter/lints/avoid_types_as_parameter_names.html) | 💡 | ✅ | |  |
|  [await_only_futures](https://dart-lang.github.io/linter/lints/await_only_futures.html) | 💡 | ✅ | |  |
| …
=> score support scoring

tool/canonical/fix_excludes.json, tool/canonical/scorecard.dart
Follow-up from https://github.com/dart-lang/linter/issues/2405.
Sample run:
| name | fix | score | recommend | bug refs |
| :--- | :---: | :---: | :---: | :---  |
|  [`avoid_empty_else`](https://dart-lang.github.io/linter/lints/avoid_empty_else.html) | 💡 | ✅ | |  |
|  [`avoid_relative_lib_imports`](https://dart-lang.github.io/linter/lints/avoid_relative_lib_imports.html) | 💡 | ✅ | |  |
|  [`avoid_shadowing_type_parameters`](https://dart-lang.github.io/linter/lints/avoid_shadowing_type_parameters.html) | ➖ | ✅ | |  |
|  [`avoid_types_as_parameter_names`](https://dart-lang.github.io/linter/lints/avoid_types_as_parameter_names.html) | 💡 | ✅ | |  |
|  [`await_only_futures`](https://dart-lang.github.io/linter/lints/await_only_futures.html) | 💡 | ✅ | |  |
| …
=> tracked unfixable lints and updated scoring

AUTHORS
I prefer this email for people contacting me and I've fully switched to it for git authoring purposes.
_Ignore the fact I used my name in third person..._
=> Update Parker's email

styles.css
Due to the wrapper width being increased a little while ago, the website can appear outside the browser window as the transition to the 100% contained version happened too late. This causes the transition to occur before the wrapper runs out of space.
This screenshot illustrates the issue:
=> Increase break point for margin-0 transition

example/all.yaml, lib/src/rules.dart, lib/src/rules/avoid_dynamic_calls.dart, test/rules/experiments/nnbd/rules/avoid_dynamic_calls.dart
Closes https://github.com/dart-lang/linter/issues/1782.
---
This is a pretty difficult lint to get "right". I tried my best with the following principals:
1. Simple _existence_ of `dynamic` or a dynamic-ly typed expression should not cause a lint. 
There are many places where a dynamic expression can be used in a way that does not "cause" a dynamic call:
- Some types of expressions, such as `as`, `is`, `??`, or `x!` are non-virtual, and are not dynamic calls.
- Some trickier cases like members that exist on `Object?` (`==`, `hashCode`, `runtimeType`, `toString`).
2. Implicit downcasts from `dynamic` to non-`dynamic`, while bad, is _not_ a dynamic call (it's a runtime cast).
There are other lints and analysis modes that can lint these.
3. While not explicitly typed `dynamic`, a static type …
=> Initial commit of avoid_dynamic_calls.

CHANGELOG.md, lib/src/rules/avoid_dynamic_calls.dart, test/rules/experiments/nnbd/rules/avoid_dynamic_calls.dart
Fixes https://github.com/dart-lang/linter/issues/2424.
=> Fix a.call() for avoid_dynamic_calls.

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
/cc @bwilkerson @matanlurey @devoncarew
=> prep for `0.1.129` release

lib/src/rules/avoid_as.dart
=> deprecate avoid_as

example/all.yaml, lib/src/rules.dart, lib/src/rules/deprecated_consistency.dart, test/rules/deprecated_consistency.dart
Lint to apply `@Deprecated()` consistently:
- if a class is deprecated its contructors should also be deprecated.
- if a field is deprecated the contructor parameter pointing to it should also be deprecated.
- if a contructor parameter pointing to a field is deprecated the field should also be deprecated.
Related to flutter/flutter#75903, flutter/flutter#75813, and https://docs.google.com/document/d/1gR-uEryHrAtkU8-6rTg489JbxtBOnTqG_W3WDCcfU00/edit?usp=sharing&resourcekey=0-6Oy2jitxjIWgBFntFZsWmg
=> add deprecated_consistency

lib/src/rules/package_api_docs.dart, lib/src/rules/package_prefixed_library_names.dart
Removes uses of the explicit `!` modifiers in the `package_` lints.
=> Clean up package_ rules NNBD migration

lib/src/util/score_utils.dart, pubspec.yaml, tool/bot/rule_doc_check.dart, tool/bot/version_check.dart, tool/canonical/scorecard.dart, tool/crawl.dart, tool/doc.dart, tool/scorecard.dart, tool/since.dart
Updates to new `http` APIs and nullable `github`.
Definitely room for cleaning up but this gets us a lot of the way there.
=> upgrade to nullable http and github

lib/src/rules/always_put_required_named_parameters_first.dart, test/rules/always_put_required_named_parameters_first.dart
This updates the test to test the null safety feature with the `required` keyword and instead focuses on the `require` keyword in the rule documentation as that is what users should be using after the migration.
=> Update required named parameters rule for new required keyword

example/all.yaml, lib/src/rules.dart, lib/src/rules/avoid_multiple_declarations_per_line.dart, test/rules/avoid_multiple_declarations_per_line.dart
Lint on multiple variable declarations in a single line.
Fixes # (issue)
https://github.com/dart-lang/linter/issues/2501
=> add avoid_multiple_declarations_per_line

lib/src/rules/curly_braces_in_flow_control_structures.dart
Switches from an `http` Wikipedia link to a `https` one in curly_braces_in_flow_control_structures
=> Switch from http to https in curly braces lint

.github/workflows/build.yaml
Pana is crashing the build.  This disables baselining pending a fix: https://github.com/dart-lang/linter/issues/2504.
/fyi @jonasfj
=> disable pana baselining

lib/src/rules/prefer_mixin.dart, test/_data/prefer_mixin/lib.dart, test/integration/prefer_mixin.dart, test/integration_test.dart
Dart collection legacy mixins had the wrong library name and so were not being allowed as expected.  This fixes that.
See: https://github.com/dart-lang/linter/issues/2514
/fyi @goderbauer
=> fix legacy dart:collection mixin uris

tool/canonical/recommend.yaml
As discussed in our meeting today.
In the future: could be replaced with https://github.com/dart-lang/linter/issues/2519.
/cc @pq @Hixie @mit-mit @munificent @devoncarew
=> Remove avoid_private_typedef_functions from recommend.yaml

lib/src/rules/camel_case_types.dart, test/rules/experiments/nonfunction-type-aliases/rules/camel_case_types.dart
=> `camel_case_types` support for nonfunction type aliases

lib/src/util/unrelated_types_visitor.dart, test/rules/iterable_contains_unrelated_type.dart, test/rules/list_remove_unrelated_type.dart
Fixes #1003
This is an attempt to fix `iterable_contains_unrelated_type`. This rule works in the test suite but not with a real SDK.
This is because the [MockSdk] defines the hierarchy as `List<T> implements Iterable<T>` ([analyzer/mock_sdk.dart](https://github.com/dart-lang/sdk/blob/caa31f55be518e2de0bf723c81c853c2362dafb5/pkg/analyzer/lib/src/test_utilities/mock_sdk.dart#L419)) while the real SDK defines `List<T> extends EfficientLengthIterable<T>` ([sdk/core/list.dart](https://github.com/dart-lang/sdk/blob/c5d01ec4f7078a75b038a2ed04312afb50154323/sdk/lib/core/list.dart#L52))
=> Fix iterable_contains_unrelated_type

example/all.yaml, lib/src/rules.dart, lib/src/rules/library_private_types_in_public_api.dart, test/rules/library_private_types_in_public_api.dart
I chose to give this a fairly specific name because what it catches is fairly limited.
Fixes #2519
=> Implement the lint library_private_types_in_public_api

example/all.yaml, lib/src/rules.dart, lib/src/rules/prefer_null_aware_method_calls.dart, test/rules/prefer_null_aware_method_calls.dart
Instead of checking nullability of a function/method `f` before calling it you
can use `f?.call()`.
**BAD:**
```
if (f != null) f!();
```
**GOOD:**
```
f?.call();
```
Requested by https://github.com/flutter/flutter/pull/79003#issuecomment-806156141
=> add prefer_null_aware_method_calls

lib/src/rules/lines_longer_than_80_chars.dart, test/integration/lines_longer_than_80_chars.dart
This came up at https://github.com/Dart-Code/Dart-Code/issues/3263 / https://github.com/dart-lang/linter/issues/2570. Previously the entire line would be included in the range which means clicking the lint would place the caret at the start of the line and not in the area where you need to make the modification. Jumping to 80 saves time time - especially if using a screenreader as the original reporter.
Fixes #2570.
=> Reduce lines_longer_than_80_chars range to only the offending part of the line

lib/src/rules/unnecessary_getters_setters.dart
The sentence is incomplete or confusing before, I assume what the writer mean in the first place and add the missing words.
the rule is `unnecessary_getters_setters`, I discovered it when reading from the lint [rule online doc](https://dart-lang.github.io/linter/lints/unnecessary_getters_setters.html):
=> missing words in the document

CHANGELOG.md, lib/src/rules/directives_ordering.dart
`directives_ordering` had a gap for google3 because those don't count as pub packages; this seems to do the job.
=> Fix `directives_ordering` for non-pub packages.

tool/canonical/core.yaml, tool/canonical/recommend.yaml
As discussed in our meeting today this PR removes the three lints from the `core.yaml` / `recommend.yaml` set for which we don't have full agreement between Flutter and Dart yet.
For details see also https://github.com/flutter/flutter/issues/78432.
=> Remove lints without full alignment

test/engine_test.dart, test/experiments_test.dart, test/integration/always_require_non_null_named_parameters.dart, test/integration/avoid_private_typedef_functions.dart, test/integration/avoid_relative_lib_imports.dart, test/integration/avoid_renaming_method_parameters.dart, test/integration/avoid_web_libraries_in_flutter.dart, test/integration/cancel_subscriptions.dart, test/integration/close_sinks.dart, test/integration/directives_ordering.dart, test/integration/exhaustive_cases.dart, test/integration/file_names.dart, test/integration/flutter_style_todos.dart, test/integration/lines_longer_than_80_chars.dart, test/integration/only_throw_errors.dart, test/integration/overridden_fields.dart, test/integration/packages_file_test.dart, test/integration/prefer_asserts_in_initializer_lists.dart, test/integration/prefer_const_constructors_in_immutables.dart, test/integration/prefer_mixin.dart, test/integration/prefer_relative_imports.dart, test/integration/public_member_api_docs.dart, test/integration/sort_pub_dependencies.dart, test/integration/unnecessary_lambdas.dart, test/integration/unnecessary_string_escapes.dart, test/integration/use_build_context_synchronously.dart, test/integration_test.dart, test/rule_test.dart, test/test_constants.dart, test/util/rule_debug.dart
Some constant corralling to prepare for moving rule test data out of `test/` (#2595).
=> introduce test constants

lib/src/rules/prefer_initializing_formals.dart, test_data/rules/prefer_initializing_formals.dart
=> `prefer_initializing_formals`: allow assignments where identifier names don't match

example/all.yaml, lib/src/rules.dart, lib/src/rules/prefer_final_parameters.dart, lib/src/rules/unnecessary_final.dart, test_data/rules/prefer_final_parameters.dart
I know this one doesn't fit everyone's style, but it's how I instinctively write my code and goes well along with `prefer_final_locals`. It's strange to have your locals be `final` but not your parameters which are similar to locally declared variables.
It also goes well with `parameter_assignments` as once they removal those assignments, then this lint can trigger. Then they won't trigger the `parameter_assignments` lint again.
Fixes #1914
=> Add prefer_final_parameters lint

lib/src/rules/avoid_web_libraries_in_flutter.dart
=> mark `avoid_web_libraries_in_flutter` as stable

example/all.yaml, lib/src/rules.dart, lib/src/rules/noop_primitive_operations.dart, test_data/rules/noop_primitive_operations.dart
Follow up on #2618
Some operations on primitive types are idempotent and can be removed.
**BAD:**
```dart
doubleValue.toDouble();
intValue.toInt();
intValue.round();
intValue.ceil();
intValue.floor();
intValue.truncate();
string.toString();
string = 'hello\n'
'world\n'
''; // useless empty string
```
=> add noop_primitive_operations

tool/machine.dart
Fixes #2627
Example:
```json
...
{
"name": "unnecessary_final",
"description": "Don't use `final` for local variables.",
"group": "style",
"maturity": "stable",
"incompatible": [
"prefer_final_locals",
"prefer_final_parameters"
],
"sets": [],
"details": "**DON'T** use `final` for local variables.\n\n`var` is shorter, and `final` does not change the meaning of the code.\n\n**BAD:**\n```dart\nvoid badMethod() {\n  final label = 'Final or var?';\n  for (final char in ['v', 'a', 'r']) {\n    print(char);\n  }\n}\n```\n\n**GOOD:**\n```dart\nvoid goodMethod() {\n  var label = 'Final or var?';\n  for (var char in ['v', 'a', 'r']) {\n    print(char);\n  }\n}\n```\n"
},
...
```
/cc @bwilkerson @parlough
=> add incompatible rules

lib/src/rules/prefer_contains.dart
Another significant gain moving away from visiting simple identifiers. (5ms vs 26)
=> refactor `prefer_contains` analysis to use visitMethodInvocation

lib/src/rules/sort_child_properties_last.dart, test_data/rules/sort_child_properties_last.dart
Related to flutter/flutter#81687
This relax the rule to accept closure after `child` property.
=> relax sort_child_properties_last to accept closures after child

example/all.yaml, lib/src/rules.dart, lib/src/rules/use_test_throws_matchers.dart, test_data/mock_packages/test_api/lib/src/frontend/expect.dart, test_data/mock_packages/test_api/lib/test_api.dart, test_data/mock_packages/test_api/pubspec.yaml, test_data/rules/.mock_packages, test_data/rules/use_test_throws_matchers.dart
Use the `throwsA` matcher instead of try-catch with `fail()`.
**BAD:**
```dart
// sync code
try {
someSyncFunctionThatThrows();
fail('expected Error');
} on Error catch (error) {
expect(error.message, contains('some message'));
}
// async code
try {
await someAsyncFunctionThatThrows();
fail('expected Error');
} on Error catch (error) {
expect(error.message, contains('some message'));
}
```
**GOOD:**
```dart
// sync code
expect(
() => someSyncFunctionThatThrows(),
throwsA(isA<Error>().having((Error error) => error.message, 'message', contains('some message'))),
);
// async code
await expectLater(
() => someAsyncFunctionThatThrows(),
throwsA(isA<Error>().having((Error error) => error.message, 'message', contains('some message'))),
);
```
=> add use_test_throws_matchers

lib/src/util/score_utils.dart
Missed in https://github.com/dart-lang/linter/pull/2646.
(I have a TODO to consolidate these two fetch URI paths but that's part of a bigger cleanup; this just gets this aligned in the meantime.)
/cc @bwilkerson @goderbauer
=> update flutter lint source

lib/src/rules/avoid_returning_null_for_future.dart, test_data/rules/avoid_returning_null_for_future.dart
Related to #1930
In nullsafety it should be ok to have `Future<String>? f() => null`. (simplified version of an issue in flutter where enabling the lint would have introduce an error)
=> disable avoid_returning_null_for_future in nullsafety

lib/src/analyzer.dart, lib/src/cli.dart, lib/src/rules/depend_on_referenced_packages.dart, lib/src/util/dart_type_utilities.dart, test/formatter_test.dart, test/integration/depend_on_referenced_packages.dart, test/integration_test.dart, test/mocks.dart, test/rule_test.dart, test/util/test_utils.dart, test_data/integration/depend_on_referenced_packages/_packages, test_data/integration/depend_on_referenced_packages/bin/main.dart, test_data/integration/depend_on_referenced_packages/lib/public.dart, test_data/integration/depend_on_referenced_packages/lib/sample_project.dart, test_data/integration/depend_on_referenced_packages/pubspec.yaml, test_data/integration/depend_on_referenced_packages/test/private.dart, test_data/integration/depend_on_referenced_packages/vendor/private_dep/private_dep.dart, test_data/integration/depend_on_referenced_packages/vendor/public_dep/public_dep.dart, test_data/integration/depend_on_referenced_packages/vendor/transitive_dep/transitive_dep.dart
I realized last night this would trigger for the current package as well, which we definitely don't want 🤣 .
This fixes that, and also makes the tests a bit more robust by ensuring we don't lint for any lines with `// OK` in them.
Also fixes some new unnecessary import lints (this lint now triggers for imports that don't expose anything not exposed already by another import).
=> fix depend_on_referenced_packages lint to allow imports of the current package

lib/src/rules/prefer_interpolation_to_compose_strings.dart, test_data/rules/prefer_interpolation_to_compose_strings.dart
`prefer_interpolation_to_compose_strings` should apply only if the left operand has a `String` type.
Fixes #792
=> prefer_interpolation_to_compose_strings should apply only for String.+

lib/src/rules/avoid_types_as_parameter_names.dart, pubspec.yaml, test_data/rules/avoid_types_as_parameter_names.dart
See https://buganizer.corp.google.com/issues/188405800 for the full context.
Once this lands everywhere, I will able to revert https://dart-review.googlesource.com/c/sdk/+/200280.
=> Don't report avoid_types_as_parameter_names for FieldFormalParameterElement.

lib/src/rules/unsafe_html.dart
I want to remove `SecurityLintCodeWithUniqueName`.
=> Use SecurityLintCode instead of deprecated SecurityLintCodeWithUniqueName

lib/src/rules/library_private_types_in_public_api.dart
Fixes a typo on the documentation at library_private_types_in_public_api.dart. Check https://dart-lang.github.io/linter/lints/library_private_types_in_public_api.html for the typo.
=> Fix typo on library_private_types_in_public_api.dart

lib/src/rules/unnecessary_parenthesis.dart, test_data/rules/unnecessary_parenthesis.dart
The internal presubmit looks green.
https://test.corp.google.com/ui#id=OCL:375864901:BASE:375864817:1622008515263:e0e91d35&include_skipped=true
=> Report unnecessary_parenthesis when the parent precedence is equal to the expression precedence.

lib/src/rules/unnecessary_parenthesis.dart, test_data/rules/unnecessary_parenthesis.dart
There were failures in https://dart-review.googlesource.com/c/sdk/+/201163
I suspect that this means that precedence in analyzer might be not quite correct, and `(foo.bar).baz` is still something we would like to report. But for now we should just revert, and get back to it later.
=> Revert unnecessary parenthesis equal precedence

tool/machine.dart
Includes `core`, `recommended`, and `effective_dart` in the machine generated JSON file. I'm heavily open to suggestions on alternative names for these :)
Also fetches the badge info in the `main` method in-case this tool is run standalone to make sure the sets are retrieved.
Fixes #2611
=> Include new rule sets in the machine generated rules file

lib/src/rules/directives_ordering.dart, test/integration/directives_ordering.dart, test_data/integration/directives_ordering/match_analyzer_organize_directives/sort.dart, test_data/integration/directives_ordering/match_analyzer_organize_directives/sort_imports_package_and_path.dart
I added the tests I could find in the analyzer about sort ordering--not enough coverage by itself but it's a start.
Unfortunately it looks like we do need a breaking change to the lint. At least, it's not a _new_ breaking change with the last change to the lint, it was there before :)
=> Make `directives_ordering` match "organize imports" in the analyzer.

lib/src/rules/prefer_final_parameters.dart, test_data/rules/prefer_final_parameters.dart
This rule stopped looking for non-final parameters if it found a `final` one causing lints to not be triggered when they should have been. This modification only skips that parameter instead of stopping processing completely.
Fixes #2700
=> Don't stop identifying non-final parameters once a final one is found

lib/src/rules/sort_child_properties_last.dart, test_data/mock_packages/flutter/lib/src/widgets/basic.dart, test_data/rules/sort_child_properties_last.dart
Reverts dart-lang/linter#2648
This change is flagging a number of new violations internally and needs to be investigated (https://github.com/dart-lang/linter/issues/2713).  This revert will unblock the other changes that we want to roll.
/cc @bwilkerson @a14n @jacob314
=> Revert "relax sort_child_properties_last to accept other widget afterward"

CHANGELOG.md, lib/src/rules/use_setters_to_change_properties.dart
Fixes #2430 by reporting lint on the method name, not the entire method node including its doc comment and body.
Also tidy up by renaming a _local_ function to not start with an underscore, as per Effective Dart.
=> Report use_setters_to_change_properties on the method name

CHANGELOG.md, lib/src/ast.dart, lib/src/rules/unnecessary_getters_setters.dart, test_data/rules/unnecessary_getters_setters.dart
A getter or setter which is otherwise unnecessary, but has an annotation should be allowed; the annotation may carry meaning to humans, static analyzers, or code generators
Fixes #2706
=> Allow unnecessary getters and setters with annotations

CHANGELOG.md, lib/src/rules/missing_whitespace_between_adjacent_strings.dart, test_data/rules/missing_whitespace_between_adjacent_strings.dart
This lint rule was too strict on adjacent strings that start or end with interpolations. Since it cannot know anything about string interpolations, it should treat them as "valid" (containing whitespace).
Fixes #2489 
Also:
* change helper functions to extension methods; let me know if this is undesirable
* update comments to format like sentences, as per [Effective Dart](https://dart.dev/guides/language/effective-dart/documentation#do-format-comments-like-sentences).
=> Allow interpolations on adjacent strings

CHANGELOG.md, lib/src/ast.dart, test_data/rules/unnecessary_getters_setters.dart
Assignments other than `=` are allowable in setters, like `??=` or `+=`.
Fixes #2402 
Also updates related doc comments to use Markdown code blocks with language tags; dartdoc started warning about code blocks which don't use language tags recently.
=> Update unnecessary_getters_setters to allow for non-basic assignments

CHANGELOG.md, lib/src/rules/unnecessary_overrides.dart, test_data/rules/unnecessary_overrides.dart
Update `unnecessary_overrides` to allow overrides with a doc comment only if they are abstract.
Also tidy comments to format like sentences.
Fixes #2277
=> allow overrides with a doc comment only if they are abstract

lib/src/rules/missing_whitespace_between_adjacent_strings.dart, test_data/rules/missing_whitespace_between_adjacent_strings.dart
This involves a sizeable refactor; I pushed most of the logic of whether a
StringLiteral ends with, starts with, or contains whitespace into extensions on
StringLiteral. I think this makes a lot of sense; they're all getters that
return information about the instance.
Fixes a bug that @pq found.
This is slightly more performant; string literals that do start with whitespace or end with whitespace are not iterated.
=> Fix missing_whitespace_between_adjacent_strings handling of no-whitespace strings

lib/src/rules/use_full_hex_values_for_flutter_colors.dart, test_data/rules/use_full_hex_values_for_flutter_colors.dart
If you use an uppercase 'X' in the hexadecimal prefix, it gives a false positive.
=> Fixed false positive use_full_hex_values_for_flutter_colors

CHANGELOG.md, lib/src/rules/unnecessary_overrides.dart, test_data/rules/unnecessary_overrides.dart
Reverts dart-lang/linter#2723
This flags a bunch of new places in flutter which suggests some more ecosystem impact.  The rub is that the message should indicate the rationale from https://github.com/dart-lang/linter/issues/2277 and the remedy (make the method abstract).  We should also consider updating the quick-fix to make methods abstract where appropriate.
=> Revert "allow overrides with a doc comment only if they are abstract"

lib/src/rules/missing_whitespace_between_adjacent_strings.dart, test_data/rules/missing_whitespace_between_adjacent_strings.dart
Fix a typo in missing_whitespace_between_adjacent_strings which causes false positives.
Fixes an issue that @pq found.
=> Correct typo in missing_whitespace_between_adjacent_strings

tool/canonical/gh_labels.dart, tool/canonical/readme.md
A tool I wrote to help shore up unlabeled github issues.
Emits output like:
```
https://github.com/dart-lang/linter/issues/2732 => set: effective_dart
https://github.com/dart-lang/linter/issues/2731 => set: effective_dart
https://github.com/dart-lang/linter/issues/2713 => set: pedantic
https://github.com/dart-lang/linter/issues/2708 => set: pedantic
https://github.com/dart-lang/linter/issues/2708 => set: effective_dart
https://github.com/dart-lang/linter/issues/2678 => set: effective_dart
https://github.com/dart-lang/linter/issues/2673 => set: effective_dart
https://github.com/dart-lang/linter/issues/2670 => set: effective_dart
https://github.com/dart-lang/linter/issues/2636 => set: effective_dart
https://github.com/dart-lang/linter/issues/2626 => set: pedantic …
```
=> gh label query tool

lib/src/rules/directives_ordering.dart
Also switches import mentions from quotes to inline code blocks
Codeblock issue discovered here: https://github.com/dart-lang/site-www/pull/3372
@pq Can you regenerate gh-pages after this change makes it in? Thanks!
=> Fix unclosed code block in directives_ordering details

lib/src/rules/avoid_classes_with_only_static_members.dart, test_data/rules/avoid_classes_with_only_static_members.dart
=> fix `avoid_classes_with_only_static_members` to flag classes with only methods

lib/src/rules/avoid_function_literals_in_foreach_calls.dart, test_data/rules/avoid_function_literals_in_foreach_calls.dart
Fixes #https://github.com/dart-lang/linter/issues/2751
=> skip nullable iterables in `avoid_function_literals_in_foreach_calls`

doc/WritingLints.MD
Correct a sentence in `WritingLints`.
`either` is usually followed by `or`, and it seems the sentence is better without it.
=> Remove a word from documentation.

CHANGELOG.md, lib/src/util/dart_type_utilities.dart, pubspec.yaml
As there error [here](https://github.com/dart-lang/linter/pull/2771/checks?check_run_id=3078290090), we need to use `CompilationUnitElement`.`classes` instead of `types` and this is not existing in `analyzer` `1.7.0`
Needed for any upcoming PR, including #2771
=> analyzer 2.0.0

AUTHORS
Thanks a lot.
Fixes #2765.
Another point: I guess `Ivan Tugay` should be before `Danny Tuppeny`, since I understand names are sorted by last name.
=> + asashour

lib/src/rules/avoid_dynamic_calls.dart
https://dart-review.googlesource.com/c/sdk/+/207360 improved the
analyzer by making CompoundAssignmentExpression a subtype of
Expression; this means that once a version of the analyzer is
published with this improvement, and the linter can depend on that
version, it will be possible to promote from Expression to
CompoundAssignmentExpression (and the linter will be able to remove a
cast).  Until then, the cast is still required to work with older
analyzers, but will trigger an "unnecessary cast" warning when
analyzing against the newest analyzer.
So for now we ignore the "unnecessary cast" warning.  Once the linter
depends on a later version of the analyzer, we'll be able to clean
this up.
=> Ignore unnecessary cast warning.

lib/src/utils.dart, test/utils_test.dart
Fixes #2790
`isValidDartIdentifier` rejects keywords too which is too restrictive for package names.
/cc @natebosch @bwilkerson
=> allow keywords for dart package_names

lib/src/rules/prefer_is_not_empty.dart
Improves performance a bit and is a little tidier (note the use of `unParenthesized`).
Benchmark runs:
**before:**
-----------------------------------------------------------------------------
Timings                                                                    ms
-----------------------------------------------------------------------------
prefer_is_not_empty [core, pedantic]                                       23
**after:**
prefer_is_not_empty [core, pedantic]                                        2
([Task link](https://github.com/dart-lang/linter/pull/2796/checks?check_run_id=3147906276).)
🔥 
=> migrate `prefer_is_not_empty` from visitSimpleIdentifier to more specific visitPrefixEpression

lib/src/rules/annotate_overrides.dart
* avoid unnecessary calls to `getOverriddenMember`
* remove unused node visit registration
=> `annotate_overrides` perf fixes

lib/src/rules/prefer_void_to_null.dart
Improves perf a bit.
Benchmark runs:
**before:**
-----------------------------------------------------------------------------
Timings                                                                    ms
-----------------------------------------------------------------------------
prefer_void_to_null [recommended]                                          14
**after:**
prefer_void_to_null [recommended]                                           7
=> stop visiting simple identifiers in `prefer_void_to_null`

lib/src/rules/use_rethrow_when_possible.dart, test_data/rules/use_rethrow_when_possible.dart
Fixes #2789
I don't know how to have a compilable case with `return i ?? throw e;`
=> Fix false positive in `use_rethrow_when_possible`

test/rule_test.dart
Since #909 is accepted as a bug, then the `ignore` should be removed once the issue is fixed.
=> Add TODO to remove an `ignore` once an issue is fixed

lib/src/rules/avoid_renaming_method_parameters.dart, test/integration/avoid_renaming_method_parameters.dart
Related to the message description of #2683 
Dart `fix` to be separately handled.
=> Better lint messages for `avoid_renaming_method_parameters`

lib/src/rules/void_checks.dart, test_data/rules/void_checks.dart
Fixes #2813
I feel it may need further refactoring, since the condition is very similar to the one next:
```dart
if (expectedType.isVoid && !isTypeAcceptableWhenExpectingVoid(type)) {
```
but I am not sure.
=> Fix `void_checks` for a compiler error case

lib/src/rules/prefer_initializing_formals.dart, test_data/rules/prefer_initializing_formals.dart
=> skip factory constructors when checking `prefer_initializing_formals`

lib/src/rules/prefer_void_to_null.dart, test_data/rules/prefer_void_to_null.dart
Fixes #https://github.com/dart-lang/linter/issues/2792
=> fix `prefer_void_to_null` false positive on overriding returns

test_data/rules/void_checks.dart
It looks like @asashour's recent fix addresses #2794 as well.
This adds a test to validate.
Closes #2794
=> test case for fixed `void_checks` false positive

lib/src/rules/avoid_dynamic_calls.dart
Fixes #2666
/cc @srawlins @bwilkerson 
/fyi @devoncarew @matanlurey
=> mark `avoid_dynamic_calls` stable

analysis_options.yaml, lib/src/rules/avoid_renaming_method_parameters.dart, lib/src/util/ascii_utils.dart, test/integration/depend_on_referenced_packages.dart
~~No need to ignore `prefer_single_quotes`. It is not part of the checked lints in the project.~~
Enable `prefer_single_quotes`, as per the below feedback.
=> Enable `prefer_single_quotes`

test/mocks.dart
Follow-up from https://github.com/dart-lang/linter/pull/2865.
Remove another unused and fragile mock class.
=> remove unused `MockRule`

lib/src/rules/use_build_context_synchronously.dart, test/integration/use_build_context_synchronously.dart, test_data/integration/use_build_context_synchronously/lib/unmigrated.dart
There are false positives when writing awaits inside anonymous functions defined above.
Fixes #2878
PS: First time contributing to the linter so I may be taking wrong assumptions here, but this works for the false positive cases I've encountered.
=> Fix false positive in `use_build_context_synchronously`

lib/src/rules/always_specify_types.dart
Migrate from deprecated `aliasElement`.
=> prefer `alias` over `aliasElement`

lib/src/ast.dart, lib/src/utils.dart
Some of the current RegExps in `utils.dart` risk [catastrophic backtracking](https://swtch.com/~rsc/regexp/regexp1.html), which allows [denial of service attacks](https://en.wikipedia.org/wiki/ReDoS).
This change should fix those RegExps to guarantee nominally linear execution,
and generally clean up unnecessary complexity.
See: https://github.com/dart-lang/linter/issues/2803
The change should not alter the behavior of the RegExps other than where it's deliberately chosen to fix the linked issue, or where the current behavior is clearly erroneous. But do check that there are not further errors.
The change also attempts to define, in words, what each RegExp is supposed to match.
Fixes #2803
=> Improve RegExps.

lib/src/rules/hash_and_equals.dart
> Using `is` in `operator ==` is usually wrong as it makes the `==` operator asymmetric.
https://github.com/dart-lang/sdk/issues/36004#issuecomment-557958476
I based my early `==` overrides on the `hash_and_equals` docs, so I'm sure others have done the same
=> Recommend using runtimeType in hash_and_equals

test_data/rules/experiments/constructor_tearoffs/rules/always_specify_types.dart
Follow-up from #2693.
See also: #2914.
(FWIW: waiting to address TODOs until a new push of analyzer since ASTs are in flux.)
=> test updates for `always_specify_types` w/ constructor tear-offs

tool/rule.dart
=> make outdir optional

test_data/rules/experiments/constructor_tearoffs/rules/prefer_const_declarations.dart
Fixes #2911
It looks like some cases are not covered (commented out) and I think these are constant evaluation issues and so should be tracked maybe in analyzer? (FYI @scheglov.)
=> constructor tear-off tests for `prefer_const_declarations`

lib/src/rules/unnecessary_parenthesis.dart, test_data/rules/experiments/constructor_tearoffs/rules/unnecessary_parenthesis.dart
=> constructor tearoff support for `unnecessary_parenthesis`

lib/src/rules/unnecessary_lambdas.dart, test_data/rules/experiments/constructor_tearoffs/rules/unnecessary_lambdas.dart
=> constructor tear-off support for `unnecessary_lambdas`

lib/src/rules/prefer_initializing_formals.dart
=> Fix doc typo "enabled"

lib/src/rules/always_declare_return_types.dart
Quote function name in always_declare_return_types
Addresses the second point in https://github.com/dart-lang/sdk/issues/47142.
=> Quote function name in always_declare_return_types

lib/src/rules/unnecessary_parenthesis.dart, test_data/rules/unnecessary_parenthesis.dart
Fixes #https://github.com/dart-lang/linter/issues/2944
=> fix `unnecessary_parenthesis` false positive for function expressions

test_data/rules/prefer_const_declarations.dart
The next analyzer release will allow for top-level and static function tearoffs to be const. This means this test data file has one new LINT inside, where indicated.
Instead of merging this PR by itself, the diff can just be used in a PR which bumps analyzer.
=> Prepare const static function tearoff test for analyzer roll

lib/src/rules/use_build_context_synchronously.dart, test_data/rules/use_build_context_synchronously.dart
Handle a few patterns found in internal testing.
=> control flow improvements for use_build_context_synchronously

lib/src/rules/unnecessary_brace_in_string_interps.dart
In `unnecessary_brace_in_string_interps.dart`, there is an extra `^`, which doesn't add a value, since the `identifierPart` is used only once in `startsWith()`.
This PR removes, as also hinted in https://dart-review.googlesource.com/c/sdk/+/212742/comments/e3e4560f_28eca233
Also, no need to have the starting as `raw`.
=> Remove unnecessary `begin of input` and raw string from `identifierPart`

pubspec.yaml, test/all.dart, test/rule_test_support.dart, test/rules/all.dart, test/rules/analysis_options.yaml, test/rules/avoid_init_to_null.dart, test_data/rules/experiments/nnbd/rules/avoid_init_to_null.dart
Fixes #2974
Extracts a set of tests with diagnostics (`avoid_init_to_null` -- see: #2969).
=> in-memory reflective test harness

test/rule_test_support.dart, test/rules/all.dart, test/rules/overridden_fields.dart, test_data/rules/overridden_fields.dart
See: #2969
Diagnostics matching API can evolve and certainly the air-lifted test source should be revisited at some point...  (So many errors -- all the more value in this work!)
=> add support for asserting diagnostics && migrate `overridden_fields`

test/rule_test_support.dart, test/rules/all.dart, test/rules/avoid_function_literals_in_foreach_calls.dart, test/rules/avoid_init_to_null.dart, test/rules/missing_whitespace_between_adjacent_strings.dart, test/rules/overridden_fields.dart, test/rules/prefer_asserts_in_initializer_lists.dart, test/rules/prefer_const_constructors_in_immutables.dart, test/rules/prefer_contains.dart, test/rules/prefer_spread_collections.dart, test/rules/type_init_formals.dart, test/rules/void_checks.dart, test_data/rules/experiments/nnbd/rules/type_init_formals.dart, test_data/rules/experiments/nnbd/rules/unrelated_type_equality_checks.dart, test_data/rules/missing_whitespace_between_adjacent_strings.dart, test_data/rules/prefer_collection_literals.dart, test_data/rules/prefer_initializing_formals.dart
=> more test diagnostic cleanup

lib/src/rules/unawaited_futures.dart
`unwaited` is now present in the `dart:async` package.
=> unawaited is present in dart:async

test/rules/all.dart, test/rules/prefer_generic_function_type_aliases.dart, test/rules/super_goes_last.dart, test/rules/unnecessary_null_checks.dart, test_data/rules/avoid_equals_and_hash_code_on_mutable_classes.dart, test_data/rules/avoid_redundant_argument_values.dart, test_data/rules/avoid_relative_lib_imports.dart, test_data/rules/experiments/nnbd/rules/overridden_fields.dart, test_data/rules/experiments/nnbd/rules/unnecessary_null_checks.dart, test_data/rules/no_logic_in_create_state.dart, test_data/rules/prefer_generic_function_type_aliases.dart
=> Test diagnostic cleanup

test/rule_test.dart
I would like to remove it.
You always want to go through `AnalysisContextCollection`, which discovers the pertinent analysis options file.
Even in tests. It is a question of configuring the file system, the actual, or in-memory, or overlay.
=> Stop using FeatureSet.forTesting()

example/all.yaml, lib/src/rules.dart, lib/src/rules/sized_box_for_whitespace.dart, lib/src/rules/sized_box_shrink_expand.dart, lib/src/util/flutter_utils.dart, test_data/mock_packages/flutter/lib/src/widgets/basic.dart, test_data/rules/sized_box_shrink_expand.dart
Hey @pq,
This is the start of a lint for `SizedBox.shrink(...)` and `SizedBox.expand(...)`. When finished, this will fix https://github.com/dart-lang/linter/issues/2072. I'm using https://github.com/dart-lang/linter/pull/2049 as the starting point. 
However, I'm hitting an issue with `double.infinity` and I can't see how to patch it into the mock_packages.
```console
$ dart test -N sized_box_shrink_expand
00:03 +0 -1: test/rule_test.dart: rule dart sized_box_shrink_expand [E]                                                                                                        
Unexpected diagnostics:
test_data/rules/sized_box_shrink_expand.dart 55:20 The getter 'infinity' isn't defined for the type 'double'.
test_data/rules/sized_box_shrink_expand.dart 23:19 The getter 'infinity' isn't …
```
=> Lint for `SizedBox.shrink(...)` and `SizedBox.expand(...)`

AUTHORS, example/all.yaml, lib/src/rules.dart, lib/src/rules/use_decorated_box.dart, test_data/mock_packages/flutter/lib/painting.dart, test_data/mock_packages/flutter/lib/src/painting/box_decoration.dart, test_data/rules/use_decorated_box.dart
Use `DecoratedBox` over `Container` when only `Decoration` is specified.
Fixes https://github.com/dart-lang/linter/issues/3060
Style advice.
```dart
Widget buildArea() {
return Container(
decoration: const BoxDecoration(
color: Colors.blue,
borderRadius: BorderRadius.all(
Radius.circular(5),
),
),
child: const Text('...'),
);
}
```
```dart
Widget buildArea() {
return const DecoratedBox(
decoration: BoxDecoration(
color: Colors.blue,
borderRadius: BorderRadius.all(
Radius.circular(5),
),
),
child: Text('...'),
);
}
```
=> `use_decorated_box`

test/rules/super_goes_last.dart
See: https://github.com/dart-lang/linter/issues/3069.
=> prep for rename of CompileTimeErrorCode.INVALID_SUPER_INVOCATION

lib/src/rules/missing_whitespace_between_adjacent_strings.dart
Noted in discussions at https://github.com/dart-lang/linter/pull/3080#discussion_r761283802.
@bwilkerson
=> Change missing_whitespace_between_adjacent_strings to use SimpleAstVisitor

lib/src/rules/avoid_redundant_argument_values.dart, test/rules/all.dart, test/rules/avoid_redundant_argument_values.dart
=> `avoid_redundant_argument_values` support for `named-arguments-anywhere`

lib/src/rules/pub/secure_pubspec_urls.dart, test/integration/secure_pubspec_urls.dart, test_data/integration/secure_pubspec_urls/pubspec.yaml
Fixes `only only` :rofl: 
Adds checks for:
* `repository`
* `issue_tracker`
/cc @sigurdm
------------
Also noticed bug in analyzer wrt. to handling of git references, will fix that separately.
=> Fix secure_pubspec_urls lint, and check `issue_tracker` and `repository`

lib/src/rules/prefer_initializing_formals.dart
=> `prefer_initializing_formals`: add note on stricter param typing

example/all.yaml, lib/src/rules.dart, lib/src/rules/unnecessary_late.dart, test_data/rules/unnecessary_late.dart
Adds a new `unnecessary_late` lint which will detect usages of the late modifier `late` on static and top-level variables which are evaluated as if they are marked with `late` already.
I believe there are other situations where `late` may be unnecessary. The first that comes to mind is in a local variable declaration where the initializer will have no side effects. I have opted to not account for this and potential other  more complicated situations currently(unless I'm missing something obvious). I was thinking other situations could be incorporated into this lint in the future, **but if you think this** should have a more specific name such `unnecessary_static_late`, let me know :)
=> Add a new `unnecessary_late` lint

CHANGELOG.md, lib/src/rules/no_leading_underscores_for_local_identifiers.dart, test_data/rules/no_leading_underscores_for_local_identifiers.dart
Fixes a false positive in the common case:
```dart
try {
...
} catch (_) {
...  
}
```
=> `no_leading_underscores_for_local_identifiers`: allow underscores in catch clauses

lib/src/analyzer.dart
The analyzer cannot (yet!) detect unused "exports" in an implementation library (any directory other than `lib/`). But by my mighty "delete, analyze, undo" strategy, I found these unused exports.
=> Tidy the analyzer exports used in linter

lib/src/rules/exhaustive_cases.dart, lib/src/util/dart_type_utilities.dart, test_data/rules/exhaustive_cases.dart
This adds some logic to DartTypeUtilities.asEnumLikeClass (IMHO this is begging to be an extension on ClassElement :D ) to account for equal-valued fields.
We store each field (enum-like value) in a mapping keyed to the field's constant value. Then only need to have a case for each constant value.
Fixes #3017
=> enum-like: Account for equal-valued fields if one is deprecated

lib/src/rules/prefer_contains.dart
prefer_contains is the slowest "recommended" rule, and the 6th slowest rule overall (according to a recent CI benchmark). This PR should speed it up. Before this PR, the broad algorithm is:
For every binary expression:
1. If the right operand is an int:
1. and if the left operand is an invocation of `indexOf`:
1. and the value of the int combined with the operator should be linted, report lint.
2. Else, if the left operand is an int:
1. and the right operand is an invocation of `indexOf`:
1. and the value of the int combined with the operator should be linted, report lint.
I decided this was inefficient in two spots:
1. The algorithm doesn't check the operator until the innermost steps, after which other more expensive computation has been done.
2. The algorithm doesn't check whether an …
=> prefer_contains: short circuit more

lib/src/rules/directives_ordering.dart, lib/src/rules/no_duplicate_case_values.dart, lib/src/rules/prefer_contains.dart, lib/src/rules/prefer_is_empty.dart
This removes unnecessary subclasses of `LintCode` by using static fields instead. I think this is a better approach to having custom messages.
=> Remove subclasses of LintCode

lib/src/rules/prefer_function_declarations_over_variables.dart, test_data/rules/prefer_function_declarations_over_variables.dart
This rule should not be reported for fields or for top-level variables which can be re-assigned (non-final).
Fixes https://github.com/dart-lang/linter/issues/1628
=> Do not report prefer_function_declarations_over_variables for non-final fields

lib/src/rules/always_specify_types.dart, lib/src/rules/avoid_unused_constructor_parameters.dart, lib/src/rules/empty_catches.dart, lib/src/rules/no_leading_underscores_for_local_identifiers.dart, lib/src/rules/non_constant_identifier_names.dart, lib/src/rules/type_annotate_public_apis.dart, lib/src/util/ascii_utils.dart, lib/src/utils.dart, test/ascii_utils_test.dart
isOnlyUnderscores is used in a few lint rules, including non_constant_identifier_names, which is the 2nd slowest core lint rule, and 8th slowest overall (according to a recent CI benchmark).
The idea here is simple, though unvetted by me in Dart: the regular expression engine may be heavy to fire up, so instead just do a simple character walk.
=> Reimpliment isOnlyUnderscores with a loop

lib/src/rules/camel_case_types.dart, test_data/rules/camel_case_types.dart
Effective dart [mentions](https://dart.dev/guides/language/effective-dart/style#do-name-types-using-uppercamelcase) that enum names must be camel-cased. This PR adds that according to the discussion on #3091 .
Fixes #3091
=> Make camel_case_types cover enums

lib/src/rules/unnecessary_late.dart, test_data/rules/unnecessary_late.dart
Previously the `unnecessary_late` lint triggered on the whole variable declaration range, which was a bit confusing, particularly in a list of declarations. Now the lint reports on just the name. I've also avoided looping if the list is not marked `late`.
=> Improve unnecessary_late to target variable name

lib/src/rules/avoid_unused_constructor_parameters.dart, test/rules/all.dart, test/rules/avoid_unused_constructor_parameters.dart
=> super param support for `avoid_unused_constructor_parameters`

test/rules/all.dart, test/rules/avoid_types_as_parameter_names.dart
=> super_parameters test for `avoid_types_as_parameter_names`

lib/src/rules/avoid_annotating_with_dynamic.dart, lib/src/rules/tighten_type_of_initializing_formals.dart, test/rules/all.dart, test/rules/avoid_annotating_with_dynamic.dart, test/rules/tighten_type_of_initializing_formals.dart
=> super_parameters support for `tighten_type_of_initializing_formals`

lib/src/rules/avoid_annotating_with_dynamic.dart, test/rules/avoid_annotating_with_dynamic.dart
=> add support for field formals to `avoid_annotating_with_dynamic`

lib/src/rules/type_init_formals.dart
=> add super initializer example

test/rules/all.dart, test/rules/unnecessary_overrides.dart
See: #3090
/fyi @scheglov for test failure context (see stacktrace in #3090)
=> enhanced enums tests for `unnecessary_overrides`

lib/src/rules/avoid_returning_this.dart, test/rules/all.dart, test/rules/avoid_returning_this.dart
=> enhanced enum support for `avoid_returning_this`

lib/src/rules/type_init_formals.dart
Add text to address #3214
Fixes #3214
It appears that the spelling "OK" is the most common in this package.
=> Add improved text for type_init_formals

lib/src/rules/always_use_package_imports.dart, lib/src/rules/avoid_relative_lib_imports.dart
See https://github.com/dart-lang/linter/pull/3225#issuecomment-1036306676.
@pq @bwilkerson
=> Add a note above how always_use_package_imports and avoid_relative_lib_imports complement each other

lib/src/rules/avoid_equals_and_hash_code_on_mutable_classes.dart, test/rules/all.dart, test/rules/avoid_equals_and_hash_code_on_mutable_classes_test.dart
See: https://github.com/dart-lang/linter/issues/3094
=> enhanced enum support for `avoid_equals_and_hash_code_on_mutable_classes`

AUTHORS, lib/src/rules/avoid_print.dart
The existing message gave no hint on what to do *instead* of using
print calls, so this gives an explanation and a few examples.
Fixes #2787
=> Improve description & example for avoid_print

lib/src/rules/sort_constructors_first.dart, test/rules/all.dart, test/rules/sort_constructors_first.dart
=> enhanced enum support for `sort_constructors_first`

lib/src/rules/sort_constructors_first.dart, lib/src/rules/sort_unnamed_constructors_first.dart
Benchmarking is showing pretty measurable improvements.
Before:
```
#62 sort_constructors_first                                                    12
#122 sort_unnamed_constructors_first                                            5
```
After:
```
#124 sort_constructors_first                                                    6
#172 sort_unnamed_constructors_first                                            3
```
🎉 🎉 🎉 
Cheers for the catch Brian!
=> stop (needlessly) (re)sorting member ast nodes

example/all.yaml, lib/src/rules.dart, lib/src/rules/use_colored_box.dart, test_data/rules/use_colored_box.dart
Use `ColoredBox` over `Container` when only the `Color` is specified.
Addresses https://github.com/flutter/flutter/issues/90722 and https://github.com/dart-lang/linter/issues/3255
Style advice.
```dart
Widget buildArea() {
return Container(
color: Colors.blue,
child: const Text('...'),
);
}
```
```dart
Widget buildArea() {
return const ColoredBox(
color: Colors.blue,
child: Text('...'),
);
}
```
=> Add `use_colored_box`

example/all.yaml, lib/src/rules.dart, lib/src/rules/use_super_initializers.dart, test/rules/all.dart, test/rules/use_super_initializers_test.dart
=> + use_super_initializers

lib/src/rules/use_super_initializers.dart, test/rules/use_super_initializers_test.dart
Updates to move the diagnostic range from individual identifiers to the constructor node.
/fyi @jacob314 
=> use_super_initializers: report diagnostic on constructor node

lib/src/rules/always_specify_types.dart
In some circumstances, the analyzer doesn't reliably set
DartType.alias to point to the type alias that led to a type.  (This
is the ultimate cause of #3275).  I'm currently researching whether
it's possible to improve the analyzer behavior in this regard.  In the
meantime, we can fix #3275 by changing the linter to grab the type
alias element directly from NamedType.name.staticElement.
Fixes #3275.
=> For `always_specify_types`, use NamedType.name.staticElement in favor of DartType.alias.

CHANGELOG.md, example/all.yaml, lib/src/rules.dart, lib/src/rules/use_super_parameters.dart, lib/src/version.dart, pubspec.yaml, test/rules/all.dart, test/rules/use_super_parameters_test.dart
=> rename `use_super_initializers` to `use_super_parameters`

lib/src/rules/use_enums.dart
=> fix `use_enum` doc examples

lib/src/rules/prefer_for_elements_to_map_fromIterable.dart
Added the rationale behind this lint. Also another example that doesn't rely on Flutter, and attempts to show how the alternative can be used to good effect.
Fixes #3259
=> Add rationale & example to prefer_for_elements_to_map_fromIterable

lib/src/rules/unnecessary_null_checks.dart
The roll for 1.21.0 is blocked due to a newly flagged `unnecessary_non_null_assertion`.
```
ERROR: third_party/dart/linter/lib/src/rules/unnecessary_null_checks.dart
45: parent = parent!.parent; The '!' will have no effect because the receiver can't be null. #unnecessary_non_null_assertion
```
https://fusion2.corp.google.com/invocations/07bd1269-3e54-4ec1-ad8e-1b3b4ca53809/targets/%2F%2Fthird_party%2Fdart%2Fanalyzer:analyzer_tests_src_fasta_recovery_partial_code_method_declaration_test/log
This swizzles the flow around to sidestep this skew between HEAD and the latest published analyzer.
=> work around upcomming flow-analysis improvements

lib/src/cli.dart, lib/src/rules/unnecessary_null_checks.dart, pubspec.yaml
Follow-up from: https://github.com/dart-lang/linter/commit/d1de2e9f4a3cdfc7a44a787905781eb6fa08d532
=> bump language lower-bound to 2.15

test_data/rules/experiments/super_parameters/rules/use_key_in_widget_constructors.dart
See: https://github.com/dart-lang/linter/issues/3296
**TL;DR** this test is blocking a Google3 roll. 😬 
=> disable `use_key_in_widget_constructors` test

lib/src/rules/use_super_parameters.dart, test/rules/use_super_parameters_test.dart
See: #3306
(Addresses case 1.)
=> fix `use_super_parameters` false positive passing named params as positional

lib/src/rules/depend_on_referenced_packages.dart, test_data/integration/depend_on_referenced_packages/_packages, test_data/integration/depend_on_referenced_packages/lib/public.dart
Fixes #3308
/cc @bwilkerson @jakemac53 
/fyi @goderbauer
=> update `depend_on_referenced_packages` to skip `flutter_gen`

lib/src/rules/unnecessary_getters_setters.dart
Fix a "where is ..." predicate that could be a `whereType<T>`.
=> migrate to `whereType`

lib/src/rules/unsafe_html.dart, test_data/rules/unmocked/unsafe_html.dart, test_data/rules/unsafe_html.dart
This used to be dangerous because of img.src = 'javascript:hack' but browsers don't allow this anymore. We allow it in all other languages.
=> [unsafe_html] Allow assigning to img.src.

lib/src/rules/require_trailing_commas.dart, test_data/rules/require_trailing_commas.dart
This PR prevents `require_trailing_commas` to trigger on asserts with function like the following one:
```dart
assert(() {
_debugIsRenderViewInitialized = true;
return true;
}());
```
=> handle functions in asserts for require_trailing_commas

lib/src/rules/require_trailing_commas.dart, test_data/rules/require_trailing_commas.dart
This PR prevents `require_trailing_commas` to trigger on multiline-strings like the following one:
```dart
print('''
--help      Print a usage message.
--temp-dir  A location where temporary files may be written. Defaults to a
directory in the system temp folder. If a temp_dir is not
specified, then the default temp_dir will be created, used, and
removed automatically.
''');
```
=> handle multiline-strings in require_trailing_commas

lib/src/rules/always_require_non_null_named_parameters.dart, lib/src/rules/cascade_invocations.dart, lib/src/rules/prefer_constructors_over_static_methods.dart, lib/src/rules/unnecessary_lambdas.dart, test/engine_test.dart
These will be flagged by the next linter release which updates `non_constant_identifier_names` to flag local functions.
See:
* https://github.com/flutter/flutter/pull/102615
* https://dart-review.googlesource.com/c/sdk/+/242391
* dart-lang/linter#3360
=> rename local functions with `_`s

README.md, pubspec.yaml
- rev the min. dep on package:args
- add an additional markdown badge to the readme
`package:args` `2.1.0` introduced a new `mandatory` named param to one of it's APIs; it looks like linter is using this param; here's the error I saw against package:args 2.0.0 locally:
```
error • tool/rule.dart:21:7 • The named parameter 'mandatory' isn't defined. Try correcting the name to an
existing named parameter's name, or defining a named parameter with the name 'mandatory'. •
undefined_named_parameter
```
=> rev the min. dep on package:args

lib/src/rules/use_key_in_widget_constructors.dart, test_data/rules/use_key_in_widget_constructors.dart
=> `use_key_in_widget_constructors` to report at the constructor `name` or `returnType`

.github/workflows/build.yaml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
=> chore: Set permissions for GitHub actions

lib/src/rules/directives_ordering.dart
=> remove `DartProject` references

example/all.yaml, lib/src/rules.dart, lib/src/rules/unnecessary_to_list_in_spreads.dart, test_data/rules/unnecessary_to_list_in_spreads.dart
Unnecessary `toList()` in spreads.
**BAD:**
```dart
children: <Widget>[
...['foo', 'bar', 'baz'].map((String s) => Text(s)).toList(),
]
```
**GOOD:**
```dart
children: <Widget>[
...['foo', 'bar', 'baz'].map((String s) => Text(s)),
]
```
Fixes #2965
=> add unnecessary_to_list_in_spreads

lib/src/rules/prefer_initializing_formals.dart
Our [benchmark bot](https://github.com/dart-lang/linter/runs/6532600308?check_suite_focus=true), while not rigorous, does suggest a significant improvement.
Before:
After:
Note that this is a recommended lint so *any* improvement will be felt by lots of folks.
/cc @srawlins @scheglov @bwilkerson
=> `prefer_initializing_formals` iteration optimizations

lib/src/rules/prefer_const_constructors_in_immutables.dart
Another wee optimization on a `flutter` recommended lint.  (Some context in https://github.com/dart-lang/sdk/issues/32102.)
[BEFORE](https://github.com/dart-lang/linter/runs/6497647704?check_suite_focus=true):
[AFTER](https://github.com/dart-lang/linter/runs/6532900300?check_suite_focus=true):
A pretty significant improvement!
/cc @srawlins @scheglov @bwilkerson 
/fyi @goderbauer
=> `prefer_const_constructors_in_immutables`: optimize out sync* and extra iteration

lib/src/rules/avoid_redundant_argument_values.dart, test/rules/avoid_redundant_argument_values_test.dart
See: #3447
I think the constant evaluator should be returning `hasKnownValue == false` in this repro test?
=> failing test for unknown constant value

lib/src/rules/prefer_final_locals.dart, test_data/rules/prefer_final_locals.dart
`prefer_final_locals` should trigger only if all variables in the declaration list can be final.
Related to #3444
=> prefer_final_locals: handling of declaration list

lib/src/rules/avoid_multiple_declarations_per_line.dart, test_data/rules/avoid_multiple_declarations_per_line.dart
`avoid_multiple_declarations_per_line` shouldn't apply in for declaration list.
Fixes #2543
Related to #3444
=> avoid_multiple_declarations_per_line: handling of for

CHANGELOG.md, lib/src/rules/unnecessary_parenthesis.dart, lib/src/version.dart, pubspec.yaml, test_data/rules/unnecessary_parenthesis.dart
Check for Sets and Maps at start of expression statements broadly.
Fixes #3474
=> Check for Set/Maps at start of expr statements broadly

lib/src/rules/use_colored_box.dart, lib/src/rules/use_decorated_box.dart, test_data/rules/use_colored_box.dart, test_data/rules/use_decorated_box.dart
A `Container` without child (and without constraint) will [introduce a LimitedBox in the tree](https://github.com/flutter/flutter/blob/160e0712a8bb6f2d10dfca703c91e60d0e0a0c5e/packages/flutter/lib/src/widgets/container.dart#L386-L391). So it is not correct in the code in description to replace the Container with a DecoratedBox.
This PR requires a `child` parameter to be specified to trigger. This will prevent false positives.
Fixes #3479, #3344
=> trigger use_decorated_box and use_colored_box only with child

example/all.yaml, lib/src/rules.dart, lib/src/rules/combinators_ordering.dart, test_data/rules/combinators_ordering.dart
**DO** sort combinator names alphabetically.
**BAD:**
```dart
import 'a.dart' show B, A hide D, C;
export 'a.dart' show B, A hide D, C;
```
**GOOD:**
```dart
import 'a.dart' show A, B hide C, D;
export 'a.dart' show A, B hide C, D;
```
Fixes #2785
=> add combinators_ordering

test/all.dart, test/doc_test.dart, tool/doc.dart, tool/machine.dart
See https://github.com/dart-lang/linter/issues/2650.
Sample machine.json output:
```json
{
"name": "always_use_package_imports",
"description": "Avoid relative imports for files in `lib/`.",
"group": "errors",
"maturity": "stable",
"incompatible": [],
"sets": [],
"fixStatus": "hasFix",
"details": "*DO* avoid relative imports for files in `lib/`.\n\nWhen mixing relative and absolute imports it's possible to create confusion\nwhere the same member gets imported in two different ways. One way to avoid\nthat is to ensure you consistently use absolute imports for files withing the\n`lib/` directory.\n\nThis is the opposite of 'prefer_relative_imports'.\n\nYou can also use 'avoid_relative_lib_imports' to disallow relative imports of\nfiles within `lib/` directory outside of it (for example …
```
=> generate fix status documentation

analysis_options.yaml, lib/src/analyzer.dart, lib/src/formatter.dart
(And remove deprecated `invariant_booleans`.)
/fyi @a14n
=> enable `combinators_ordering`

test/integration/avoid_private_typedef_functions.dart, test/integration/avoid_renaming_method_parameters.dart, test/integration/flutter_style_todos.dart, test/integration/lines_longer_than_80_chars.dart, test/integration/secure_pubspec_urls.dart, test/integration/sort_pub_dependencies.dart, test/integration/use_build_context_synchronously.dart
References to descriptions make the messages hard to evolve.
(See related: https://github.com/flutter/flutter/pull/107541.)
(Medium-term, we might consider migrating these to reflective tests: https://github.com/dart-lang/linter/issues/3535)
=> remove descriptions from integration test "goldens"

lib/src/rules/noop_primitive_operations.dart, test_data/rules/noop_primitive_operations.dart
Improve` noop_primitive_operations` to catch `.toString()` in string interpolations.
Related to #3334
=> catch '${x.toString()}' with noop_primitive_operations

test/rule_test_support.dart, test/rules/annotate_overrides_test.dart, test/rules/avoid_annotating_with_dynamic_test.dart, test/rules/avoid_equals_and_hash_code_on_mutable_classes_test.dart, test/rules/avoid_final_parameters_test.dart, test/rules/avoid_init_to_null_test.dart, test/rules/avoid_redundant_argument_values_test.dart, test/rules/avoid_renaming_method_parameters_test.dart, test/rules/avoid_returning_this_test.dart, test/rules/avoid_setters_without_getters_test.dart, test/rules/avoid_shadowing_type_parameters_test.dart, test/rules/avoid_types_as_parameter_names_test.dart, test/rules/avoid_unused_constructor_parameters_test.dart, test/rules/deprecated_consistency_test.dart, test/rules/hash_and_equals_test.dart, test/rules/library_private_types_in_public_api_test.dart, test/rules/prefer_asserts_in_initializer_lists_test.dart, test/rules/prefer_equal_for_default_values_test.dart, test/rules/prefer_final_fields_test.dart, test/rules/prefer_final_parameters_test.dart, test/rules/public_member_api_docs_test.dart, test/rules/sort_constructors_first.dart, test/rules/sort_unnamed_constructors_first.dart, test/rules/tighten_type_of_initializing_formals_test.dart, test/rules/type_init_formals_test.dart, test/rules/unnecessary_overrides_test.dart, test/rules/use_enums_test.dart, test/rules/use_super_parameters_test.dart
A number of reflective tests enable experiments explicitly that are now on by default in our minimum supported SDK.  This change removes those redundant declarations and adds validation to ensure that we don't accrue similar technical debt in the future.
=> ensure reflective tests don't enable default on experiments

lib/src/rules/pub/sort_pub_dependencies.dart
Clarifies a bit what "Sort dependencies" means. When I read about the linter, was this not clear to me what "Sort dependencies" acutely means.
=> Clarify how the dependencies should be sorted when using `sort_pub_dependencies`

doc/RELEASING.md
Adds instructions on updating the dart.dev version of the linter rule documentation as a stop-gap until the process is automated.
Closes https://github.com/dart-lang/linter/issues/3557
=> Update release docs for dart.dev updating instructions

lib/src/rules/use_late_for_private_fields_and_variables.dart, test_data/rules/use_late_for_private_fields_and_variables.dart
=> use_late_for_private_fields_and_variables: handling of enum

lib/src/ast.dart, lib/src/extensions.dart, lib/src/rules/always_require_non_null_named_parameters.dart, lib/src/rules/avoid_init_to_null.dart, lib/src/rules/avoid_null_checks_in_equality_operators.dart, lib/src/rules/avoid_returning_null.dart, lib/src/rules/cascade_invocations.dart, lib/src/rules/invariant_booleans.dart, lib/src/rules/join_return_with_assignment.dart, lib/src/rules/prefer_conditional_assignment.dart, lib/src/rules/prefer_final_fields.dart, lib/src/rules/prefer_foreach.dart, lib/src/rules/prefer_initializing_formals.dart, lib/src/rules/unnecessary_null_aware_assignments.dart, lib/src/rules/unnecessary_null_in_if_null_operators.dart, lib/src/rules/unnecessary_overrides.dart, lib/src/rules/unrelated_type_equality_checks.dart, lib/src/rules/use_late_for_private_fields_and_variables.dart, lib/src/rules/use_rethrow_when_possible.dart, lib/src/rules/use_setters_to_change_properties.dart, lib/src/rules/use_string_buffers.dart, lib/src/util/condition_scope_visitor.dart, lib/src/util/dart_type_utilities.dart
Move 5 static functions out of DartTypeUtilities. Helps linter comply with [AVOID defining a class that contains only static members.](https://dart.dev/guides/language/effective-dart/design#avoid-defining-a-class-that-contains-only-static-members) and makes the code much more readable.
* `canonicalElementsAreEqual` can be a top-level function
* `canonicalElementsFromIdentifiersAreEqual` can be a top-level function
* `getCanonicalElement` can be an extension on `Element` and be shortened to `canonicalElement` 🎉 
* `getCanonicalElementFromIdentifier` can be an extension on `AstNode` and renamed to be much shorter: `canonicalElement` 🎉 
* `isNullLiteral` can be an extension on `Expression`
=> Move 5 static functions out of DartTypeUtilities

lib/src/extensions.dart, lib/src/rules/exhaustive_cases.dart, lib/src/rules/no_default_cases.dart, lib/src/util/dart_type_utilities.dart
Move 2 static functions out of DartTypeUtilities. Helps linter comply with [AVOID defining a class that contains only static members.](https://dart.dev/guides/language/effective-dart/design#avoid-defining-a-class-that-contains-only-static-members) and makes the code much more readable.
* `asEnumLikeClass` and `hasSubclassInDefiningCompilationUnit`
* Also moved `isEnumLikeClass` into this extension, as it seems equally utility-like as the others.
=> Move two more DartTypeUtilities static methods into extensions

lib/src/extensions.dart, lib/src/rules/avoid_returning_this.dart, lib/src/rules/use_setters_to_change_properties.dart, lib/src/util/dart_type_utilities.dart
Move `DartTypeUtilities.overridesMethod` to an extension, and rename it `get isOverride` (sticks to convention of other bool-returning getters). I also refactored the end of the method body to be more readable.
=> Move DartTypeUtilities.overridesMethod to an extension

lib/src/extensions.dart, lib/src/rules/avoid_slow_async_io.dart, lib/src/rules/await_only_futures.dart, lib/src/rules/null_closures.dart, lib/src/rules/omit_local_variable_types.dart, lib/src/rules/prefer_mixin.dart, lib/src/rules/unsafe_html.dart, lib/src/util/condition_scope_visitor.dart, lib/src/util/dart_type_utilities.dart
* `isClassElement` can be `isClass` on ClassElementExtension; added documentation
* `getLastStatementInBlock` can be `get lastStatement` on BlockExtension; added documentation
* `extendsClass` can be `extendsClass` on DartTypeExtension
* `getImplementedInterfaces` can be `get implementedInterfaces` on InterfaceTypeExtension
Only `extendsClass` is used internally, so kept that with a Deprecation notice.
I think readability is improved in each case.
=> Move 4 static DartTypeUtilities methods to extensions

lib/src/util/boolean_expression_utilities.dart, lib/src/util/tested_expressions.dart
See: https://github.com/dart-lang/linter/issues/2066 and https://github.com/dart-lang/linter/issues/2555.
=> convert unnecessary `.from`s to `.of`s

lib/src/rules/use_late_for_private_fields_and_variables.dart
The gist is that UnifyingAstVisitor was a little expensive, as we ultimately only do any work if we're looking at (1) the left side of an AssignmentExpression, or (2) an Identifier or a PropertyAccess. So it wasn't too hard to just visit those nodes with a RecursiveAstVisitor.
Also in `visitFieldDeclaration`, I moved the `parent != null` check to be outside the for loop
I also tidied up a few comments to be [formatted like sentences](https://dart.dev/guides/language/effective-dart/documentation#do-format-comments-like-sentences).
Fixes https://github.com/dart-lang/linter/issues/3584
Does not address the P1 memory leak or the false positive bug.
=> Speed up use_late_for_private_fields_and_variables

lib/src/extensions.dart, lib/src/rules/avoid_null_checks_in_equality_operators.dart, lib/src/rules/avoid_returning_null.dart, lib/src/rules/avoid_returning_this.dart, lib/src/rules/cascade_invocations.dart, lib/src/rules/diagnostic_describe_all_properties.dart, lib/src/rules/invariant_booleans.dart, lib/src/rules/parameter_assignments.dart, lib/src/rules/prefer_constructors_over_static_methods.dart, lib/src/rules/prefer_foreach.dart, lib/src/rules/prefer_interpolation_to_compose_strings.dart, lib/src/rules/recursive_getters.dart, lib/src/rules/unnecessary_lambdas.dart, lib/src/rules/unreachable_from_main.dart, lib/src/util/condition_scope_visitor.dart, lib/src/util/dart_type_utilities.dart, lib/src/util/leak_detector_visitor.dart
Move `DartTypeUtilities.traverseNodesInDFS` to be an extension method on AstNode.
I also refactored it to be non-recursive. This appears to save ~3% in the big benchmark, but I don't know what the error window is... it might be a negligible performance change.
It is used internally, so I've kept the old static method with a deprecation.
=> Move traverseNodesInDFS to extension

lib/src/extensions.dart, lib/src/rules/unnecessary_lambdas.dart, lib/src/rules/unnecessary_overrides.dart, lib/src/rules/unrelated_type_equality_checks.dart, lib/src/rules/use_full_hex_values_for_flutter_colors.dart, lib/src/rules/use_late_for_private_fields_and_variables.dart, lib/src/util/dart_type_utilities.dart, lib/src/util/unrelated_types_visitor.dart
* `DartTypeUtilities.isConstructorElement` becomes a method `isSameAs` on ConstructorElement
* `DartTypeUtilities.matchesArgumentsWithParameters` becomes a top-level method, `argumentsMatchParameters`, with the same parameters, unchanged body.
* `DartTypeUtilities.unrelatedTypes` becomes a top-level method, `typesAreUnrelated`, with the same parameters, unchanged body.
* `DartTypeUtilities.isNonNullable` is inlined into the single spot which called it.
=> Move four more methods out of DartTypeUtilities

lib/src/rules/prefer_contains.dart
prefer_contains: Move constant evaluation to be later
For performance reasons
Fixes #3549
=> prefer_contains: Move constant evaluation to be later

lib/src/extensions.dart, lib/src/rules/avoid_positional_boolean_parameters.dart, lib/src/rules/avoid_setters_without_getters.dart, lib/src/rules/unnecessary_overrides.dart, lib/src/rules/use_to_and_as_if_applicable.dart, lib/src/util/dart_type_utilities.dart
* `DartTypeUtilities.hasInheritedMethod()` moved to be a getter on MethodDeclarationExtension.
* `DartTypeUtilities.lookUpGetter`, `DartTypeUtilities.lookUpInheritedConcreteGetter`, `DartTypeUtilities.lookUpInheritedConcreteMethod`, `DartTypeUtilities.lookUpInheritedConcreteSetter`, `DartTypeUtilities.lookUpInheritedMethod` are all moved to be zero-parameter methods on MethodDeclarationExtension.
* `DartTypeUtilities.lookUpSetter` was unused and is deleted.
None of these are used internally.
=> Move 6 DartTypeUtilities methods to MethodDeclaration extension methods

lib/src/extensions.dart, lib/src/rules/avoid_catching_errors.dart, lib/src/rules/avoid_function_literals_in_foreach_calls.dart, lib/src/rules/avoid_positional_boolean_parameters.dart, lib/src/rules/avoid_returning_null.dart, lib/src/rules/await_only_futures.dart, lib/src/rules/cancel_subscriptions.dart, lib/src/rules/close_sinks.dart, lib/src/rules/diagnostic_describe_all_properties.dart, lib/src/rules/omit_local_variable_types.dart, lib/src/rules/only_throw_errors.dart, lib/src/rules/prefer_collection_literals.dart, lib/src/rules/prefer_contains.dart, lib/src/rules/prefer_is_empty.dart, lib/src/rules/prefer_iterable_whereType.dart, lib/src/rules/unawaited_futures.dart, lib/src/rules/unnecessary_to_list_in_spreads.dart, lib/src/rules/use_key_in_widget_constructors.dart, lib/src/rules/use_string_buffers.dart, lib/src/util/dart_type_utilities.dart, lib/src/util/flutter_utils.dart
`DartTypeUtilities.implementsAnyInterface`, `DartTypeUtilities.implementsAnyInterface`, `DartTypeUtilities.isSameAs` become extension methods on DartType.
=> Move last methods out from DartTypeUtilities

lib/src/util/dart_type_utilities.dart
Back out part of https://github.com/dart-lang/linter/pull/3600.
`DartTypeUtities.isClass` is used internally and blocking a roll.
https://dart-in-g3-qa-prod.corp.google.com/dg3/Home#/cbuild/find/d839a48e5f0be0488269cd5d557769aa9b051664
/cc @srawlins @bwilkerson 
/fyi @scheglov
=> re-add `DartTypeUtilities.isClass`

lib/src/rules/avoid_redundant_argument_values.dart
This continues from #3619 and resolves the last part of #3617 and dart-lang/sdk#49821.
=> Use `visitEnumConstantArguments` in `avoid_redundant_argument_values`

test/rules/prefer_const_declarations_test.dart
As per our discussion (and looking at how list literals are supported), this is actually WAI.
Closes: #3626
=> fix `prefer_const_declarations` failing test (WAI)

lib/src/rules/use_build_context_synchronously.dart, test/rule_test_support.dart, test/rules/all.dart, test/rules/use_build_context_synchronously_test.dart
Fixes #3676
Also adds `package:flutter` mocking to reflective tests.
=> fix `use_build_context_synchronously` to check for `BuildContext`s in NamedExpressions

lib/src/rules/use_build_context_synchronously.dart, test_data/mock_packages/flutter/lib/src/widgets/framework.dart, test_data/rules/use_build_context_synchronously.dart
This PR ensures that the upcoming [BuildContext.mounted](https://github.com/flutter/flutter/pull/111619) is supported.
Fixes #3688
=> update use_build_context_synchronously for BuildContext.mounted

lib/src/util/unrelated_types_visitor.dart, test_data/rules/iterable_contains_unrelated_type.dart, test_data/rules/list_remove_unrelated_type.dart
If `Iterable.contains` or `List.remove` was called from within an enum, with an implicit receiver, it was not caught by `iterable_contains_unrelated_type` or `list_remove_unrelated_type`.
Fixes https://github.com/dart-lang/linter/issues/3697
=> Report unrelated argument types on Enums

lib/src/util/unrelated_types_visitor.dart, test_data/rules/iterable_contains_unrelated_type.dart, test_data/rules/list_remove_unrelated_type.dart
This allows some rules to track an implicit receiver from within an extension method.
Fixes https://github.com/dart-lang/linter/issues/3702
=> Report unrelated types on implicit receiver calls from extension

lib/src/rules/use_build_context_synchronously.dart, test/rules/use_build_context_synchronously_test.dart
=> check for context property accesses in `use_build_context_synchronously`

test/rules/prefer_collection_literals_test.dart, test_data/rules/prefer_collection_literals.dart
Shows that the check for returning from a function literal is incorrect.
Please include a summary of the change and a reference to any corresponding issues.
If this is a fix to an existing lint rule or a proposed new one, please include
the name of the rule in the pull request.
If this is a new lint or feature and there is not an existing tracking bug, please
consider opening one to better facilitate conversation.
Fixes # (issue)
=> Add missed case for prefer_collection_literals

lib/src/rules/recursive_getters.dart, test/rules/all.dart, test/rules/recursive_getters_test.dart
Addresses the pathological case reported by @davidmorgan (see: `test_constList_expressionFunctionBody`) and makes the common case **_much_** faster.
Compare.
**BEFORE**
**AFTER**
Fixes: https://github.com/dart-lang/linter/issues/3706
=> perf improvements for `recursive_getters`

lib/src/rules/avoid_final_parameters.dart, lib/src/rules/leading_newlines_in_multiline_strings.dart, lib/src/rules/prefer_const_literals_to_create_immutables.dart, lib/src/rules/prefer_double_quotes.dart, lib/src/rules/prefer_int_literals.dart, lib/src/rules/prefer_single_quotes.dart, lib/src/rules/unnecessary_null_aware_operator_on_extension_on_nullable.dart, test/all.dart, test/rule_test.dart, test/validate_rule_description_format_test.dart
Validates that rule descriptions don't have needless leading whitespace.
Catches a few spots missed in https://github.com/dart-lang/linter/pull/2764.
Also ensures description checking is run (by ensuring the list of lints is not empty).
Catches a few spots that were going undetected.
Fixes #3709
/fyi @asashour 
=> validate rule descriptions don't have needless leading whitespace

lib/src/rules/avoid_null_checks_in_equality_operators.dart
=> migrate `avoid_null_checks_in_equality_operators` away from `traverseNodesInDFS()`

lib/src/rules/unnecessary_parenthesis.dart, test_data/rules/unnecessary_parenthesis.dart
Fixes unnecessary_parenthesis handling of an `as` expression and an `is` expression. Also adds documentation explaining the heuristics of the rule.
Also changes 'parenthesis' to 'parentheses' where grammatically necessary.
Fixes https://github.com/dart-lang/linter/issues/1843
=> Fix unnecessary_parenthesis with as-expression

lib/src/rules/avoid_returning_this.dart, test_data/rules/avoid_returning_this.dart
This just changes the lint report position to be the first `return this` statement.
Fixes #780
=> Report avoid_returning_this on the return statement

lib/src/rules/avoid_equals_and_hash_code_on_mutable_classes.dart
The three examples for avoid_equals_and_hash_code_on_mutable_classes don't compile because `hashCode` is a getter and not a method. Also, the class `C` references `B` instead of itself.
You can now copy and paste these examples into a Dart app.
Just a note: the second example also violates [const_constructor_with_non_final_field](https://dart.dev/diagnostics/const_constructor_with_non_final_field) which could be a bit confusing.
=> Correct Documentation Examples for avoid_equals_and_hash_code_on_mutable_classes

lib/src/rules/unnecessary_lambdas.dart
A modest gain in the general case.
**BEFORE**
**AFTER**
=> migrate `unnecessary_lambdas` from `traverseNodesInDFS()`

lib/src/rules/diagnostic_describe_all_properties.dart
Another modest gain (for the general case) and another step closer to deprecating `traverseNodesInDFS()` 🎉 .
**BEFORE**
**AFTER**
=> migrate `diagnostic_describe_all_properties` from `traverseNodesInDFS()`

lib/src/rules/avoid_escaping_inner_quotes.dart
Modest improvement in benchmarks but I think worth it?
**BEFORE**
**AFTER**
=> simplify iteration in `avoid_escaping_inner_quotes`

lib/src/rules/prefer_foreach.dart
Surprisingly big gain in the general case (and we all know this can get quadratic in the pathological one). 🏁 
**BEFORE**
**AFTER**
=> migrate `prefer_foreach` from `traverseNodesInDFS()`

lib/src/rules/avoid_returning_this.dart
Minor improvement but one step closer to deprecating `traverseNodesInDFS`.
**BEFORE**
**AFTER**
=> migrate `avoid_returning_this` from `traverseNodesInDFS`

lib/src/rules/parameter_assignments.dart, test/rules/all.dart, test/rules/parameter_assignments_test.dart
**BEFORE**
**AFTER**
@bwilkerson: it's still a bit awkward but on the right track I think.  Comments welcome!
=> migrate `parameter_assignments` from `traverseNodesInDFS()`

lib/src/rules/prefer_constructors_over_static_methods.dart
A modest gain in the common case.
**BEFORE**
**AFTER**
=> migrate `prefer_constructors_over_static_methods` from `traverseNodesInDFS`

lib/src/rules/prefer_interpolation_to_compose_strings.dart
Not much of a gain in the common case (but serves deprecating `traverseNodesInDFS`).
=> migrate `prefer_interpolation_to_compose_strings` from `traverseNodesInDFS`

.github/workflows/scorecards-analysis.yml
This is required with the update to v2 in https://github.com/dart-lang/linter/commit/40f67411f4bd184175d2b2416818fe1f8bcac158. See [Breaking changes in v2](https://github.com/ossf/scorecard-action#breaking-changes-in-v2) for more information.
=> Add required scorecards id-token permission to fix build

README.md
Bug: https://github.com/dart-lang/.github/issues/31
Adds the scorecards badge to the linter repository. This badge shows the current security score for the repository.
=> Add scorecards badge.

doc/writing-lints.md
I added text at the top with new specifications for naming a lint rule, and linked to https://dart.dev/tools/pub/pubspec#name.
I also formatted the file:
* hard line wraps at 80 columns
* move links to references at the end, to improve inline readability
* standardize on "wide sentence spacing" (two spaces) as this appeared to be the more common case within this file
* remove trailing whitespace
* change `pub run` to `dart run`
=> Writing Lints doc: Add text to naming lints paragraph; format

lib/src/rules/cascade_invocations.dart, test_data/rules/cascade_invocations.dart
I fixed most of https://github.com/dart-lang/linter/issues/1323 earlier, but https://github.com/dart-lang/linter/issues/3240 raised a case that I missed. We just need to add a check for simple identifier in the cascade case.
But I'll leave https://github.com/dart-lang/linter/issues/3240 open, as the false negative half of that story is still a TODO.
=> Address false positive in 3240

lib/src/rules/non_constant_identifier_names.dart, lib/src/rules/null_check_on_nullable_type_parameter.dart, lib/src/rules/package_prefixed_library_names.dart, lib/src/rules/prefer_generic_function_type_aliases.dart, lib/src/rules/prefer_is_empty.dart, lib/src/rules/prefer_is_not_empty.dart, lib/src/rules/prefer_iterable_whereType.dart, lib/src/rules/prefer_typing_uninitialized_variables.dart, lib/src/rules/provide_deprecation_message.dart, lib/src/rules/unnecessary_overrides.dart, lib/src/rules/void_checks.dart
Continuing some ongoing work to improve the messages for lints by adding explicit `LintCode`s.
=> Add lint codes for the remaining core lints

lib/src/rules/no_leading_underscores_for_local_identifiers.dart, test_data/rules/no_leading_underscores_for_local_identifiers.dart
When considering the names of local variables, do not consider super formals to be local variables.
Fixes https://github.com/dart-lang/linter/issues/3769.
=> Do not consider super formals as local variables

lib/src/rules/flutter_style_todos.dart
Refactoring the regular expressions (#3774) should get us another win but this addresses the known slowness in `sync*` (https://github.com/dart-lang/sdk/issues/32102) and speeds this up ~3x.
**Before**
**After**
=> `flutter_style_todos`: factor out sync*

lib/src/rules/prefer_const_constructors.dart
Delay more expensive node `isConst` check.
A pretty minor bump but a few runs suggest some relative improvement (and objectively this shouldn't **_hurt_** and is no less clear).
**Before**
**After**
=> `prefer_const_constructors`: constant check re-ordering

example/all.yaml, lib/src/rules.dart, lib/src/rules/dangling_library_doc_comments.dart, test/rules/all.dart, test/rules/dangling_library_doc_comments_test.dart
Fixes https://github.com/dart-lang/linter/issues/3789
The issue states the intent of the rule well, but the devil is, as usual, in the details.
I have implemented this rule specifically to use a heuristic of which doc comments _might_ be trying to document a library. Here are the criteria:
* `///`-style comments only.
* comments above the first directive, unless the first directive is a `library` or `part` directive, so doc comments mixed _within_ directives (imports, exports) are not considered.
* comments above the first declaration, which are not physically attached to the declaration; that is, there exists at least one blank line between the doc comment and the first non-comment token of the declaration. The tests cover this case well, as it is tricky to get right.
* comments at the …
=> New rule: dangling_library_doc_comments

lib/src/rules/pub/package_names.dart
This code was commented out pending the publishing of a later version of the analyzer. That version has been published and moved to, so this code can now be uncommented.
There's no rush to merge this.
=> Define a lint code for package_names

lib/src/rules/collection_methods_unrelated_type.dart, test/rules/collection_methods_unrelated_type_test.dart
This PR removes 5 methods from `collection_methods_unrelated_type`'s concern, as they are too hard to analyze given downwards inference.
Fixes #3833
=> Remove Iterable<Object?>-related methods from collection_methods_unrelated_type

lib/src/rules/always_put_control_body_on_new_line.dart, lib/src/rules/always_specify_types.dart
Add a note. Also correct the name of the "style guide for the flutter repo".
Fixes #1847
=> Add notes about `always_put_control_body_on_new_line` and the formatter

lib/src/rules/use_to_and_as_if_applicable.dart, test_data/rules/use_to_and_as_if_applicable.dart
This issue is already fixed, but the tests are still lacking.
* Properly format the description text.
* Do not create a constructor parameter name that shadows a class name.
* Add inheritance tests.
Fixes #2080
=> Add tests for use_to_and_as_if_applicable inheritance

lib/src/rules/use_build_context_synchronously.dart, test/rules/use_build_context_synchronously_test.dart
Fixes #3818
(FWIW: this is not for immediate landing since we want to potentially hustle a low-risk release in after 1.29 sticks.)
=> `use_build_context_synchronously`: check for context properties

lib/src/rules/avoid_redundant_argument_values.dart, test/rules/avoid_redundant_argument_values_test.dart
Redirecting constructors are not allowed to specify default values; instead they sort of "inherit" the default values of the redirectee (the target constructor).
One might thing a better fix would be to build this logic into `Expression.staticParameterElement`, but I think there are reasons that that should point to the redirecting constructor's parameters, rather than the redirectee's parameters. Specifically, the two lists of parameters _can_ have different parameter types.
Fixes #2217
=> avoid_redundant_argument_values: Check correct parameters of redirecting constructors

lib/src/rules/avoid_redundant_argument_values.dart, test/rules/avoid_redundant_argument_values_test.dart
=> Fix avoid_redundant_argument_values for redirecting generative constructors

lib/src/rules/avoid_equals_and_hash_code_on_mutable_classes.dart, lib/src/rules/enable_null_safety.dart
Also puts `@immutable` in code style.
=> Fix broken markdown caused by unclosed code block

.github/ISSUE_TEMPLATE/lint-proposal.md
This changes the lint template, similar to the changes done in https://github.com/dart-lang/linter/commit/81ca8f2ccd14fbe172874b5cc1aeda10bf95be91
=> Put `bad` examples before `good` in lint template

lib/src/rules/library_annotations.dart
Should be at the top of the library file
=> library_annotation: fix bad example

example/all.yaml, lib/src/rules/prefer_equal_for_default_values.dart
This lint is no longer necessary with the analyzer reporting it as a warning in Dart 2.19(https://github.com/dart-lang/sdk/commit/289aa509cd4f078457faf50670bb2871c31b2718).
=> Deprecate prefer_equal_for_default_values

lib/src/rules/prefer_equal_for_default_values.dart, test/rules/prefer_equal_for_default_values_test.dart, test_data/rules/prefer_equal_for_default_values.dart
See also: https://github.com/dart-lang/linter/pull/3855.
=> don't overreport `prefer_equal_for_default_values` when it's a warning

CHANGELOG.md, lib/src/rules/prefer_equal_for_default_values.dart, lib/src/version.dart, pubspec.yaml, test/rules/prefer_equal_for_default_values_test.dart, test_data/rules/prefer_equal_for_default_values.dart
- updated `prefer_equal_for_default_values` to not report for SDKs `>=2.19`,
where this lint is now an analyzer diagnostic.
Closes: #3864.
---
/cc @bwilkerson @srawlins @parlough
=> 1.31.0 (cherry-pick release)

lib/src/rules/unrelated_type_equality_checks.dart
Fixes #3868 
(Note that we'll want to hustle this into a cherry-pick release for 2.19.)
=> update unrelated_type_equality_checks for fixnum restructuring

CHANGELOG.md, lib/src/rules/unrelated_type_equality_checks.dart
Pulls in `unrelated_type_equality_checks` fix.
=> linter 1.31.0 cherry-pick release (update)

lib/src/rules/unnecessary_parenthesis.dart, test_data/rules/unnecessary_parenthesis.dart
As reported in #3848
This fixes the situation where a nullable expression is surrounded by parentheses.
Please note, I couldn't create a test case for `SpreadElement` or `ExtensionOverride` (which possibly have also `isNullAware`).
=> Fix `unnecessary_parenthesis` with null aware expressions.

lib/src/rules/unnecessary_parenthesis.dart, test_data/rules/unnecessary_parenthesis.dart
#3848
Add a fix for the `PostfixExpression` with `!`.
Please also note the Flutter code can be simplified as proposed in https://github.com/flutter/flutter/pull/117026
=> Fix `unnecessary_parenthesis` with postfix bang operator.

lib/src/rules/avoid_null_checks_in_equality_operators.dart
There are a few issues with the text, which I fix here:
* the example used a class with a non-nullable field with no initializer,
* the example did not specify a parameter type for `operator ==`; in Dart versions before null safety, this parameter type was `dynamic` (I think), but after null safety, it is `Object`, so even aside from this lint rule, comparing to null wouldn't make sense.
* incorrect text in the first sentence summary.
=> Fix examples in avoid_null_checks_in_equality_operators

AUTHORS, lib/src/rules/use_build_context_synchronously.dart, test_data/rules/use_build_context_synchronously.dart
Prevent false positives in IF statements, only check the IF statements.
Fixes false positives introduced in https://github.com/dart-lang/linter/pull/3458
=> Fix use_build_context_synchronously in if conditions

lib/src/rules/non_constant_identifier_names.dart, test/rules/non_constant_identifier_names_test.dart
Add support for:
* `DeclaredVariablePattern`s
* `RecordPatternField`s
(Pattern for statement testing is pending some upstream parser changes.)
See: https://github.com/dart-lang/linter/issues/3669
=> extend `non_constant_identifier_names` for patterns

example/all.yaml, lib/src/rules.dart, lib/src/rules/unnecessary_breaks.dart, test/rules/all.dart, test/rules/unnecessary_breaks_test.dart
First crack at a new `unnecessary_breaks` lint.
Feedback and other cases (hah) welcome.
Fixes #3671
/fyi @MaryaBelanger this is what docs typically start as
=> + unnecessary_breaks

lib/src/util/leak_detector_visitor.dart
* Add some doc comments.
* In `_buildVariableReporter`, in the first loop over DartTypePredicates, extract out the null check for `variable`'s `declaredElement`, which is unrelated to the loop.
* In `_buildVariableReporter`, `validators` was a List of Iterables, whose elements were never used; instead, the List was added to in various ways, and then we asked if all of the Iterables were empty. This is a long-winded way of saying `List<bool>`, so I make each of the functions which added to `validators` instead return `bool`. Also, we don't need to carry out _all_ of the checks. If any of these checks returns false, we can just exit `_buildVariableReporter`, without reporting any lint.
* Some of the functions should now be renamed, but I didn't want to confuse in the PR by adding a lot of …
=> Refactor leak detector

lib/src/rules/void_checks.dart, test_data/rules/experiments/nnbd/rules/void_checks.dart
* Fixes #3172
Note that the tests I'm adding *do* need to be in the nnbd folder, they don't fail in legacy Dart.
=> Fix void_checks false positive: allow returning Never as void

lib/src/rules/omit_local_variable_types.dart
Not sure what was up with the old documentation, but that's definitely not how this lint works in its current state
=> Fix documentation for `omit_local_variable_types`

lib/src/rules/avoid_as.dart, tool/doc.dart
Room for improvement but a start.  
Adds "removed" state context to generated rule docs.
**Example:**
@parlough: I'm curious if you have some thoughts here.
We'd like to keep generating docs for removed lints (to keep backlinks working) but would like it to be clear at a glance that a rule has been removed.
Any ideas most welcome!
See: #3880 
/cc @bwilkerson @parlough
=> "removed" rule doc codegen WIP

lib/src/rules/unnecessary_parenthesis.dart, test_data/rules/unnecessary_parenthesis.dart
* Fixes #3885
* Fixes #3886
---
This implements new rules for `unnecessary_parenthesis` lint:
* `${(  )}` and `((  ))` are never OK, drop the inner ones
else,
* `(a ? b : c)` is always OK
* `(a == b)` and `(a != b)` are OK in assignment-like and return-like statements.
---
This pull request addresses two seemingly completely separate changes, but I think it should be done all at once. That is because:
* Currently some cases where doubled parentheses *happen to be* dropped are cases of `((a == b))` etc. So I'd be introducing more false negatives if I remove the old reason to drop these but not add the new one.
* Removing doubled parentheses just misses one case of `ArgumentList` so it's unclear why I am adding all the other numerous cases here. But more rules are necessary *only because* …
=> Detect doubled unnecessary_parenthesis, but allow ternary and equality

lib/src/rules/unnecessary_parenthesis.dart, test/rules/all.dart, test/rules/unnecessary_parenthesis_test.dart
=> don't report `unnecessary_parenthesis` for null-aware cascades

lib/src/rules/unnecessary_parenthesis.dart, test/rules/unnecessary_parenthesis_test.dart
This PR cover more cases for #4041
The fix in #4043 covers only the case of `parent is MethodInvocation`, but it should be generalized to be not based on the `parent` but rather that `expression is CascadeExpression`.
This PR removes the condition from `_isNullAware` and leaves the logic to reach line 150 to return without linting.
=> Fix `UnnecessaryParenthesis`

lib/src/rules/unnecessary_const.dart, test/rules/unnecessary_const_test.dart
Follow-up from https://github.com/dart-lang/linter/issues/4049
The previous fix silenced linting on all collection literals (not just ones in constant patterns). 😬 
=> fix pattern constant detection

test/rules/avoid_final_parameters_test.dart, test/rules/conditional_uri_does_not_exist_test.dart, test/rules/constant_identifier_names_test.dart, test/rules/invalid_case_patterns_test.dart, test/rules/non_constant_identifier_names_test.dart, test/rules/overridden_fields_test.dart, test/rules/parameter_assignments_test.dart, test/rules/prefer_const_constructors_test.dart, test/rules/prefer_contains_test.dart, test/rules/unnecessary_breaks_test.dart, test/rules/use_enums_test.dart
The `HintCode` values are being deprecated for new `WarningCode` ones.
This is required to be pulled into the SDK and google3 before we can remove the HintCodes.
=> Use WarningCodes over deprecated HintCodes

lib/src/rules/unnecessary_null_checks.dart, test/rules/unnecessary_null_checks_test.dart
`Completer.complete`.
Fixes #4077
=> `unnecessary_null_checks` to ignore `Future.value` and

lib/src/rules/prefer_mixin.dart, test/rules/all.dart, test/rules/prefer_mixin_test.dart
Fixes https://github.com/dart-lang/linter/issues/4065
=> support class mixins in `prefer_mixin`

lib/src/rules/unnecessary_lambdas.dart, test/rules/unnecessary_lambdas_test.dart
Fixes https://github.com/dart-lang/linter/issues/2182
Final properties and variables are understood by this rule to be "safe for tearing off" as they shouldn't change. While this is not true for final fields, it is the understanding. This change also requires the property or variable to not be late, so that it is definitely initialized when it is torn off.
=> unnecessary_lambdas: Do not report when expression has late final variables

test/rule_test_support.dart, test/rules/avoid_void_async_test.dart
This will ensure issues like #4108 won't come up again.
(Addressing a newly caught issue with [`avoid_void_async_test.dart`](https://github.com/dart-lang/linter/pull/4112/files#diff-67c4d7e3477a13b813accd633db07e372ac60d3b72fc527c5982f60b94184f52) along the way. 🙄 )
=> ensure rules tests by reflective test exist

.github/workflows/build.yaml, .github/workflows/gh-pages.yml
Related to https://github.com/dart-lang/setup-dart/issues/79; this updates the CI here to use the new, unreleased version of the `setup-dart` action in order to ensure it's working as expected.
=> dogfood the new version of setup-dart

test/integration/public_member_api_docs.dart
After manually reviewing the full expectations and comparing with the `// LINT` and `// OK` comments, this is the total fix for the misalignment.
Fixes #4114
=> Align public_member_api_docs expectations with '// LINT' comments

test/rule_test_support.dart
Helpful especially for folks stumbling around in the dark supporting new language features with unfamiliar ASTs. 🔦 
Sample output:
```
package:test_api                               fail
test/rule_test_support.dart 252:7              LintRuleTest.assertDiagnosticsIn
test/rule_test_support.dart 143:11             LintRuleTest.assertDiagnostics
===== asynchronous gap ===========================
test/rules/prefer_final_locals_test.dart 42:5  PreferFinalLocalsPatternsTest.test_destructured_recordPattern_list
Expected but did not find:
prefer_final_locals [13, 1]
prefer_final_locals [16, 1]
CompilationUnitImpl [f() {var [a, b] = ['a', 'b']; print('$a$b');}] 
FunctionDeclarationImpl [f() {var [a, b] = ['a', 'b']; print('$a$b');}] 
FunctionExpressionImpl [() {var [a, b] = ['a', 'b']; …
```
=> 🔦 optionally dump ASTs on reflective test failures

test_data/rules/library_private_types_in_public_api.dart, test_data/rules/overridden_fields.dart, test_data/rules/prefer_const_constructors_in_immutables.dart, test_data/rules/slash_for_doc_comments.dart
Running w/ 3.0 experiments enabled, these tests all fail.
I think they can all be migrated to `mixin` declarations and not lose any coverage.
9 tests remain that I think need coverage in both 3.0 and pre-3.0 worlds so I'll work on breaking out some reflective tests for those.
/cc @scheglov
=> update tests w/ 3.0-compatible mixins

test_data/rules/avoid_implementing_value_types.dart, test_data/rules/prefer_asserts_in_initializer_lists.dart
Follow-up from https://github.com/dart-lang/linter/pull/4136.
A few I missed.
The rest I'll migrate to reflective tests.
/cc @scheglov
=> mixin test data migrations for 3.0

test_data/rules/unrelated_type_equality_checks.dart
Another simple one.
/cc @scheglov
=> update `unrelated_type_equality_checks` w/ 3.0-safe mixin

lib/src/rules/no_adjacent_strings_in_list.dart, test/rules/all.dart, test/rules/non_adjacent_strings_in_list_test.dart
=> switch pattern support for `no_adjacent_strings_in_list`

lib/src/rules/null_check_on_nullable_type_parameter.dart, test/rule_test_support.dart, test/rules/all.dart, test/rules/null_check_on_nullable_type_parameter_test.dart
=> null assert pattern support for `null_check_on_nullable_type_parameter`

example/all.yaml, lib/src/rules.dart, lib/src/rules/deprecated_member_use_from_same_package.dart, test/rules/all.dart, test/rules/deprecated_member_use_from_same_package_test.dart
Fixes https://github.com/dart-lang/linter/issues/4118
This rule implements (more or less*) the same feature currently implemented in the analyzer `HintCode.DEPRECATED_MEMBER_USE_FROM_SAME_PACKAGE`.
See [this comment on the issue](https://github.com/dart-lang/linter/issues/4118#issuecomment-1460627011) for the steps to roll this to analyzer, which involve simultaneously removing `HintCode.DEPRECATED_MEMBER_USE_FROM_SAME_PACKAGE`.
*: The changes are improvements to the rule, which are similarly proposed and in-progress for `HintCode.DEPRECATED_MEMBER_USE`: https://github.com/dart-lang/sdk/issues/51664.
=> Add new rule: deprecated_member_use_from_same_package

lib/src/ast.dart, lib/src/rules/public_member_api_docs.dart, test/integration/public_member_api_docs.dart
Fixes #3987 and fixes #4116.
I went to fix #3987 but could not see any change in the results for `test/integration/public_member_api_docs.dart`. It turns out this test does not make any assertions on the code you're writing. It makes assertions on whatever `dart` binary exists in your `PATH`. So I filed #4116, and fix it here.
* Simplify `getNodeToAnnotate` and `_getNodeToAnnotate` by combining them into one method. It was split for nullability purposes, but that logic can be made more local in the ConstructorDeclaration and ExtensionDeclaration cases.
* Add MixinDeclaration case to `getNodeToAnnotate`.
* Sort the cases in `getNodeToAnnotate`.
* Re-implement `test/integration/public_member_api_docs.dart` with the `cli.dart` features that the other integration tests use.
* Normally this …
=> Fix reported range for undocumented mixin; re-implement public docs integration test

lib/src/rules/deprecated_member_use_from_same_package.dart
In https://dart-review.googlesource.com/c/sdk/+/289028, I widen the type of this parameter in the super class, so we must widen it here as well.
We'll need this later in order to report on deprecated uses in ObjectPatterns as well.
=> Widen _DeprecatedMemberUseVerifier.reportError parameter type

lib/src/rules/literal_only_boolean_expressions.dart, test/rules/literal_only_boolean_expressions_test.dart
=> when clause support for `literal_only_boolean_expressions`

README.md
This is linked to by the OpenSSF scorecard badge at the top of the README. The previous link was to unformatted JSON. Instead, this links to [deps.dev](https://deps.dev) which formats the results and in the future may include other information.
Previous link: https://api.securityscorecards.dev/projects/github.com/dart-lang/linter
New link: https://deps.dev/project/github/dart-lang%2Flinter
=> Use deps.dev for OpenSSF scorecard results link

lib/src/rules/void_checks.dart, test/rules/void_checks_test.dart
=> assigned variable support for `void_checks`

lib/src/rules/unnecessary_null_checks.dart, test/rules/unnecessary_null_checks_test.dart
=> null assert pattern support for `unnecessary_null_checks`

test/rules/public_member_api_docs_test.dart
Closes #1396 (an analyzer bump, long ago, likely fixed the issue)
=> Add a test for a documented annotated enum value

lib/src/rules/prefer_void_to_null.dart, test/rules/prefer_void_to_null_test.dart
Fixes https://github.com/dart-lang/linter/issues/4201 **(actually)** 😊 
/cc @srawlins
=> don't overreport `prefer_void_to_null` on cast patterns and as expressions

test/rules/use_late_for_private_fields_and_variables_test.dart
It looks like you can't do a pattern assignment of a field or top level member so the diagnostics are expected.  Verifying no lints.
@srawlins: let me know if this doesn't get the case you had in mind?
Fixes #4180
=> `use_late_for_private_fields_and_variables` pattern assignment test

example/all.yaml, lib/src/rules.dart, lib/src/rules/type_literal_in_constant_pattern.dart, pubspec.yaml, test/rule_test_support.dart, test/rules/all.dart, test/rules/type_literal_in_constant_pattern_test.dart
Obviously, cannot be landed with dependency overrides, will clean up after initial review.
Fixes https://github.com/dart-lang/linter/issues/4195
=> Issue 4195. Add type_literal_in_constant_pattern

test/rule_test_support.dart, test/rules/no_leading_underscores_for_local_identifiers_test.dart
(The AST dump change just means you don't need to scroll to see the current state output.)
=> `no_leading_underscores_for_local_identifiers` if-case tests

test/rule_test_support.dart, test/rules/cancel_subscriptions_test.dart, test/rules/constant_identifier_names_test.dart, test/rules/join_return_with_assignment_test.dart, test/rules/non_constant_identifier_names_test.dart, test/rules/null_check_on_nullable_type_parameter_test.dart, test/rules/parameter_assignments_test.dart, test/rules/prefer_const_constructors_test.dart, test/rules/prefer_contains_test.dart
These diagnostics are just noise and we need to do hokey things to ignore them.
In case we ever care a test can always override `ignoredErrorCodes`.
I'll take a pass to remove all the gross `print(..)` work-arounds next.
=> filter UNUSED_LOCAL_VARIABLE diagnostics in test expectations

test/rules/cancel_subscriptions_test.dart, test/rules/deprecated_member_use_from_same_package_test.dart
The `HintCode`s are soft-deprecated. Removing them will cause these references to die.
=> Refer to new WarningCodes as such

lib/src/rules/prefer_void_to_null.dart, test/rules/prefer_void_to_null_test.dart, test_data/rules/prefer_void_to_null.dart
Fixes #3792  to not report `Null` as the type of a variable declaration.
=> prefer_void_to_null: not for variable declarations

lib/src/rules/implicit_reopen.dart
* Many of the extension getters on `InterfaceElement?` helped account for a `null` receiver, but it turns out we don't want to report any lint when the annotated element is `null`, or when it's supertype's element is `null` either (we we also null-checking `supertype` in a few positions already).
* We also don't want to report any lint when the annotated element is not a `ClassElement`, or when it's supertype is not a `ClassElement`, so when we promote those variables, a lot of the benefits of the extension getters fall away.
=> Simplify logic in implicit_reopen

lib/src/rules/unreachable_from_main.dart, test/rules/unreachable_from_main_test.dart
This adds support for reporting unreachable constructors in `unreachable_from_main`.
* Constructors (named and unnamed) can be reachable through direct call, tear-off, explicit super call, implicit super call (default constructor), transitive implicit super call, redirecting constructor initializer, redirected factory constructor.
* Unused public enum constructors are already reported as `UNUSED_ELEMENT`.
=> unreachable_from_main: Report unreachable constructors

test/rules/prefer_const_constructors_in_immutables_test.dart
The linter never had a chance to report lint in this test case.
=> prefer_const_contsructors_in_immutables: Use @immutable class in test

test/rules/use_build_context_synchronously_test.dart, test_data/rules/use_build_context_synchronously.dart
This also makes some of the existing tests more compact, allowing for the reported range to have a smaller offset (like `lint(115, 21)` vs `lint(145, 21)`).
=> Move more use_build_context_synchronously tests

lib/src/util/dart_type_utilities.dart, test/rules/collection_methods_unrelated_type_test.dart, test/rules/unrelated_type_equality_checks_test.dart
Fixes https://github.com/dart-lang/linter/issues/4265
Uses `isAssignableTo` to handle relatedness, accounting for shape and subtypes.
=> Account for records in type relatedness checks

test/rules/use_build_context_synchronously_test.dart
I've found myself writing linguistic gymnastics in the test case names for `use_build_context_synchronously`. This is an experiment where I use slightly shorter names, and appending suffixes like `2`, `3`, etc. and then using simpler English with punctuation in a comment at the top.
WDYT?
=> Add comments to use_build_context_synchronously tests with fuller explanations

.github/workflows/gh-pages.yml
This should fix our broken gh-pages deployment.
=> bump gh pages build to dev SDK

lib/src/rules/use_build_context_synchronously.dart, test/rule_test_support.dart, test/rules/use_build_context_synchronously_test.dart
Also enables `propagate-linter-exceptions`, so that we get the crash when resolving test code.
This issue started to happen quite often internally, there is a spike of crashes.
=> [use_build_context_synchronously] Fix for unprotected 'last' invocation.

example/all.yaml, lib/src/rules.dart, lib/src/rules/matching_super_parameters.dart, test/rules/all.dart, test/rules/matching_super_parameters_test.dart
Implements the proposal at https://github.com/dart-lang/linter/issues/4259
=> New rule: Use matching super parameter names

pubspec.yaml
See: #4204.
Some out of dates deps remain:
dev_dependencies:
grinder       *0.9.0    *0.9.0      *0.9.0      0.9.3    
matcher       *0.12.14  *0.12.14    *0.12.14    0.12.15  
But I haven't investigated causes...
=> bump cli_util dep

example/all.yaml, lib/src/rules.dart, lib/src/rules/no_literal_bool_comparisons.dart, test_data/rules/no_literal_bool_comparisons.dart
This lints against any expression like `x == true` or `false == x`.
It kicks in only if the variable is of type `bool`, non-nullable.
Fixes #3005
Ref https://github.com/dart-lang/linter/issues/3005#issuecomment-941293191
Ref https://github.com/dart-lang/linter/issues/3908#issuecomment-1352445021
=> Lint about comparing booleans to boolean literals

tool/gh/get_labels.dart, tool/github.dart
Adds a simple tool to fetch issue labels.
Sample run:
```
linter [main] ⚡  dart tool/gh/get_labels.dart -o dart-lang -n linter
area-build
cla: no
cla: yes
customer: flutter
customer: g3
customer: money (g3)
dependency: analyzer
effective dart
false negative
false positive
good first issue
help wanted
lint proposal
lint request
meta
needs internal testing
needs-info
new language feature
NNBD
P0
P1
P2
P3
P4
process
pub
set-core
set-flutter
set-flutter (dev)
set-internal
set-internal (available)
set-none
set-recommended
status: accepted
status: closed
status: in progress
status: pending
style
type-bug
type-code-health
type-documentation
type-enhancement
type-performance
type-question
type-task
type-test
ux
waiting for customer response
```
/fyi @jcollins-g
=> add a tool to get GH issue labels

lib/src/rules/avoid_function_literals_in_foreach_calls.dart, test/rules/avoid_function_literals_in_foreach_calls_test.dart
* Fixes #4328.
Reverts #4039 that caused false negatives in non-null-safe mode. 
And reverts #2752 along with it because it was not the exact right fix in the first place.
Null-aware calls are since handled by #4305 and all the existing tests still pass.
=> Don't check if iterable is nullable, what matters is null-aware calls

lib/src/rules/use_build_context_synchronously.dart, test/rules/use_build_context_synchronously_test.dart
This is a sizable refactoring of `use_build_context_synchronously` which I think makes it more robust for future improvements, and solves one bug as a demonstration of this.
I learned a lot about this rule while poking around, and this refactoring is not a slam dunk (the code is certainly longer), so I'm including a big explanation of what is going on (and the code itself has many comments).
**Quick description of the rule**: In a method, you should not access a BuildContext (named `context`) after any `await` expression, _unless_ you "guard" that BuildContext access with a proper "mounted check", which is a call to `mounted.check` in some control-flow-affecting position, _between_ the `await` and the BuildContext access.
The devil is really in the details of what defines a proper …
=> Refactor "mounted check" computation in `use_build_context_synchronously`

test/rules/use_build_context_synchronously_test.dart
Fixes https://github.com/dart-lang/linter/issues/4027
I think this was fixed by the recent refactoring. Just adding test cases here.
=> Add use_build_context_synchronously tests for context-in-await

lib/src/rules/avoid_returning_this.dart, test/rules/avoid_returning_this_test.dart
Updates the semantics of `avoid_returning_this` to bail when a body has a return of anything non-`this`. This lint should only fire when `this` is returned unconditionally.
Fixes #3853
=> fix `avoid_returning_this` false positive w/ conditional this returns

lib/src/rules/prefer_const_constructors_in_immutables.dart, test/rules/prefer_const_constructors_in_immutables_test.dart
Saw a crash in logs.
```
StateError: Bad state: No element
at ListBase.firstWhere    (dart:collection)
at _Visitor._hasConstConstructorInvocation    (prefer_const_constructors_in_immutables.dart:124)
at _Visitor.visitConstructorDeclaration    (prefer_const_constructors_in_immutables.dart:96)
```
=> Fix for crash in prefer_const_constructors_in_immutables when firstWhere().

lib/src/rules/use_build_context_synchronously.dart, test/rules/use_build_context_synchronously_test.dart
We just need to handle more expression types in `accessesContext`. I broke the code out into a getter on Expression, to allow for recursion (as is needed for a postfix expression, parentheses expression, etc).
Fixes https://github.com/dart-lang/linter/issues/4342
=> Report use_build_context_synchronously for null-asserted BuildContext

lib/src/rules/type_literal_in_constant_pattern.dart, test/rules/type_literal_in_constant_pattern_test.dart
As requested in https://github.com/dart-lang/linter/issues/4195#issuecomment-1523954808
=> Report type_literal_in_constant_pattern more often.

lib/src/rules/cast_nullable_to_non_nullable.dart, pubspec.yaml, test/rules/all.dart, test/rules/cast_nullable_to_non_nullable_test.dart
See also: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8780744067138629361/+/u/analyze_flutter_flutter/stdout
/cc @scheglov
=> don't overreport `cast_nullable_to_non_nullable` on undefined classes

example/all.yaml, lib/src/rules/iterable_contains_unrelated_type.dart, lib/src/rules/list_remove_unrelated_type.dart
=> Deprecate iterable_contains_unrelated_type and list_remove_unrelated_types

lib/src/rules/await_only_futures.dart, test/rules/all.dart, test/rules/await_only_futures_test.dart
(This is breaking internally.)
See also: https://github.com/dart-lang/linter/pull/4371
/cc @scheglov
=> skip undefined classes in `await_only_futures`

lib/src/rules/iterable_contains_unrelated_type.dart, lib/src/rules/list_remove_unrelated_type.dart
In preparation for: https://github.com/dart-lang/sdk/issues/52472.
/cc @srawlins
=> add `replacedBy` info to point to `collection_methods_unrelated_type`

test/rules/use_enums_test.dart
We are reversing the deprecation: This code will remain a `HintCode`.
=> Update reference to UNUSED_ELEMENT_PARAMETER

tool/doc.dart
Eventually moving away from the site, but since it's still used and referenced, doesn't hurt to add some usage information.
Staged example: https://parlough-linter.web.app/lints/unnecessary_late.html
Closes https://github.com/dart-lang/linter/issues/4351
=> Include usage information in generated docs

.github/ISSUE_TEMPLATE/lint-proposal.md, README.md, doc/writing-lints.md, lib/src/rules/avoid_classes_with_only_static_members.dart, lib/src/rules/avoid_equals_and_hash_code_on_mutable_classes.dart, lib/src/rules/avoid_init_to_null.dart, lib/src/rules/camel_case_extensions.dart, lib/src/rules/camel_case_types.dart, lib/src/rules/directives_ordering.dart, lib/src/rules/empty_constructor_bodies.dart, lib/src/rules/no_literal_bool_comparisons.dart, lib/src/rules/one_member_abstracts.dart, lib/src/rules/package_api_docs.dart, lib/src/rules/prefer_equal_for_default_values.dart, lib/src/rules/slash_for_doc_comments.dart, lib/src/rules/super_goes_last.dart, lib/src/rules/type_annotate_public_apis.dart, lib/src/rules/type_init_formals.dart, lib/src/rules/unnecessary_final.dart, lib/src/rules/unnecessary_getters_setters.dart, lib/src/rules/unnecessary_this.dart, lib/src/rules/use_if_null_to_convert_nulls_to_bools.dart, lib/src/rules/use_string_in_part_of_directives.dart, lib/src/rules/use_to_and_as_if_applicable.dart
This PR primary updates to the more concise `dart.dev/effective-dart` path we've [updated to](https://github.com/dart-lang/site-www/commit/176f6c58c204690fb5f421617b14f2eb99696f58) but also worked historically. It also updates multiple mentions of Effective Dart directly to the related rule for more relevant information. Also some linked to the wrong page completely, so updated those too.
=> Use more direct Effective Dart links

lib/src/rules/require_trailing_commas.dart, test_data/rules/require_trailing_commas.dart
This PR checks trailing commas in list/set/map literals.
=> check trailing commas in list/set/map literals

test/engine_test.dart
Found this while playing around with `unreachable_from_main`.
=> Make a field in engine_test non-nullable

lib/src/rules/unreachable_from_main.dart, test/rules/unreachable_from_main_test.dart
A reference in a type annotation is not good enough to count as "reachable". Marking a type as reachable only because it was seen in a type annotation would be a miscategorization if the type is never instantiated or subtyped.
This was inspired by a comment @bwilkerson made in an earlier review.
CC @goderbauer This is the last change I plan for this rule 😁
=> unreachable_from_main: Do not consider type annotations when computing reachability

lib/src/rules/deprecated_member_use_from_same_package.dart
We will stop visiting `NamedType.name` node (and remove it). So, `NamedType.element` should be used explicitly.
=> Prepare for the breaking change to NamedType.

test/engine_test.dart, test/experiments_test.dart, test/rule_test.dart, test/test_constants.dart, test/unmocked_sdk_rule_test.dart, test/util/rule_debug.dart, tool/rule.dart
Sample output:
```
☁  linter [generate_unit_test_stub] ⚡  dart tool/rule.dart -n no_wildcard_variable_uses
Writing to ./lib/src/rules/no_wildcard_variable_uses.dart
Writing to ./test/rules/no_wildcard_variable_uses_test.dart
Don't forget to update lib/src/rules.dart with a line like:
..register(NoWildcardVariableUses())
and add your rule to `example/all.yaml`.
A unit test has been stubbed out in:
test/rules/no_wildcard_variable_uses_test.dart
```
```dart
// Copyright (c) 2023, the Dart project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.
import 'package:analyzer/dart/ast/ast.dart';
import 'package:analyzer/dart/ast/visitor.dart';
import '../analyzer.dart'; …
```
=> migrate test stub generation to unit test style

example/all.yaml, lib/src/rules.dart, lib/src/rules/no_wildcard_variable_uses.dart, test/rules/all.dart, test/rules/no_wildcard_variable_uses_test.dart
Fixes #4392
/cc @bwilkerson @scheglov @MaryaBelanger
=> + no_wildcard_variable_uses

lib/src/rules/unrelated_type_equality_checks.dart, test/rules/unrelated_type_equality_checks_test.dart
This PR mainly splits the lint message into two, one appropriate for expressions (BinaryExpression with `==` or `!=`) and one appropriate for patterns. In each case, a conscious decision was made to write the "argument" type before the "target" type (approximate terms for the two cases). In particular for patterns, this produces messages like:
> The operand type, 'String', is not a subtype nor a supertype of the value type, 'int'.
I think this is much more readable than printing the target type (value type) first, as the problem likely does not lie with the value type, but with the operand type. But I'm still very open to word-smithing; this one is wordy 🙁 .
Also some tidying:
* Move some utility functions into the `_Visitor`, so as not to pass around the `TypeSystem`.
* Move some utility …
=> Print the type names in unrelated_type_equality_checks

test/doc_test.dart, test/engine_test.dart, test/experiments_test.dart, test/rule_test.dart, test/util/test_utils.dart, test/validate_rule_description_format_test.dart
Changes required to make tests "hermetic" and runnable via `dart test` and from within the idea using the "run all tests" action.
```
☁  linter [main] ⚡  dart test test
01:23 +1554: test/doc_test.dart: doc generation fixStatus (sanity)                                              
loading https://raw.githubusercontent.com/dart-lang/sdk/main/pkg/analysis_server/lib/src/services/correction/error_fix_status.yaml...
01:27 +1594: All tests passed!  
```
See: #4404 
=> tidy shared test setup

CHANGELOG.md, pubspec.yaml
Removes the `version` from our pubspec and updates the changelog to a new scheme based on 3.1.0 (the next stable Dart version).
My thinking is we do not need to suffix this with `-dev` since we're not really using semver and don't see the value of a suffix that we'll have to remember to update.
Very open to input though.
See: #4389
/cc @bwilkerson @natebosch @devoncarew
=> move to new "versioning" scheme

CONTRIBUTING.md, doc/lint-lifecycle.md
Some notes on `CHANGELOG` updates.
In support of https://github.com/dart-lang/linter/issues/4389.
=> + changelog process notes

tool/doc.dart, tool/machine.dart, tool/scorecard.dart, tool/since.dart
The linter version cache is still required to lookup corresponding Dart SDKs but this at least stops putting the version in the documentation. (Removes the stale "maturity" field from `rules.json` too.)
Fixes #4432
/cc @bwilkerson @parlough
=> stop documenting "since" linter versions

lib/src/rules/use_build_context_synchronously.dart, test/rules/use_build_context_synchronously_test.dart, test_data/rules/use_build_context_synchronously.dart
Many of the tests already have equivalent reflective tests, so they are just deleted.
But the try/catch tests, when improving them for reflective tests, found some bugs in `AsyncVisitor.visitTryStatement`, so the impl is changed to fix those:
* a BuildContext reference _found in a finally-block_ is not guarded by any "if not mounted then exit" in the try-body; any such check is not guaranteed to be run before the code in the finally.
* a BuildContext reference _found after a try/catch/finally_ is not guarded by any "if not mounted then exit" in the try-body; any such check is not guaranteed to be run before the code in the finally.
CC @pq @keertip
=> Move many use_build_context_synchronously tests to reflective

CHANGELOG.md
As per new CHANGELOG policy, keep it lean (only lint adds, removes, and deprecations).
See: #4389
/cc @scheglov
=> remove fix entry

lib/src/rules/use_build_context_synchronously.dart, test/rules/use_build_context_synchronously_test.dart
In a while loop, an async gap that comes _after_ a BuildContext reference should be reported!
Statements that precede a BuildContext reference can guard it with a mounted check, but not statements that follow the BuildContextReference.
In order to accomplish this, note that a _lot_ of the complexity in `check()` is moved to the `_AsyncStateVisitor`, mostly in `visitBlock`. I think it is a big benefit to make `check()` simpler, when it comes to special treatment of parent node types.
CC @keertip
=> use_build_context: Fix a failing test regarding the looping of while loops

lib/src/rules/unreachable_from_main.dart, test/rules/unreachable_from_main_test.dart
When applied to `analyzer/`, `analysis_server`, etc found a handful of violations.
https://dart-review.googlesource.com/c/sdk/+/307975
=> [unreachable_from_main] Support for instance members.

tool/changelog.dart, tool/rule.dart, tool/since.dart
Taking automation nearly as far as we can go... This updates `rule.dart` to generate a `CHANGELOG` entry and update the since SDK version map.
Sample run:
```
☁  linter [main] ⚡  dart tool/rule.dart -n foo_bar
Writing to ./lib/src/rules/foo_bar.dart
Writing to ./test/rules/foo_bar_test.dart
Writing to ./test/rules/all.dart
Writing to ./example/all.yaml
Updating tool/since/sdk.yaml
Updating CHANGELOG.md
Writing to ./lib/src/rules.dart
A unit test has been stubbed out in:
test/rules/foo_bar_test.dart
```
/fyi @parlough
=> rule.dart: auto-gen changelog and since map entries

lib/src/rules/use_build_context_synchronously.dart, test/rules/use_build_context_synchronously_test.dart, test_data/rules/use_build_context_synchronously.dart
* Properly support `await`s in CatchClauses.
* Other correctness fixes for TryStatements, with new tests.
* Properly support `await`s in ConditionalExpressions and IfElements.
* Support WhenGuards with mounted guards, which can guard statements in a SwitchPatternCase.
* Remove all special casing in `check()`; we just unconditionally move to each parent, and check the async state.
* Move some ForStatement tests from the integration style to the reflective style.
=> Many small improvements to use_build_context_synchronously

lib/src/rules/unreachable_from_main.dart, test/rules/unreachable_from_main_test.dart
When looking at a NamedType, if it is found in the return type of an external member, call it reachable.
Fixes #4474
=> Mark types of external declarations as "reachable"

lib/src/rules/use_build_context_synchronously.dart, test/rules/use_build_context_synchronously_test.dart
We correctly handle more cases in switch-default blocks, and switch when-clauses.
=> use_build_context_synchronously: Fix a few TODOs

lib/src/rules/unreachable_from_main.dart, test/rules/unreachable_from_main_test.dart
Since classes in type arguments can affect compile-time errors, they can have "side effects" even without instantiation. I guess its a valid use of a class.
Fixes #4471
=> consider referencing a type in a type argument as 'usage'

lib/src/rules/use_build_context_synchronously.dart, test/rules/use_build_context_synchronously_test.dart
The issue here is that use-of-context inside await is "uninteresting."  Like in `await Future.value(context)`. However, this calculation gets messed up when the await is inside a broader expression, like `var x = await Future.value(context)`. In the existing code, we see that the await (parent of `Future.value(context)`) has no interesting async state with that chid, and go up a level, then we see that `var x = await ...` has an `await`! So the state is `AsyncState.asynchronous`.
The fix is to cache the uninteresting state. There are doc comments validating the cache idea.
This cache can be used in the future to improve performance.
Fixes #4472
=> use_build_context_synchronously: Fix context-in-await cases

tool/move_legacy_test.dart
This introduces a command line tool which hastens the process of converting a legacy test data file into a reflective test.
It is interactive, presenting the legacy file, and asking for what snippets should be called out as individual test cases. Here is a sample run:
```none
$ dart tool/move_legacy_test.dart avoid_single_cascade_in_expression_statements
0  // Copyright (c) 2018, the Dart project authors. Please see the AUTHORS file
1  // for details. All rights reserved. Use of this source code is governed by a
2  // BSD-style license that can be found in the LICENSE file.
3
4  // test w/ `dart test -N avoid_single_cascade_in_expression_statements`
5
6  main(){
7    var o;
8    o..toString(); // LINT
9    o..toString()..toString(); // OK
10    f(o..toString()); // OK
11 …
```
=> New tool for moving legacy tests quickly

tool/move_legacy_test.dart
This fixes a little issue when migrating a large file that needs to scroll; I had never tested this range-updating logic 😅
=> Fix range-setting in move_legacy_test

index.html
Followup to https://github.com/dart-lang/linter/pull/4504 since the home page is not generated, and just lives in the `gh-pages` branch.
Contributes to https://github.com/dart-lang/linter/issues/4460 and https://github.com/dart-lang/site-www/issues/4499
=> Redirect gh-pages homepage to dart.dev

lib/src/rules/avoid_return_types_on_setters.dart, lib/src/rules/curly_braces_in_flow_control_structures.dart, lib/src/rules/prefer_generic_function_type_aliases.dart, lib/src/rules/slash_for_doc_comments.dart, lib/src/rules/unnecessary_const.dart, lib/src/rules/unnecessary_new.dart, lib/src/rules/unnecessary_string_escapes.dart, lib/src/rules/use_function_type_syntax_for_parameters.dart
This will override a getter in the base class `LintRule` when the analyzer package is upgraded. These changes are part of the work for adding a lightweight parse only mode to dart fix.
=> Add a getter to lint rules that can work with just a parsed AST.

pubspec.yaml
Without publishing, these links aren't useful, plus removes a link to the old linter site.
=> Remove irrelevant pubspec links

lib/src/rules/library_private_types_in_public_api.dart, test/rules/library_private_types_in_public_api_test.dart
=> fix `library_private_types_in_public_api` overreporting on enum constructor params

lib/src/rules/unnecessary_parenthesis.dart, test_data/rules/unnecessary_parenthesis.dart
Fixes a few false ~~positives~~ negatives that I noticed when mass-editing code and gratuitously sprinkling parentheses everywhere
=> Report unnecessary_parenthesis around Literal and PrefixedIdentifier

lib/src/rules/prefer_spread_collections.dart, pubspec.yaml, test/rules/deprecated_member_use_from_same_package_test.dart, test/rules/unnecessary_this_test.dart
Fixes #4381
Newly failing tests tracked in: #4541.
=> analyzer 6.0.0

lib/src/rules/use_build_context_synchronously.dart, test/rules/use_build_context_synchronously_test.dart, test_data/rules/use_build_context_synchronously.dart
If an `await` is found in a for-statement or a do-statement (or a while-statement, already implemented), even if it is _after_ a reference to a BuildContext, the reference is not safe. This implements that behavior.
There are new unit tests, and some legacy tests are moved.
=> use_build_context_synchronously: handle asynchrony in for- and do-statements better

lib/src/rules/directives_ordering.dart, test/rules/directives_ordering_test.dart
It sorts imports as follows:
```dart
import './foo1.dart';
import '../../foo2.dart';
import '../foo3.dart';
import 'foo4.dart';
```
This change corrects it to the following:
```dart
import '../../foo1.dart';
import '../foo2.dart';
import './foo3.dart';
import 'foo4.dart';
```
Fixes #2678
See https://github.com/dart-lang/linter/issues/2678#issuecomment-1610144987 for an explanation on how this edit relates to the behavior
=> Fix directives_ordering for a leading dot in path

analysis_options.yaml, tool/doc.dart
This PR will regenerate each page with textual directions pointing and linking to the new documentation. It should likely never be seen due to the redirects created in https://github.com/dart-lang/linter/pull/4504, however it acts as a backup in case a client doesn't support those for some reason. It also removes unnecessary doc generation code that is no longer used after these changes.
After this lands and the pages on `gh-pages` are updated, this generation logic can be _(mostly)_ removed.
Contributes to https://github.com/dart-lang/linter/issues/4460#issuecomment-1595810116
=> Leave backup text crumbs pointing to new docs

analysis_options.yaml, test/rule_test.dart, tool/scorecard.dart
It has been quite useful when removing old/stale functionality, especially in `/tool`.
=> Enable `unreachable_from_main` linter rule

test/rules/use_late_for_private_fields_and_variables_test.dart
This no longer reproduces. Test added.
Fixes #3823
=> `use_late_for_private_fields_and_variables` enum test case

test/rules/use_late_for_private_fields_and_variables_test.dart
=> `use_late_for_private_fields_and_variables` part of test

test/all.dart, test/verify_machine_json_test.dart, tool/machine.dart, tool/machine/rules.json
Fixes #4587
@parlough: let me know if this is what you had in mind?
=> write and verify `rules.json`

.gitignore, README.md, index.html, lints/use_super_initializers.html, styles.css
- Adds a README redirecting to dart.dev
- Adjust/simplify index page to match others
- Simplifies styles so only ones still used for fallback text remain, allowing for quicker page loading.
- Manually redirect old [`use_super_initializers` page](https://dart-lang.github.io/linter/lints/use_super_initializers) to new `use_super_parameters` page. It was renamed before being released, resulting in an isolated page that wasn't updated.
Closes https://github.com/dart-lang/linter/issues/4460
=> Finalize retirement of gh-pages branch

lib/src/ast.dart, lib/src/extensions.dart, lib/src/rules/public_member_api_docs.dart, test/rules/public_member_api_docs_test.dart
Fixes #https://github.com/dart-lang/linter/issues/4650
=> extension type support for `public_member_api_docs`

analysis_options.yaml, lib/src/rules/avoid_web_libraries_in_flutter.dart, test/verify_machine_json_test.dart, tool/labeler/issue_config.dart, tool/labeler/pr_config.dart, tool/machine.dart
To ease transition to the SDK and for consistency, adds a few linter rules enabled on the [analyzer](https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/analysis_options.yaml) and the [analysis_server](https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/analysis_options.yaml).
The only lint that triggered is `avoid_dynamic_calls`, so this PR fixes those.
=> Enable more lints used in sdk analysis packages

CHANGELOG.md, tool/machine/rules.json, tool/since/sdk.yaml
Some of this is replicated from the `1.35.0` section, but there were linter rules added after `1.35.0` but before the linter commit included in Dart 3, which were missing from the changelog completely: `matching_super_parameters` and `no_literal_bool_comparisons`.
To clearly indicate to users all of the lints that were added and removed, I added an entry for 3.0.0 including both those already included and missing previously. This has the added benefit of beginning the new style with a full major version :)
=> Account for missing lints in changelog

lib/src/rules/prefer_constructors_over_static_methods.dart, test/rules/prefer_constructors_over_static_methods_test.dart
Fixes #4679
(Sorry for the sorting churn; will be nice to add this code to sort verification in analyzer sooner than later!)
=> extension type support for `prefer_constructors_over_static_methods`

lib/src/rules/sort_constructors_first.dart, test/rules/sort_constructors_first_test.dart
=> extension type support for `sort_constructors_first`

test/rules/hash_and_equals_test.dart
=> extension type support for `hash_and_equals`

lib/src/rules/use_late_for_private_fields_and_variables.dart, test/rules/use_late_for_private_fields_and_variables_test.dart
=> extension type support for `use_late_for_private_fields_and_variables`

lib/src/rules/sort_unnamed_constructors_first.dart, test/rules/sort_unnamed_constructors_first_test.dart
=> extension type support for `sort_unnamed_constructors_first`

lib/src/rules/unnecessary_constructor_name.dart, test/rules/unnecessary_constructor_name_test.dart
=> extension type support for `unnecessary_constructor_name`

lib/src/rules/avoid_shadowing_type_parameters.dart, test/rules/avoid_shadowing_type_parameters_test.dart
This reverts commit e32b6e9817789374dc38bc2a3603c0bcf3970bee.
(Accidental un-reviewed commit to main.)
=> Revert "extension type support for `avoid_shadowing_type_parameters`"

lib/src/rules/avoid_shadowing_type_parameters.dart, test/rules/avoid_shadowing_type_parameters_test.dart
=> extension type support for `avoid_shadowing_type_parameters`

lib/src/rules/non_constant_identifier_names.dart, test/rules/non_constant_identifier_names_test.dart
=> extension type support for `non_constant_identifier_names`

README.md
Contributes to https://github.com/dart-lang/linter/issues/4411
Closes https://github.com/dart-lang/linter/issues/4707 
Redirects contributions to the appropriate repository.
=> Call out move in README

CONTRIBUTING.md
Redirect potential contributors to the linter's new home in the Dart SDK.
/cc @jacob314 @parlough @bwilkerson
=> Point to SDK contributing guide
