- lib/src/analysis.dart
- lib/src/rules/package_prefixed_library_names.dart
- lib/src/rules/pub/package_names.dart
- test/linter_test.dart
- tool/doc.dart
- tool/rule.dart
> Library name fixes.

- lib/src/formatter.dart
- pubspec.yaml
@bwilkerson PTAL.  (And thanks again for the fix!)
> Raw multiline string workaround cleanup.

- lib/src/rules/camel_case_types.dart
- lib/src/rules/constant_identifier_names.dart
- lib/src/rules/empty_constructor_bodies.dart
- lib/src/rules/library_names.dart
- lib/src/rules/library_prefixes.dart
- lib/src/rules/non_constant_identifier_names.dart
- lib/src/rules/one_member_abstracts.dart
- lib/src/rules/package_prefixed_library_names.dart
- lib/src/rules/pub/package_names.dart
- lib/src/rules/slash_for_doc_comments.dart
- lib/src/rules/super_goes_last.dart
- lib/src/rules/type_init_formals.dart
- lib/src/rules/unnecessary_brace_in_string_interp.dart
- lib/src/rules/unnecessary_getters.dart
- lib/src/rules/unnecessary_getters_setters.dart
@lukechurch : for your enjoyment.
> Lint message softening.

- lib/src/io.dart
- lib/src/linter.dart
- lib/src/pub.dart
- lib/src/rules/pub/package_names.dart
- test/_data/p3/_pubspec.yaml
- test/integration_test.dart
- test/linter_test.dart
- test/mocks.dart
- test/pub_test.dart
> Pubspec parsing error handling; name cleanup.

- pubspec.yaml
> Bumped analyzer constraint.

- bin/linter.dart
- lib/src/analysis.dart
- test/_data/p4/lib/lib1.dart
- test/_data/p4/lib/lib2.dart
- test/_data/p4/lib/lib3.dart
- test/integration_test.dart
> Analyze lib files by package uri

- bin/linter.dart
- lib/src/formatter.dart
- test/formatter_test.dart
> Machine output. Fix #69.

- CHANGELOG.md
- pubspec.yaml
> V0.2.0+1 bump

- lib/src/analysis.dart
- lib/src/ast.dart
- lib/src/linter.dart
- lib/src/project.dart
- lib/src/rules.dart
- lib/src/rules/package_api_docs.dart
- test/_data/p2/src/a.dart
- test/all.dart
- test/integration_test.dart
- test/project_test.dart
- test/rules/package_api_docs.dart
Rough but ready for iterating.
> API doc tracking; project model WIP.

- test/all.dart
@stereotype441 
Nothing fancy but useful for getting a quick read on test elapsed time.
> Test timing.

- lib/src/linter.dart
- lib/src/rules/camel_case_types.dart
- lib/src/rules/constant_identifier_names.dart
- lib/src/rules/empty_constructor_bodies.dart
- lib/src/rules/library_names.dart
- lib/src/rules/library_prefixes.dart
- lib/src/rules/non_constant_identifier_names.dart
- lib/src/rules/one_member_abstracts.dart
- lib/src/rules/package_api_docs.dart
- lib/src/rules/package_prefixed_library_names.dart
- lib/src/rules/pub/package_names.dart
- lib/src/rules/slash_for_doc_comments.dart
- lib/src/rules/super_goes_last.dart
- lib/src/rules/type_init_formals.dart
- lib/src/rules/unnecessary_brace_in_string_interp.dart
- lib/src/rules/unnecessary_getters.dart
- lib/src/rules/unnecessary_getters_setters.dart
- test/linter_test.dart
- tool/doc.dart
> Style updates WIP.

- lib/src/linter.dart
- lib/src/rules/camel_case_types.dart
- lib/src/rules/constant_identifier_names.dart
- lib/src/rules/empty_constructor_bodies.dart
- lib/src/rules/library_names.dart
- lib/src/rules/library_prefixes.dart
- lib/src/rules/non_constant_identifier_names.dart
- lib/src/rules/one_member_abstracts.dart
- lib/src/rules/package_api_docs.dart
- lib/src/rules/package_prefixed_library_names.dart
- lib/src/rules/pub/package_names.dart
- lib/src/rules/slash_for_doc_comments.dart
- lib/src/rules/super_goes_last.dart
- lib/src/rules/type_init_formals.dart
- lib/src/rules/unnecessary_brace_in_string_interp.dart
- lib/src/rules/unnecessary_getters.dart
- lib/src/rules/unnecessary_getters_setters.dart
- test/linter_test.dart
- tool/doc.dart
@keertip 
**TL;DR** removes notion of kinds (DO, DONT, PREFER, etc) in favor of the idea that rules will be either enabled or not.
> Bye by kinds.  Fix #78.

- .travis.yml
> Added sudo:false

- pubspec.yaml
> Constraint fix.

- pubspec.yaml
> Relaxed constraints (to play nice with SDK third_party).

- pubspec.yaml
> Version bump.

- lib/src/linter.dart
- test/linter_test.dart
> Add `errors` to builtin groups.

- lib/src/linter.dart
> Const fix.

- lib/plugin/linter.dart
- lib/src/plugin/linter_plugin.dart
- pubspec.yaml
- test/linter_test.dart
> Plugin babysteps.

- lib/src/config.dart
- lib/src/linter.dart
- lib/src/plugin/linter_plugin.dart
- lib/src/rules.dart
- pubspec.yaml
- test/all.dart
- test/config_test.dart
- test/linter_test.dart
- test/mocks.dart
- test/plugin_test.dart
This integrates the linter with the analyzer's options mechanism.
> Analysis options integration.

- CHANGELOG.md
- pubspec.yaml
> Version bump and CHANGELOG updates.

- README.md
- appveyor.yml
> appveyor support (fix #116).

- lib/src/rules/unnecessary_brace_in_string_interp.dart
- test/rules/unnecessary_brace_in_string_interp.dart
> Update unnecessary brace checking (Fixes #112).

- CHANGELOG.md
- pubspec.yaml
> Version bump pre publish.

- .gitignore
> Ignore .packages.

- lib/src/util.dart
- test/pub_test.dart
> Windows test fixes.

- test/linter_test.dart
> Test path fix [TBR].

- lib/src/linter.dart
> Tracing out to debug windows tests.

- CHANGELOG.md
- pubspec.yaml
> Bump to 0.1.3 [TBR].

- pubspec.yaml
> Bump markdown dep.

- lib/src/rules.dart
- lib/src/rules/overriden_field.dart
- test/rules/overriden_field.dart
BUG=https://github.com/dart-lang/sdk/issues/25567
LGTMed Code review https://codereview.chromium.org/1870423002
> Hint if a field overrides or hides other field.

- lib/src/rules.dart
- lib/src/rules/equals_test_argument_type.dart
- test/rules/equals_test_argument_type.dart
LGTMed code review https://codereview.chromium.org/1880163002
> Lint rule: Always test type arguments in operator ==(Object other).

- lib/src/rules.dart
- lib/src/rules/await_only_future.dart
- test/rules/await_only_future.dart
BUG=https://github.com/dart-lang/sdk/issues/26065
#26065
lgtmed  CL https://codereview.chromium.org/1886173004
> Lint rule: Await only futures.

- lib/src/rules.dart
- lib/src/rules/no_control_flow_in_finally_block.dart
- lib/src/rules/no_throw_in_finally_block.dart
- test/rules/no_control_flow_in_finally_block.dart
- test/rules/no_throw_in_finally_block.dart
Code review https://codereview.chromium.org/1879343002
> Lint rule: Avoid flow control in finally block.

- lib/src/rules/unnecessary_brace_in_string_interp.dart
- test/rules/unnecessary_brace_in_string_interp.dart
> Don't lint braces on string interpolation if identifier starts with $.

- lib/src/rules.dart
- lib/src/rules/dont_compare_unrelated_types_for_equality.dart
- test/rules/dont_compare_unrelated_types_for_equality.dart
> Equality operator (==) invocation with references of unrelated types

- lib/src/rules.dart
- lib/src/rules/cancel_subscriptions.dart
- lib/src/rules/iterable_contains_unrelated_type.dart
- lib/src/rules/unrelated_type_equality_checks.dart
- lib/src/util/dart_type_utilities.dart
- lib/src/util/leak_detector_visitor.dart
- test/_data/cancel_subscriptions/cancel_subscriptions.dart
- test/integration_test.dart
In the same spirit that https://github.com/dart-lang/linter/pull/241 perform a check for dart.async.StreamSubscription.
> Cancel subscriptions

- lib/src/rules.dart
- lib/src/rules/only_throw_error.dart
- lib/src/util/dart_type_utilities.dart
- test/_data/only_throw_error/only_throw_error.dart
- test/integration_test.dart
> Only throw instances of dart:core.Error

- lib/src/rules/overridden_fields.dart
- test/rules/overridden_fields.dart
> Do not lint overriding static fields.

- tool/grind.dart
> Fix compilation errors

- lib/src/rules.dart
- lib/src/rules/parameter_assignments.dart
- lib/src/rules/prefer_final_fields.dart
- lib/src/rules/prefer_final_locals.dart
- test/integration_test.dart
- test/rules/parameter_assignments.dart
- test/rules/prefer_final_fields.dart
- test/rules/prefer_final_locals.dart
> New rule: Prefer final for variable declaration if reference is not reassigned.

- lib/src/rules.dart
- lib/src/rules/cascade_invocations.dart
- test/rules/cascade_invocations.dart
Cascade consecutive method invocations on the same reference.
> New rule: cascade_invocations.

- CHANGELOG.md
- pubspec.yaml
Fixes: #327.
/cc @bwilkerson @alexeieleusis
> Linter `0.1.29` (#327).

- lib/src/rules/invariant_booleans.dart
- test/rules/invariant_booleans.dart
Fixes https://github.com/dart-lang/linter/issues/357
> invariant_booleans:  Fix false positive for null aware test.

- lib/src/rules/invariant_booleans.dart
Reviewed: https://codereview.chromium.org/2618833002/
> Fix invariant_boolean, invariant_booleans mismatch.

- test/rules/invariant_booleans.dart
Verifies https://github.com/dart-lang/linter/issues/371
> invariant_booleans: Added test case for unreproducible bug.

- lib/src/rules/invariant_booleans.dart
- test/rules/invariant_booleans.dart
Verifies https://github.com/dart-lang/linter/issues/368 which I could not reproduce even after reviewing the code where the rule was triggering.
Changed maturity type for rule so it gets reported on CI servers (that ignore experimental).
> Verify unreproducible bug

- pubspec.yaml
> Update to analyzer 0.29.6.

- lib/src/util/tested_expressions.dart
I found myself confused when fixing
https://github.com/dart-lang/linter/issues/373
so I rearranged it trying to make it easier to understand the next time
someone has to work on it.
> Cleanup to make code more readable.

- lib/src/rules/prefer_is_empty.dart
Avoid reaching into analyzer source implementation.
@bwilkerson @dikmax
> Fix up analyzer API accesses.

- .analysis_options
- tool/rule.dart
Some are commented out because are too new.
> Enable a few more lints.

- AUTHORS
Adds @dikmax 👍 
Maxim: is this a good email?  (I got it from your github profile.)
@alexeieleusis @bwilkerson
> Update AUTHORS [TBR]

- .analysis_options
- lib/src/rules.dart
- lib/src/rules/prefer_const_constructors.dart
- test/rules/prefer_const_constructors.dart
* import cleanup
* rename `prefer_const_constructor` => `prefer_const_constructors`
* turn on `prefer_const_constructors`
@bwilkerson @dikmax
> Flip on `prefer_const_constructors`.

- README.md
Fixes: #393 
@bwilkerson 
FYI @filiph
> Update docs to recommend analyzer CLI (#393).

- lib/src/rules.dart
- lib/src/rules/unnecessary_null_in_if_null_operator.dart
- test/rules/unnecessary_null_in_if_null_operator.dart
> Avoid null as operand in if null operator

- CONTRIBUTING.md
Part of #416.
* improve git flow instructions
* add review protocol
* add note about "WIP" conventions
@filiph @bwilkerson
> Update contributing docs (#416).

- tool/rule.dart
Some cleanup in the stub generation:
* Unify the two nearly identical stub generators.
* Check if a file already exists before writing.
* Fix the stub to use the right imports, and privatize top-level variables.
> Don't overwrite existing files with the stub generator

- README.md
- doc/WritingLints.MD
Doc tweaks.
* add a few notes on test running
* add a link to the contributing lints doc to the main README
@srawlins @bwilkerson
> Update docs with notes on running tests.

- doc/WritingLints.MD
Adds details on
* travis test running
* solo test debugging
* AST spelunking
@bwilkerson
> More writing lints details [TBR].

- doc/WritingLints.MD
Fixes: #416.
Elaboration and word-smithing welcome.
@bwilkerson
> Analyzer API advice (#416) [TBR].

- lib/src/rules.dart
- lib/src/rules/recursive_getters.dart
- lib/src/rules/unnecessary_brace_in_string_interps.dart
- lib/src/rules/unnecessary_null_aware_assignments.dart
- lib/src/rules/unnecessary_null_in_if_null_operators.dart
Some rule name cleanup to stay (more) consistent with existing rules.
@bwilkerson 
FYI @alexeieleusis @JPaulsen
> Rule name cleanup (pre-publish).

- lib/src/rules.dart
- lib/src/rules/use_collection_literals_when_possible.dart
- test/_data/use_collection_literals_when_possible/test.dart
- test/integration_test.dart
Fixes https://github.com/dart-lang/linter/issues/455
> Use collection literals when possible

- lib/src/rules.dart
- lib/src/rules/use_function_declaration_instead_of_variable.dart
- test/rules/use_function_declaration_instead_of_variable.dart
Fixes https://github.com/dart-lang/linter/issues/459
> New rule: use_function_declaration_instead_of_variable

- lib/src/rules.dart
- lib/src/rules/use_expression_function_body_when_possible.dart
- test/rules/use_expression_function_body_when_possible.dart
Fixes https://github.com/dart-lang/linter/issues/463
> New rule: use_expression_function_body_when_possible

- lib/src/rules.dart
- lib/src/rules/omit_local_variable_types.dart
- lib/src/util/dart_type_utilities.dart
- test/rules/omit_local_variable_types.dart
Fixes https://github.com/dart-lang/linter/issues/461
> New rule: omit_local_variable_types

- lib/src/rules.dart
- lib/src/rules/unnecessary_lambdas.dart
- test/rules/unnecessary_lambdas.dart
Fixes https://github.com/dart-lang/linter/issues/466
> New rule: unnecessary_lambdas

- lib/src/rules/invariant_booleans.dart
Fixes: #476.
@bwilkerson @alexeieleusis @JPaulsen
> Update invariant_booleans docs (#476).

- lib/src/rules.dart
- lib/src/rules/use_initializing_formals_when_possible.dart
- test/rules/use_initializing_formals_when_possible.dart
Fixes https://github.com/dart-lang/linter/issues/471
> New rule: use_initializing_formals_when_possible

- lib/src/rules/unnecessary_lambdas.dart
- test/rules/unnecessary_lambdas.dart
Fixes https://github.com/dart-lang/linter/issues/473
Fix: Do not lint when the method invocation in the lambda has any type of function invocation (including constructors and methods) in the target or a non final field or variable, so the lambda has not the same behavior than the tear-off
> Fix rule: unnecessary_lambdas

- CHANGELOG.md
> Changelog for `0.1.30` (#477).

- lib/src/rules/prefer_initializing_formals.dart
- lib/src/util/dart_type_utilities.dart
- test/rules/prefer_initializing_formals.dart
Fixes https://github.com/dart-lang/linter/issues/493
> Fix rule: prefer_initializing_formals

- lib/src/rules.dart
- lib/src/rules/unnecessary_this.dart
- test/rules/unnecessary_this.dart
Fixes https://github.com/dart-lang/linter/issues/469
> New rule: unnecessary_this.

- lib/src/rules/prefer_interpolation_to_compose_strings.dart
Improve benchmark on this rule from ~100-200 ms to 5 ms in my machine
> Improve performance: prefer_interpolation_to_compose_strings

- lib/src/util/dart_type_utilities.dart
Fixes https://github.com/dart-lang/linter/issues/504
> Fix util method: traverseNodesInDFS

- lib/src/rules/prefer_final_fields.dart
- lib/src/util/dart_type_utilities.dart
- test/rules/prefer_final_fields.dart
Fixes https://github.com/dart-lang/linter/issues/506
> Fix rule: prefer_final_fields

- lib/src/rules/unnecessary_this.dart
- test/rules/unnecessary_this.dart
Fixes https://github.com/dart-lang/linter/issues/502
> Fix rule: unnecessary_this

- lib/src/rules/literal_only_boolean_expressions.dart
- lib/src/util/dart_type_utilities.dart
Fixes https://github.com/dart-lang/linter/issues/505
Fixes https://github.com/dart-lang/linter/issues/513
> Improve performance: traverseNodesInDfs and literal_only_boolean_expressions

- lib/src/rules/invariant_booleans.dart
- lib/src/util/condition_scope_visitor.dart
- lib/src/util/dart_type_utilities.dart
- test/rules/invariant_booleans.dart
Fixes https://github.com/dart-lang/linter/issues/434
> Improve performance: invariant_booleans

- lib/src/rules.dart
- lib/src/rules/use_rethrow_when_possible.dart
- test/rules/use_rethrow_when_possible.dart
Fixes https://github.com/dart-lang/linter/issues/518
> New rule: use_rethrow_when_possible

- lib/src/rules.dart
- lib/src/rules/do_not_catch_errors.dart
- test/mock_sdk.dart
- test/rules/do_not_catch_errors.dart
Fixes https://github.com/dart-lang/linter/issues/520
Fixes https://github.com/dart-lang/linter/issues/526
> New rule: do_not_catch_errors

- lib/src/rules.dart
- lib/src/rules/avoid_catches_without_on_clauses.dart
- test/rules/avoid_catches_without_on_clauses.dart
Fixes https://github.com/dart-lang/linter/issues/522
> New rule: avoid_catches_without_on_clauses

- lib/src/rules.dart
- lib/src/rules/do_not_check_for_null_in_equality_operators.dart
- test/rules/do_not_check_for_null_in_equality_operators.dart
Fixes https://github.com/dart-lang/linter/issues/528
> New rule: do_not_check_for_null_in_equality_operators

- lib/src/rules.dart
- lib/src/rules/avoid_classes_with_only_static_members.dart
- test/rules/avoid_classes_with_only_static_members.dart
Fixes https://github.com/dart-lang/linter/issues/539
> New rule: avoid_classes_with_only_static_members

- lib/src/rules.dart
- lib/src/rules/avoid_returning_null.dart
- test/rules/avoid_returning_null.dart
Fixes https://github.com/dart-lang/linter/issues/541
> New rule: avoid_returning_null

- lib/src/rules.dart
- lib/src/rules/prefer_constructors_instead_of_static_methods.dart
- test/rules/prefer_constructors_instead_of_static_methods.dart
Fixes https://github.com/dart-lang/linter/issues/535
> New rule: prefer_constructors_instead_of_static_methods

- lib/src/rules.dart
- lib/src/rules/avoid_annotating_with_dynamic.dart
- test/rules/avoid_annotating_with_dynamic.dart
Fixes https://github.com/dart-lang/linter/issues/550
> New rule: avoid_annotating_with_dynamic

- lib/src/rules.dart
- lib/src/rules/avoid_returning_this.dart
- lib/src/util/dart_type_utilities.dart
- test/rules/avoid_returning_this.dart
Fixes https://github.com/dart-lang/linter/issues/552
> New rule: avoid_returning_this

- test/rules/avoid_returning_this.dart
Fixes https://github.com/dart-lang/linter/issues/558
> Improve test coverage: avoid_returning_this

- lib/src/rules.dart
- lib/src/rules/use_setters_to_change_a_property.dart
- test/rules/use_setters_to_change_a_property.dart
Fixes https://github.com/dart-lang/linter/issues/548
> New rule: use_setters_to_change_a_property

- lib/src/rules/avoid_returning_this.dart
- test/rules/avoid_returning_this.dart
Fixes https://github.com/dart-lang/linter/issues/560
> Fix rule: avoid_returning_this

- lib/src/rules.dart
- lib/src/rules/prefer_expression_function_bodies.dart
Fixes https://github.com/dart-lang/linter/issues/563
> Fix typo in rule: prefer_expression_function_bodies

- lib/src/rules.dart
- lib/src/rules/avoid_types_on_closure_parameters.dart
- test/rules/avoid_types_on_closure_parameters.dart
Fixes https://github.com/dart-lang/linter/issues/543
> New rule: avoid_types_on_closure_parameters

- lib/src/rules.dart
- lib/src/rules/prefer_conditional_assignment.dart
- test/rules/prefer_conditional_assignment.dart
Fixes https://github.com/dart-lang/linter/issues/483
> New rule: prefer_conditional_assignment

- lib/src/rules/use_setters_to_change_a_property.dart
Fixes https://github.com/dart-lang/linter/issues/565
> Fix lint in rule: use_setters_to_change_a_property

- lib/src/rules.dart
- lib/src/rules/avoid_positional_boolean_parameters.dart
- test/rules/avoid_positional_boolean_parameters.dart
Fixes https://github.com/dart-lang/linter/issues/531
> New rule: avoid_positional_boolean_parameters

- lib/src/rules.dart
- lib/src/rules/do_not_create_setter_without_getter.dart
- lib/src/util/dart_type_utilities.dart
- test/rules/do_not_create_setter_without_getter.dart
Fixes https://github.com/dart-lang/linter/issues/571
> New rule: do_not_create_setter_without_getter

- lib/src/rules.dart
- lib/src/rules/use_to_and_as_if_applicable.dart
- lib/src/util/dart_type_utilities.dart
- test/rules/use_to_and_as_if_applicable.dart
Fixes https://github.com/dart-lang/linter/issues/580
Fixes https://github.com/dart-lang/linter/issues/581
And also is relevant to https://github.com/dart-lang/linter/issues/573
> New rule: use_to_and_as_if_applicable

- lib/src/rules/omit_local_variable_types.dart
- test/rules/omit_local_variable_types.dart
Fixes https://github.com/dart-lang/linter/issues/585
> Fix rule: omit_local_variable_types

- lib/src/rules/do_not_check_for_null_in_equality_operators.dart
- lib/src/rules/literal_only_boolean_expressions.dart
- lib/src/rules/prefer_conditional_assignment.dart
- lib/src/util/condition_scope_visitor.dart
- lib/src/util/dart_type_utilities.dart
Fixes https://github.com/dart-lang/linter/issues/584
> Fix efficient unparenthesized

- lib/src/rules/always_require_non_null_named_parameters.dart
- lib/src/rules/avoid_init_to_null.dart
- lib/src/rules/avoid_returning_null.dart
- lib/src/rules/do_not_check_for_null_in_equality_operators.dart
- lib/src/rules/prefer_conditional_assignment.dart
- lib/src/rules/unnecessary_null_aware_assignments.dart
- lib/src/rules/unnecessary_null_in_if_null_operators.dart
- lib/src/rules/unrelated_type_equality_checks.dart
- lib/src/util/dart_type_utilities.dart
Fixes https://github.com/dart-lang/linter/issues/598
> Promote isNullLiteral

- lib/src/rules/await_only_futures.dart
- test/rules/await_only_futures.dart
> Extend await_only_futures to include FutureOr

- lib/src/rules/literal_only_boolean_expressions.dart
- lib/src/rules/omit_local_variable_types.dart
- lib/src/util/condition_scope_visitor.dart
Fixes https://github.com/dart-lang/linter/issues/604
> Quick fix: calling getters in null.

- lib/src/rules/always_put_control_body_on_new_line.dart
- test/rules/always_put_control_body_on_new_line.dart
> handle else if in always_put_control_body_on_new_line

- lib/src/util/leak_detector_visitor.dart
This rule has 2 lints in the the project
> Delint lint: prefer_final_fields

- lib/src/rules/omit_local_variable_types.dart
- lib/src/util/dart_type_utilities.dart
- test/rules/omit_local_variable_types.dart
From https://github.com/dart-lang/linter/pull/618#issuecomment-295479210
> Fix rule: omit_type_for_local_variables

- lib/src/rules.dart
- lib/src/rules/use_string_buffer.dart
- test/rules/use_string_buffer.dart
17 lints in the sdk no false positives.
It is linting the left part of assignations that could be replaced by a buffer.write(something);
> New rule: use_string_buffer

- lib/src/rules/avoid_function_literals_in_foreach_calls.dart
Fixes https://github.com/dart-lang/linter/issues/631
> Fix linted node: avoid_function_literals_in_foreach_calls

- test/rules/always_put_control_body_on_new_line.dart
Addresses https://github.com/dart-lang/linter/pull/609#discussion_r111778339
> add test for always_put_control_body_on_new_line

- lib/src/rules/cascade_invocations.dart
- test/rules/cascade_invocations.dart
Fixes https://github.com/dart-lang/linter/issues/339
Fixes https://github.com/dart-lang/linter/issues/340
Fixes https://github.com/dart-lang/linter/issues/606
> Fix rule: cascade_invocations

- lib/src/rules/avoid_types_on_closure_parameters.dart
- test/rules/avoid_types_on_closure_parameters.dart
Fixes https://github.com/dart-lang/linter/issues/637
> Fix linted node: avoid_types_on_closure_parameters

- lib/src/rules.dart
- lib/src/rules/prefer_foreach.dart
- test/rules/prefer_foreach.dart
Fixes https://github.com/dart-lang/linter/issues/634
> New rule: prefer_foreach

- pubspec.yaml
> Remove defunct `cli_util` dep.

- analysis_options.yaml
> Ignore vscode .history files

- lib/src/analyzer.dart
- test/integration_test.dart
- tool/rule.dart
@bwilkerson 
FYI: @alexeieleusis @a14n -- another step when adding new rules.
> Ensure `all.yaml` includes all registered lints.

- .travis.yml
- lib/src/formatter.dart
- test/formatter_test.dart
- tool/travis.sh
- add a benchmark travis bot
- some work towards https://github.com/dart-lang/linter/issues/669
@pq 
We may want to follow this up by selecting a much larger codebase to benchmark against (as well as ensure that all lints are running?).
> add a benchmark travis bot

- example/all.yaml
- lib/src/rules.dart
- lib/src/rules/always_put_required_named_parameters_first.dart
- test/rules/always_put_required_named_parameters_first.dart
> add lint always_put_required_named_parameters_first

- lib/src/rules/avoid_setters_without_getters.dart
> Add description to avoid_setters_without_getters

- lib/src/rules/prefer_const_constructors_in_immutables.dart
> Warning cleanup.

- lib/src/rules/prefer_const_constructors.dart
- lib/src/rules/prefer_const_constructors_in_immutables.dart
- test/rules/prefer_const_constructors.dart
- test/rules/prefer_const_constructors_in_immutables.dart
> fix prefer_const_constructors

- CONTRIBUTING.md
> Add note about crediting in CONTRIBUTORS.

- CHANGELOG.md
- pubspec.yaml
> 0.1.33 change notes.

- doc/RELEASING.md
> Update Release process docs.

- lib/src/rules/prefer_contains.dart
> Fix `prefer_contains` docs (#610).

- lib/src/rules/prefer_final_fields.dart
> Improve `prefer_final_fields` performance (#724).

- pubspec.yaml
> Bump SDK constraint to 2.0.0-dev.infinity

- test/engine_test.dart
> Fix deprecated `getSdkDir` cli_util call.

- pubspec.yaml
- test/engine_test.dart
> Make implicit package deps explicit.

- test/rules/prefer_final_fields.dart
Just to be safe.
Verifies https://github.com/dart-lang/linter/issues/686
> prefer_final_fields: Add unit test for unreproducible bug.

- lib/src/rules/cascade_invocations.dart
This was causing a cast exception.
> cascade_invocations: Don't specify type and rather check for it in condition

- analysis_options.yaml
- bin/linter.dart
- lib/src/rules/always_put_required_named_parameters_first.dart
- lib/src/rules/always_require_non_null_named_parameters.dart
- lib/src/rules/always_specify_types.dart
- lib/src/rules/prefer_const_constructors_in_immutables.dart
- lib/src/rules/prefer_contains.dart
- lib/src/rules/prefer_is_empty.dart
- lib/src/rules/use_to_and_as_if_applicable.dart
- test/engine_test.dart
- test/integration_test.dart
- test/mock_sdk.dart
- test/mocks.dart
- tool/rule.dart
> Enable `prefer_single_quotes`.

- lib/src/rules/unnecessary_overrides.dart
- test/rules/unnecessary_overrides.dart
> improve unnecessary_overrides

- test/mock_sdk.dart
- test/rule_test.dart
_WIP._
_Will update when ready for review._ 👍
----
**UPDATE:** tests look good.  PTAL! 😄 
@scheglov @bwilkerson
> TestResourceProvider path context fixes.

- bin/linter.dart
- lib/src/formatter.dart
> Fix benchmarking.

- analysis_options.yaml
- bin/linter.dart
- lib/src/rules/avoid_slow_async_io.dart
- lib/src/rules/empty_constructor_bodies.dart
- lib/src/rules/implementation_imports.dart
- lib/src/rules/parameter_assignments.dart
- lib/src/rules/prefer_initializing_formals.dart
- lib/src/rules/unnecessary_brace_in_string_interps.dart
- lib/src/rules/unnecessary_overrides.dart
- lib/src/rules/use_to_and_as_if_applicable.dart
- lib/src/util/dart_type_utilities.dart
- lib/src/util/tested_expressions.dart
- test/engine_test.dart
- test/mocks.dart
- test/rule_test.dart
- tool/grind.dart
- tool/rule.dart
Updated enabled lints and did a bunch of cleanup.
@bwilkerson
> Linter delinting.

- analysis_options.yaml
- bin/linter.dart
- lib/src/formatter.dart
- lib/src/rules/avoid_null_checks_in_equality_operators.dart
- lib/src/rules/avoid_positional_boolean_parameters.dart
- lib/src/rules/avoid_returning_this.dart
- lib/src/rules/cascade_invocations.dart
- lib/src/rules/literal_only_boolean_expressions.dart
- lib/src/rules/only_throw_errors.dart
- lib/src/rules/parameter_assignments.dart
- lib/src/rules/prefer_constructors_over_static_methods.dart
- lib/src/rules/prefer_initializing_formals.dart
- lib/src/rules/prefer_single_quotes.dart
- lib/src/rules/recursive_getters.dart
- lib/src/rules/valid_regexps.dart
- lib/src/util/condition_scope_visitor.dart
- lib/src/util/dart_type_utilities.dart
- test/mock_sdk.dart
- test/rule_test.dart
General cleanup and rule enablement:
* avoid_catches_without_on_clauses
* avoid_positional_boolean_parameters
* prefer_expression_function_bodies
* prefer_foreach
@bwilkerson 
FYI: @alexeieleusis @JPaulsen
> Cleanup and dogfood.

- lib/src/rules/always_specify_types.dart
> Remove duplication in `visitTypeName`.

- test/rules/prefer_foreach.dart
@bwilkerson 
FYI @JPaulsen @alexeieleusis 👍
> Improve `prefer_foreach` test coverage.

- example/all.yaml
- lib/src/rules.dart
- lib/src/rules/prefer_bool_in_asserts.dart
- test/rules/prefer_bool_in_asserts.dart
This lint will help for dart-lang/sdk#30326
> add prefer_bool_in_asserts

- example/all.yaml
- lib/src/rules.dart
- lib/src/rules/prefer_typing_uninitialized_variables.dart
- test/rules/prefer_typing_uninitialized_variables.dart
Useful for my project as we are migrating to DDC.
Work done with @bencalabrese
> New rule: Prefer type annotating uninitialized variables and fields.

- lib/src/rules/prefer_is_empty.dart
It was copy and pasted, pointing to isNotEmpty.
> Doc: Fix description of prefer_is_empty

- lib/src/rules/no_duplicate_case_values.dart
Fix small grammar error in no_duplicate_case lint.
> Doc: Fix grammatical error the/than

- CHANGELOG.md
- pubspec.yaml
> Restore `2.0.0` SDK constraint.

- AUTHORS
> Add Rohan to AUTHORS.

- lib/src/rules/prefer_function_declarations_over_variables.dart
- test/rules/prefer_function_declarations_over_variables.dart
> prefer_function_declarations_over_variables: only final declarations or unmutatated vars

- lib/src/rules/prefer_const_constructors_in_immutables.dart
- test/rules/prefer_const_constructors_in_immutables.dart
> prefer_const_constructors_in_immutables handle redirect constructor

- lib/src/rules/prefer_interpolation_to_compose_strings.dart
- test/rules/prefer_interpolation_to_compose_strings.dart
> Allow `+=`  in `prefer_interpolation_to_compose_strings` (#813).

- test/rules/non_constant_identifier_names.dart
> Add test for new function syntax (#805).

- test/rules/library_prefixes.dart
See: #684.
@bwilkerson 
FYI @natebosch
> Regression tests for `library_prefixes` (#684).

- pubspec.yaml
Fixes: #853 
@bwilkerson @devoncarew
> Broaden args package dep (#853)

- lib/src/rules/comment_references.dart
See: #857
@bwilkerson 
FYI: @pschiffmann
> Code reference resolution docs for `comment_references`

- lib/src/rules/package_api_docs.dart
See https://github.com/dart-lang/site-www/issues/517.
cc @kwalrath
> fix link in package_api_docs rule

- example/all.yaml
- lib/src/rules.dart
- lib/src/rules/prefer_const_declarations.dart
- test/rules/prefer_const_declarations.dart
> add lint prefer_const_declarations

- lib/src/rules/avoid_function_literals_in_foreach_calls.dart
> Fix docs for avoid_function_literals_in_foreach_calls

- pubspec.yaml
- test/integration_test.dart
> Removed defunct calls to set `enableAssertInitializer`.

- tool/rule.dart
Surprised it's taken this long to get around to this... 😉 
@bwilkerson @a14n
> Get current year dynamically.

- lib/src/rules/prefer_const_literals_to_create_immutables.dart
- test/rules/prefer_const_literals_to_create_immutables.dart
An attempt to get the build green again.
See: https://github.com/dart-lang/linter/issues/885
@bwilkerson 
cc @a14n
> Update prefer_const_literals_to_create_immutables expectations.

- CONTRIBUTING.md
> Add formatting advice

- lib/src/rules/avoid_relative_lib_imports.dart
- lib/src/util/condition_scope_visitor.dart
- test/all.dart
- test/validate_headers_test.dart
> Test to validate copyright headers.

- lib/src/rules/prefer_const_constructors_in_immutables.dart
> Clean up unused import.

- analysis_options.yaml
- pubspec.yaml
- test/rules/prefer_const_constructors.dart
> Tests validating implicit const handling (#910).

- CONTRIBUTING.md
> Add Code of Conduct link.

- example/all.yaml
- lib/src/rules.dart
- lib/src/rules/avoid_types_as_parameter_names.dart
- test/rules/avoid_types_as_parameter_names.dart
> Add avoid_types_as_parameter_names

- test/formatter_test.dart
- test/mocks.dart
Closes https://github.com/dart-lang/linter/issues/928.
> Fix a type error in formatter_test.dart

- bin/linter.dart
- pubspec.yaml
> Update to use prefered args.addMultiOption(..).

- example/all.yaml
- lib/src/rules.dart
- lib/src/rules/avoid_private_typedef_functions.dart
- test/_data/avoid_private_typedef_functions/lib.dart
- test/_data/avoid_private_typedef_functions/part.dart
- test/integration_test.dart
- test/rules/avoid_private_typedef_functions.dart
> Add avoid_private_typedef_functions

- example/all.yaml
- lib/src/rules.dart
- lib/src/rules/prefer_equal_for_default_values.dart
- test/rules/prefer_equal_for_default_values.dart
> add prefer_equal_for_default_values

- lib/src/utils.dart
- test/utils_test.dart
Fixes: #940.
Needless to say, we'll want some more test cases to make sure we've got this nailed down.  (Moreover we should consider expressing some benchmark expectations in a test somehow.)
cc @bwilkerson 
FYI @davidmorgan
> Library prefix regexp fine-tuning (#940).

- test/rules/library_prefixes.dart
Sorry for the micro fix but while I was in the neighborhood I figured I'd address some warnings.
@bwilkerson
> `library_prefixes` test update to silence warnings.

- codereview.settings
> Remove obselete codereview settings.

- lib/src/rules/prefer_const_literals_to_create_immutables.dart
- lib/src/rules/unnecessary_lambdas.dart
- lib/src/util/leak_detector_visitor.dart
- pubspec.yaml
- test/engine_test.dart
- test/formatter_test.dart
- test/integration_test.dart
- test/mocks.dart
Same PR as #944 but without the last commit (cc97ad0) because `Iterable.whereType` is not yet ready.
> Dart2 clean

- lib/src/ast.dart
- lib/src/rules/prefer_const_declarations.dart
- lib/src/util/leak_detector_visitor.dart
- test/rules/prefer_const_declarations.dart
>  Handle uninitialed var in prefer_const_declarations

- example/all.yaml
- lib/src/rules.dart
- lib/src/rules/avoid_double_and_int_checks.dart
- test/rules/avoid_double_and_int_checks.dart
> add avoid_double_and_int_checks

- doc/WritingLints.MD
> Fix grind docs (#951)

- tool/grind.dart
> Validate grind task.

- example/all.yaml
- lib/src/rules.dart
- lib/src/rules/avoid_js_rounded_ints.dart
- test/rules/avoid_js_rounded_ints.dart
> add avoid_js_rounded_ints

- pubspec.yaml
> Removed unused `plugin` package dependency.

- AUTHORS
See: https://github.com/dart-lang/linter/issues/972#issuecomment-381756913
@bwilkerson
> Add Cameron to AUTHORS.

- example/all.yaml
- lib/src/rules.dart
- lib/src/rules/void_checks.dart
- test/rules/void_checks.dart
> Void checks

- bin/linter.dart
- lib/src/analyzer.dart
- lib/src/formatter.dart
- tool/travis.sh
Fixes benchmarking to properly fail if an error is logged during analysis.
And now things reliably fail when they should.
👍 👍 👍
> Fix benchmarking to fail on errors logged in analysis.

- lib/src/rules/unnecessary_parenthesis.dart
- test/rules/unnecessary_parenthesis.dart
> handle cascade in cascade for unnecessary_parenthesis

- lib/src/rules/prefer_const_literals_to_create_immutables.dart
> add a check to prefer_const_literals_to_create_immutables

- tool/doc.dart
- tool/grind.dart
- tool/rule.dart
> member sorting; import cleanup

- test/engine_test.dart
- test/rule_test.dart
- test/utils_test.dart
> fix deprecated `isInstanceOf` uses

- lib/src/rules/use_to_and_as_if_applicable.dart
> fix issue in use_to_and_as_if_applicable

- lib/src/rules/no_duplicate_case_values.dart
- lib/src/rules/prefer_contains.dart
- lib/src/rules/prefer_is_empty.dart
> update deprecated package references

- test/rules/prefer_const_literals_to_create_immutables.dart
> remove obsolete comments

- tool/travis.sh
> Update `dart` vm flags.

- lib/src/ast.dart
- test/rules/prefer_const_constructors.dart
- test/rules/prefer_const_literals_to_create_immutables.dart
> [WIP] add tests for optional new/const

- lib/src/rules/avoid_null_checks_in_equality_operators.dart
- lib/src/rules/avoid_returning_null.dart
- lib/src/rules/avoid_returning_this.dart
- lib/src/rules/cascade_invocations.dart
- lib/src/rules/invariant_booleans.dart
- lib/src/rules/omit_local_variable_types.dart
- lib/src/rules/prefer_conditional_assignment.dart
- lib/src/rules/prefer_constructors_over_static_methods.dart
- lib/src/rules/prefer_contains.dart
- lib/src/rules/prefer_foreach.dart
- lib/src/rules/prefer_initializing_formals.dart
- lib/src/rules/unnecessary_lambdas.dart
- lib/src/rules/unnecessary_overrides.dart
- lib/src/rules/unnecessary_this.dart
- lib/src/rules/use_rethrow_when_possible.dart
- lib/src/rules/use_setters_to_change_properties.dart
- lib/src/util/condition_scope_visitor.dart
- lib/src/util/dart_type_utilities.dart
- pubspec.yaml
- test/validate_format_test.dart
> bump to analyzer 0.32.2

- example/all.yaml
- lib/src/rules.dart
- lib/src/rules/lines_longer_than_80_chars.dart
- test/_data/lines_longer_than_80_chars/a.dart
- test/integration_test.dart
- test/rules/lines_longer_than_80_chars.dart
Lint for [AVOID lines longer than 80 characters.](https://www.dartlang.org/guides/language/effective-dart/style#avoid-lines-longer-than-80-characters)
> add lint lines_longer_than_80_chars

- lib/src/rules/avoid_positional_boolean_parameters.dart
- test/rules/avoid_positional_boolean_parameters.dart
> Fix avoid_positional_boolean_parameters for implementing classes

- lib/src/rules/prefer_is_empty.dart
* unused local
* unused imports
* ignores
> Cleanup `prefer_is_empty`

- example/all.yaml
- lib/src/rules.dart
- lib/src/rules/curly_braces_in_flow_control_structures.dart
- test/rules/curly_braces_in_flow_control_structures.dart
[DO use curly braces for all flow control structures.](https://www.dartlang.org/guides/language/effective-dart/style#do-use-curly-braces-for-all-flow-control-structures)
> add lint curly_braces_in_flow_control_structures

- analysis_options.yaml
> remove `strong`

- lib/src/formatter.dart
- tool/doc.dart
> formatting fixes

- README.md
- example/google.yaml
Follow-up from: #1068.
See also: #1074.
> Google internal rules

- lib/src/rules/lines_longer_than_80_chars.dart
- test/_data/lines_longer_than_80_chars/a.dart
- test/rules/lines_longer_than_80_chars.dart
> fix lines_longer_than_80_chars for \r

- README.md
Pub analysis flagged this as too short and I listened!
Word-smithing welcome (but do keep it above 60 chars! 😉)
> improved description

- appveyor.yml
Trace VM version to help debug failures.  (See: https://ci.appveyor.com/project/pq/linter#L129.)
> echo dart version

- appveyor.yml
Update appveyor test runs to use `pub run test` pending resolution of https://github.com/dart-lang/linter/issues/1104.
> use pub test

- AUTHORS
@tenhobi: is this a good mail for your attribution?
Thanks again for your contribution!
> add Honza to AUTHORS

- lib/src/cli.dart
- lib/src/rules/prefer_void_to_null.dart
/cc @bwilkerson @MichaelRFairhurst
> hint cleanup

- README.md
Background: trying to force a sync to dart.googlesource.com by landing a
commit.
> Fix minor capitalisation error

- lib/src/rules/invariant_booleans.dart
> fix npe in invariant_booleans

- pubspec.yaml
> remove analyzer dependency_override

- lib/src/rules/overridden_fields.dart
- test/rules/overridden_fields.dart
Fixes https://github.com/dart-lang/sdk/issues/34571
> Fix an NPE in overridden_fields

- lib/src/util/condition_scope_visitor.dart
`computeNode()` is really inefficient, and we need much less info than it provides.
> Don't use computeNode() in invariant_booleans.

- lib/src/rules/await_only_futures.dart
- test/rules/await_only_futures.dart
> allow await null in await_only_futures

- lib/src/rules/use_setters_to_change_properties.dart
- test/rules/use_setters_to_change_properties.dart
> Recommend setter for arrow functions

- lib/src/rules/prefer_int_literals.dart
- test/rules/prefer_int_literals.dart
... and add a test for arguments to Math.max
Fix https://github.com/dart-lang/linter/issues/1230
Fix https://github.com/dart-lang/linter/issues/1231
> Improve prefer_int_literal to detect double literal in list literal

- lib/src/rules/use_setters_to_change_properties.dart
- test/rules/use_setters_to_change_properties.dart
> fix false positive in `use_setters_to_change_properties` (#1246)

- test/rule_test.dart
> re-enable `package_names` test

- .travis.yml
- appveyor.yml
- pubspec.yaml
> bump sdk constraint to 2.1.0

- .travis.yml
- appveyor.yml
(now that there's a 2.0.0 dev build)
> target build to dev

- README.md
> add count badge

- lib/src/rules/unnecessary_parenthesis.dart
- test/rules/unnecessary_parenthesis.dart
Fixes #1284 
The new test fails without the change to lib/
> Fix unnecessary_parenthesis's treatment of function expressions

- lib/src/rules/prefer_void_to_null.dart
Fixes: #1287.
/cc @MichaelRFairhurst @bwilkerson
> promote to stable

- tool/doc.dart
TODO:
* update styling (after #949)
* make pedantic list dynamic
/cc @davidmorgan @bwilkerson
> badge pedantic lints in generated docs

- tool/doc.dart
> fetch pedantic lints from github

- lib/src/util/dart_type_utilities.dart
- test/rules/prefer_final_fields.dart
Fixes https://github.com/dart-lang/sdk/issues/34417
> Fix prefer_final_fields with generic super-classes

- lib/src/analyzer.dart
- lib/src/rules/always_declare_return_types.dart
- lib/src/util/condition_scope_visitor.dart
- lib/src/util/dart_type_utilities.dart
A minor improvement to the messages, and an example of what it will look like when other lints are improved by creating new lint codes (so that we can discuss it).
> Improve the messages for always_declare_return_types

- CONTRIBUTING.md
- README.md
- example/effective-dart.yaml
- lib/src/util/dart_type_utilities.dart
- test/_data/directives_ordering/export_directives_after_import_directives/bad.dart
- test/rules/cascade_invocations.dart
> spelling fixes

- CONTRIBUTING.md
- README.md
- doc/WritingLints.MD
- tool/doc.dart
> https everywhere

- lib/src/rules/invariant_booleans.dart
> Mark invariant_booleans as experimental

- lib/src/rules/avoid_types_as_parameter_names.dart
> tweak grammar in avoid_types_as_parameter_names desctription

- lib/src/rules/test_types_in_equals.dart
> test_types_in_equals wordsmithing

- lib/src/rules/cascade_invocations.dart
- test/rules/cascade_invocations.dart
> Don't encourage cascade on a variable declaration with an await

- lib/src/rules/use_setters_to_change_properties.dart
- test/rules/use_setters_to_change_properties.dart
> handle implements in use_setters_to_change_properties

- lib/src/rules/prefer_final_locals.dart
- pubspec.yaml
- test/rules/prefer_final_locals.dart
> Apply prefer_final_locals to for loop variables as well

- example/all.yaml
- lib/src/rules.dart
- lib/src/rules/prefer_final_in_for_each.dart
- lib/src/rules/prefer_final_locals.dart
- test/rules/prefer_final_in_for_each.dart
- test/rules/prefer_final_locals.dart
Fixes #1346.
Also clears a path for #1342 but there might be some procedure there (like re-releasing 0.1.78 or something).
> Split prefer_final_in_for_each from prefer_final_locals

- tool/doc.dart
Add generated version info to rule descriptions.
Fixes: #1340.
> Generate "since" version / SDK info.

- lib/src/rules/unnecessary_getters_setters.dart
Currently renders like this:
😬 
> fix markdown for `unnecessary_getters_setters`

- lib/src/rules/hash_and_equals.dart
Attempt at improving messaging and docs for `hash_and_equals`.
Word-smithing welcome!  🆘 
Fixes: #976.
> improve docs and messaging for `hash_and_equals`

- test/rules/avoid_positional_boolean_parameters.dart
- test/rules/iterable_contains_unrelated_type.dart
- test/rules/list_remove_unrelated_type.dart
Seems weird that these haven't been addressed yet...
> Fix two analysis errors in tests

- doc/WritingLints.MD
Follow-up from: https://github.com/dart-lang/linter/issues/1362
/cc @bwilkerson @kevmoo
> notes about mocked SDK contents

- lib/src/rules.dart
Closes: #1361.
/cc @kevmoo @bwilkerson
> update doc ref fof disabled uneccessary_getters

- lib/src/rules/avoid_shadowing_type_parameters.dart
> doc grammar fix

- .github/ISSUE_TEMPLATE/issue-report.md
- .github/ISSUE_TEMPLATE/lint-request.md
> add issue templates

- PULL_REQUEST_TEMPLATE.md
> initial PR template

- lib/src/analyzer.dart
- lib/src/rules/annotate_overrides.dart
- lib/src/rules/avoid_positional_boolean_parameters.dart
- lib/src/rules/public_member_api_docs.dart
> migrate to inheritance_manager2

- example/all.yaml
- lib/src/rules/super_goes_last.dart
> deprecate super_goes_last

- test/rules/unnecessary_parenthesis.dart
> added `UnnecessaryParenthesis` test case

- lib/src/rules/prefer_collection_literals.dart
- pubspec.yaml
- test/mock_sdk.dart
- test/rules/prefer_collection_literals.dart
> update prefer_collection_literals to support sets

- lib/src/rules/avoid_positional_boolean_parameters.dart
- lib/src/rules/prefer_collection_literals.dart
Cleanup some unnecessary imports.
> remove unnecessary imports

- lib/src/rules/prefer_const_constructors_in_immutables.dart
- lib/src/util/dart_type_utilities.dart
- test/rules/null_closures.dart
> test for cycles in extendsClass

- test/mocks.dart
flagged in the latest dev build:
> fix invalid overrides

- lib/src/analyzer.dart
- lib/src/rules.dart
- pubspec.yaml
- test/rule_test.dart
> cache linter version on rule registration

- lib/src/rules/directives_ordering.dart
- lib/src/rules/null_closures.dart
- lib/src/rules/prefer_initializing_formals.dart
- lib/src/rules/prefer_interpolation_to_compose_strings.dart
- lib/src/rules/public_member_api_docs.dart
- lib/src/rules/use_string_buffers.dart
- lib/src/util/dart_type_utilities.dart
- lib/src/util/tested_expressions.dart
> Fix code that is now triggering lints

- test/mocks.dart
> remove unused import

- lib/src/rules/always_put_control_body_on_new_line.dart
- lib/src/rules/always_specify_types.dart
> migrate to flutter.dev links

- lib/src/rules/always_put_control_body_on_new_line.dart
- lib/src/rules/curly_braces_in_flow_control_structures.dart
- lib/src/rules/literal_only_boolean_expressions.dart
- lib/src/rules/omit_local_variable_types.dart
- lib/src/rules/prefer_foreach.dart
- lib/src/rules/unnecessary_statements.dart
- lib/src/rules/use_string_buffers.dart
- lib/src/util/condition_scope_visitor.dart
See: https://github.com/dart-lang/sdk/issues/35569
/cc @stereotype441 @bwilkerson
> migrate to new ForStatement2 API

- pubspec.yaml
> add documentation link

- lib/src/rules/unnecessary_const.dart
- lib/src/rules/unnecessary_new.dart
> fix unnecessary_{const,new} doc typos

- lib/src/rules/no_adjacent_strings_in_list.dart
- lib/src/rules/prefer_final_in_for_each.dart
- lib/src/rules/prefer_foreach.dart
- lib/src/rules/prefer_void_to_null.dart
See https://dart-review.googlesource.com/c/sdk/+/95665/ for the
complete set of analyzer APIs that are being deprecated.
> Additional migrations to prepare for the "UI as code" feature.

- pubspec.yaml
> bump sdk to 2.2.0

- lib/src/rules/prefer_const_literals_to_create_immutables.dart
> fix description typo

- lib/src/rules/prefer_const_constructors_in_immutables.dart
- lib/src/util/dart_type_utilities.dart
> set literal conversions

- doc/WritingLints.MD
> add links to the dart spec

- lib/src/rules/file_names.dart
fixes #1482
/cc @kevmoo @bwilkerson
> add dashed name example

- lib/src/util/condition_scope_visitor.dart
> removed deprecated AST node doc references

- pubspec.yaml
On the advice of `pana`:
Details are in the README anyway...
Word-smithing welcome.
/cc @bwilkerson @kwalrath
> shorten package description

- tool/baseline/pana.json
Recent fixes, bring us to 100!
🥇 🥇 🥇 
> update pana baselines 🥇 

- example/all.yaml
- lib/src/rules.dart
- lib/src/rules/prefer_asserts_with_message.dart
- test/rules/prefer_asserts_with_message.dart
> add prefer_asserts_with_message

- lib/src/rules/always_put_control_body_on_new_line.dart
- lib/src/rules/curly_braces_in_flow_control_structures.dart
- lib/src/rules/literal_only_boolean_expressions.dart
- lib/src/rules/no_adjacent_strings_in_list.dart
- lib/src/rules/omit_local_variable_types.dart
- lib/src/rules/prefer_final_in_for_each.dart
- lib/src/rules/prefer_foreach.dart
- lib/src/rules/prefer_void_to_null.dart
- lib/src/rules/unnecessary_parenthesis.dart
- lib/src/rules/unnecessary_statements.dart
- lib/src/rules/use_string_buffers.dart
- lib/src/util/condition_scope_visitor.dart
- pubspec.yaml
- tool/scorecard.dart
Note that  https://github.com/dart-lang/sdk/issues/36361 should land in the SDK before a linter with these updated deps can be pulled in.
> bump to analyzer 0.36.0

- lib/src/rules/experiments/spread_collections.dart
- test/integration_test.dart
- test/rule_test.dart
- test/rules/experiments/experiments.dart
- test/rules/experiments/spread_collections/analysis_options.yaml
- test/rules/experiments/spread_collections/spread_collections.dart
See: #1410.
* adds support for lint experiments (defined in `rules/experiments`)
* adds `spread_collections` first cut
> spread_collections experiment

- lib/src/rules/experiments/spread_collections.dart
> remove unused import [TBR]

- .travis.yml
- tool/bot/version_check.dart
- tool/travis.sh
> release bot

- test/rules/prefer_spread_collections.dart
Clarifying test case captured from discussion in https://github.com/flutter/flutter/pull/30784.
> new spread test case

- lib/src/rules/prefer_collection_literals.dart
- test/rules/prefer_collection_literals.dart
> fix false positive in prefer_collection_literals

- doc/WritingLints.MD
> mechanics example tweak

- lib/src/rules/prefer_iterable_whereType.dart
- test/rules/prefer_iterable_whereType.dart
> fix false positive in prefer_iterable_whereType for is!

- lib/src/rules/prefer_spread_collections.dart
- test/rules/prefer_spread_collections.dart
> don’t lint for spreads in const contexts

- lib/src/util/dart_type_utilities.dart
- test/rules/unrelated_type_equality_checks.dart
> Fix unrelated_type_equality_checks false negative with functions

- lib/src/rules/unnecessary_await_in_return.dart
- test/rules/unnecessary_await_in_return.dart
> fix issue 1518

- test/configs/control-flow-collections/analysis_options.yaml
No longer adding value w/ UI-as-code enabled by default.
> remove the control flow collections test config

- lib/src/ast.dart
- test/configs/README
- test/integration_test.dart
- test/rules/prefer_const_constructors_in_immutables.dart
> analyzer 0.36.1 updates for prefer_const_constructors_in_immutables

- lib/src/rules/type_annotate_public_apis.dart
- test/rules/type_annotate_public_apis.dart
> relax type_annotate_public_apis to not lint const var decls

- test/rules/unnecessary_lambdas.dart
> updated test to include generic case

- example/all.yaml
- lib/src/rules.dart
- lib/src/rules/prefer_double_quotes.dart
- lib/src/rules/prefer_single_quotes.dart
- test/integration_test.dart
- test/rules/prefer_double_quotes.dart
> Add lint prefer_double_quotes

- analysis_options.yaml
- lib/src/rules/always_put_control_body_on_new_line.dart
- lib/src/rules/lines_longer_than_80_chars.dart
- lib/src/rules/prefer_bool_in_asserts.dart
- lib/src/rules/prefer_const_constructors_in_immutables.dart
- lib/src/rules/provide_deprecation_message.dart
- lib/src/rules/unnecessary_statements.dart
- pubspec.yaml
fyi @devoncarew (who predicted as much...)
> pedantic 1.6.0 fixes [TBR]

- lib/src/rules/prefer_const_constructors_in_immutables.dart
- pubspec.yaml
- test/integration_test.dart
- test/rules/prefer_const_constructors_in_immutables.dart
see: #1537
/cc @scheglov @a14n
> update to new linter context API

- lib/src/rules/curly_braces_in_flow_control_structures.dart
- test/rules/curly_braces_in_flow_control_structures.dart
> fix curly_braces_in_flow_control_structures

- analysis_options.yaml
- pubspec.yaml
> de-dup lints defined in pedantic

- lib/src/rules/prefer_asserts_in_initializer_lists.dart
- test/rules/prefer_asserts_in_initializer_lists.dart
Fixes: #1557.
/cc @bwilkerson @stereotype441
> fix false positive in prefer_asserts_in_initializer_lists

- tool/doc.dart
> update pedantic source fetching to the new versioned model

- tool/since.dart
> note to update linter version cache

- lib/src/util/dart_type_utilities.dart
> fix null reference

- tool/since/linter.yaml
> add `unsafe_html` to lint version cache

- lib/src/rules/prefer_const_constructors.dart
Fixes #1592
/cc @scheglov 
/fyi @a14n
> fix const constructor checking w/ type params

- .github/move.yml
This never worked as written 😬.
Also updated w/ aliases from the SDK.
Fixes: #1599.
/cc @devoncarew @kevmoo
> fix move.yml syntax

- tool/doc.dart
> fix doc format for unreleased SDKs

- lib/src/rules/use_string_buffers.dart
> doc grammar tweak

- lib/src/rules/prefer_final_locals.dart
/cc @alexeieleusis @bwilkerson
> tweak description

- CONTRIBUTING.md
- README.md
- doc/WritingLints.MD
- example/readme.md
- lib/src/rules/avoid_init_to_null.dart
- lib/src/rules/camel_case_types.dart
- lib/src/rules/directives_ordering.dart
- lib/src/rules/empty_constructor_bodies.dart
- lib/src/rules/implementation_imports.dart
- lib/src/rules/one_member_abstracts.dart
- lib/src/rules/package_api_docs.dart
- lib/src/rules/prefer_equal_for_default_values.dart
- lib/src/rules/slash_for_doc_comments.dart
- lib/src/rules/super_goes_last.dart
- lib/src/rules/type_annotate_public_apis.dart
- lib/src/rules/type_init_formals.dart
- lib/src/rules/unnecessary_getters.dart
- lib/src/rules/unnecessary_getters_setters.dart
- lib/src/rules/unnecessary_this.dart
- lib/src/util/dart_type_utilities.dart
- tool/doc.dart
> link updates

- tool/crawl.dart
Scoring broke with the new "include" scheme for versioned pedantic options.  This fixes that.
> fix pedantic scoring to work w/ includes [tbr]

- lib/src/ast.dart
- lib/src/util/dart_type_utilities.dart
Baby-steps towards NNBD preparedness.
> some implicit cast tidying

- analysis_options.yaml
> doc some pedantic-included rules

- lib/src/analyzer.dart
- lib/src/cli.dart
- lib/src/formatter.dart
- lib/src/rules/always_put_required_named_parameters_first.dart
- lib/src/rules/annotate_overrides.dart
- lib/src/rules/avoid_setters_without_getters.dart
- lib/src/rules/no_duplicate_case_values.dart
- lib/src/rules/prefer_contains.dart
- lib/src/rules/test_types_in_equals.dart
- lib/src/util/tested_expressions.dart
- test/engine_test.dart
- test/integration_test.dart
- test/mock_sdk.dart
- test/rule_test.dart
- test/util/test_utils.dart
> more casts (nnbd prep)

- pubspec.yaml
> bump to latest analyzer

- lib/src/rules/invariant_booleans.dart
- tool/parse.dart
> analyzer API call update; unused import cleanup

- pubspec.yaml
(required to play nice w/ evolving `StreamTransformer` APIs)
> bump github package dep

- lib/src/ast.dart
- lib/src/rules/prefer_const_constructors.dart
- test/rules/prefer_const_constructors.dart
> literal const fix

- test/configs/extension_methods/analysis_options.yaml
> add a test config for extension methods

- pubspec.yaml
> bump to analyzer 0.38.0

- tool/rule.dart
> drop explictit `new` from codegen

- lib/src/rules/camel_case_extensions.dart
- test/rules/experiments/camel_case_extensions/analysis_options.yaml
- test/rules/experiments/camel_case_extensions/camel_case_extensions.dart
- test/rules/experiments/experiments.dart
> new lint: camel_case_extensions

- lib/src/rules/slash_for_doc_comments.dart
- test/rules/experiments/experiments.dart
- test/rules/experiments/slash_for_doc_comments/analysis_options.yaml
- test/rules/experiments/slash_for_doc_comments/slash_for_doc_comments.dart
> Extension support for `slash_for_doc_comments`

- test/rules/experiments/experiments.dart
- test/rules/experiments/type_annotate_public_apis/analysis_options.yaml
- test/rules/experiments/type_annotate_public_apis/type_annotate_public_apis.dart
> validate type annotations are checked in extensions

- lib/src/ast.dart
- lib/src/rules/public_member_api_docs.dart
- test/rule_test.dart
- test/rules/experiments/experiments.dart
- test/rules/experiments/public_member_api_docs/analysis_options.yaml
- test/rules/experiments/public_member_api_docs/lib/public_member_api_docs.dart
- test/rules/experiments/public_member_api_docs/pubspec.yaml
> public_member_api_docs extension support

- lib/src/rules/avoid_returning_this.dart
- test/rules/experiments/avoid_returning_this/analysis_options.yaml
- test/rules/experiments/avoid_returning_this/avoid_returning_this.dart
- test/rules/experiments/experiments.dart
> avoid_returning_this extension support

- lib/src/util/dart_type_utilities.dart
- test/rules/experiments/avoid_positional_boolean_parameters/analysis_options.yaml
- test/rules/experiments/avoid_positional_boolean_parameters/avoid_positional_boolean_parameters.dart
- test/rules/experiments/experiments.dart
> extension support for avoid_positional_boolean_parameters

- lib/src/util/dart_type_utilities.dart
- test/rules/experiments/experiments.dart
- test/rules/experiments/use_setters_to_change_properties/analysis_options.yaml
- test/rules/experiments/use_setters_to_change_properties/use_setters_to_change_properties.dart
> make use_setters_to_change_properties extension-aware

- pubspec.yaml
See: https://github.com/dart-lang/pana/issues/557
> add repo details

- tool/scorecard.dart
> update lint w/ fix analysis

- analysis_options.yaml
- lib/src/rules/lines_longer_than_80_chars.dart
- lib/src/util/unrelated_types_visitor.dart
- pubspec.yaml
> enable prefer_spreads

- analysis_options.yaml
- tool/grind.dart
> enable prefer_inlined_adds

- lib/src/rules/use_to_and_as_if_applicable.dart
> allow for null raw expressions

- lib/src/ast.dart
I assume this is better than `PhysicalResourceProvider.INSTANCE`?
> get resource provider from session

- test/rule_test.dart
Improves test failure reporting.
> make spelunking featureSet aware

- lib/src/rules/prefer_collection_literals.dart
I think this TODO was misleading.
/cc @scheglov
> remove stale todo

- lib/src/rules/use_full_hex_values_for_flutter_colors.dart
> fix empty arg list access

- lib/src/rules/overridden_fields.dart
> fix unsafe cast

- lib/src/rules/prefer_const_constructors.dart
> remove foundTypeParamElement hack

- AUTHORS
> add Jawahar to AUTHORS

- lib/src/rules/diagnostic_describe_all_properties.dart
- test/rules/diagnostic_describe_all_properties.dart
> lint when no debug methods are defined

- lib/src/rules/unsafe_html.dart
no need for a raw string here!
> fix rule description

- pubspec.yaml
- test/mock_packages/flutter/lib/widgets.dart
- test/mock_packages/flutter/pubspec.yaml
- test/rules/.mock_packages
- test/rules/diagnostic_describe_all_properties.dart
- test/rules/sort_child_properties_last.dart
> flutter mocking

- tool/rule.dart
> fix rule codegen code formatting

- lib/src/util/flutter_utils.dart
- test/mock_packages/flutter/lib/foundation.dart
- test/mock_packages/flutter/lib/src/foundation/diagnostics.dart
- test/mock_packages/flutter/lib/src/foundation/key.dart
- test/mock_packages/flutter/lib/src/widgets/basic.dart
- test/mock_packages/flutter/lib/src/widgets/container.dart
- test/mock_packages/flutter/lib/src/widgets/framework.dart
- test/mock_packages/flutter/lib/widgets.dart
- test/rules/diagnostic_describe_all_properties.dart
Preliminary to fixing: https://github.com/dart-lang/linter/pull/1776#discussion_r336630514
/cc @scheglov
> flutter package mocking

- example/all.yaml
- lib/src/rules.dart
- lib/src/rules/avoid_unnecessary_containers.dart
- lib/src/util/flutter_utils.dart
- test/mock_packages/flutter/lib/widgets.dart
- test/rules/avoid_unnecessary_containers.dart
See: #1560.
/cc @jacob314 @scheglov
> avoid_unnecessary_containers

- test/_data/always_require_non_null_named_parameters/lib.dart
- test/_data/prefer_const_constructors_in_immutables/lib.dart
- test/integration_test.dart
- test/mock_packages/meta/lib/meta.dart
- test/mock_packages/meta/pubspec.yaml
- test/rules/.mock_packages
- test/rules/always_put_required_named_parameters_first.dart
- test/rules/always_require_non_null_named_parameters.dart
- test/rules/always_specify_types.dart
- test/rules/avoid_equals_and_hash_code_on_mutable_classes.dart
- test/rules/prefer_const_constructors.dart
- test/rules/prefer_const_constructors_in_immutables.dart
- test/rules/prefer_const_literals_to_create_immutables.dart
- test/rules/unnecessary_getters_setters.dart
Long time in the coming...
/cc @scheglov
> fix mocking of `package:meta`

- pubspec.yaml
Deps update.
(Fixes the pana benchmark.)
> udpate to latest analyzer

- lib/src/rules/prefer_final_fields.dart
- test/rules/prefer_final_fields.dart
Fixes dart-lang/sdk/issues/39114
> ignore non-mutating prefix ops

- pubspec.yaml
See: https://github.com/dart-lang/dart_style/issues/866
> update dart_style dep

- lib/src/rules/prefer_is_not_operator.dart
- test/engine_test.dart
> warning cleanup && wordsmithing

- lib/src/rules/always_specify_types.dart
- lib/src/rules/avoid_renaming_method_parameters.dart
- lib/src/util/flutter_utils.dart
> update typeParam access

- analysis_options.yaml
- lib/src/rules/avoid_unused_constructor_parameters.dart
- lib/src/util/leak_detector_visitor.dart
- test/mocks.dart
These are getting favorable attention in internal discussions and likely to become pedantic.
> enable lints

- analysis_options.yaml
- lib/src/rules/control_flow_in_finally.dart
- lib/src/rules/invariant_booleans.dart
- lib/src/rules/overridden_fields.dart
- test/engine_test.dart
- test/integration_test.dart
- test/util/test_utils.dart
- tool/scorecard.dart
More lints that are getting favorable internal attention.
> de-linting (keeping ahead of the Joneses)

- analysis_options.yaml
> comment cleanup

- analysis_options.yaml
- lib/src/ast.dart
- lib/src/util/dart_type_utilities.dart
- lib/src/util/leak_detector_visitor.dart
- lib/src/util/tested_expressions.dart
- test/engine_test.dart
- tool/rule.dart
More lints that are being considered favorably for `pedantic`.
> more linting

- lib/src/rules/file_names.dart
- lib/src/util/ascii_utils.dart
- lib/src/utils.dart
- pubspec.yaml
- test/all.dart
- test/ascii_utils_test.dart
- test/utils_test.dart
- tool/benchmark.dart
Improves `file_names` performance and adds some breadcrumbs for future perf improvements (see: #1828).
Fixes #1803.
> file_name check improvements; benchmarking

- lib/src/rules/unnecessary_overrides.dart
- test/rules/unnecessary_overrides.dart
> allow overrides that add annotations

- tool/benchmark.dart
> doc microbenchmark

- lib/src/formatter.dart
- lib/src/util/score_utils.dart
- pubspec.yaml
- tool/crawl.dart
> annotate pedantic lint benchmarks

- pubspec.yaml
- tool/crawl.dart
- tool/scorecard.dart
> update to new `package:github` API

- pubspec.yaml
- test/mock_packages/fixnum/pubspec.yaml
> cleanup pub (lish) warnings

- lib/src/analyzer.dart
- lib/src/rules/no_duplicate_case_values.dart
- lib/src/rules/unnecessary_this.dart
- lib/src/util/dart_type_utilities.dart
- pubspec.yaml
> update to latest analyzer APIs

- example/all.yaml
- lib/src/rules.dart
- lib/src/rules/no_logic_in_create_state.dart
- lib/src/util/flutter_utils.dart
- test/rules/no_logic_in_create_state.dart
Fixes: #1875.
Feedback and word-smithing welcome and **appreciated**!
/cc @bwilkerson @rrousselGit
> no_logic_in_create_state

- lib/src/rules/comment_references.dart
> update BAD sample

- lib/src/rules/avoid_as.dart
- test/rules/avoid_as.dart
> narrow avoid_as reporting to type annotation node

- tool/travis.sh
> debug coverage

- lib/src/rules/always_require_non_null_named_parameters.dart
> update description for always_require_non_null_named_parameters

- tool/baseline/pana.json
Work-around for: https://github.com/dart-lang/pana/issues/591.
> lower baseline (temp) [TBR]

- lib/src/meta.dart
> @IncompatibleWith

- lib/src/meta.dart
- lib/src/rules/prefer_final_locals.dart
- lib/src/rules/unnecessary_final.dart
- lib/src/util/lint_cache.dart
- test/all.dart
- test/validate_metadata.dart
> IncompatibleWith validation

- lib/src/rules/package_api_docs.dart
- tool/doc.dart
> update dart.dev links

- tool/baseline/pana.json
Fixes: https://github.com/dart-lang/linter/issues/1906
> Restore maintenance baseline

- README.md
> typo and eol comment notes

- test/mock_packages/meta/lib/meta.dart
- test/mock_packages/meta/pubspec.yaml
> Update mock meta

- lib/src/rules/prefer_const_constructors_in_immutables.dart
> fix description

- README.md
> style package links consistently

- lib/src/rules/annotate_overrides.dart
- lib/src/rules/avoid_positional_boolean_parameters.dart
- lib/src/rules/diagnostic_describe_all_properties.dart
- lib/src/rules/public_member_api_docs.dart
- lib/src/util/dart_type_utilities.dart
- pubspec.yaml
> update to analyzer 0.39.3

- test/rules/prefer_const_literals_to_create_immutables.dart
See: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8892264525780591248/+/steps/analyze_flutter/0/stdout
/cc @scheglov
> regression test

- lib/src/rules/unrelated_type_equality_checks.dart
> fix null type access

- lib/src/rules/avoid_redundant_argument_values.dart
- test/rules/avoid_redundant_argument_values.dart
Follow-up from: https://dart-review.googlesource.com/c/sdk/+/130160.
> check for trailing optional positional args in avoid_redundant_argument_values

- CHANGELOG.md
> update 0.1.108 entry

- analysis_options.yaml
- lib/src/formatter.dart
- test/rule_test.dart
> + avoid_redundant_argument_values

- lib/src/rules/invariant_booleans.dart
- lib/src/rules/null_closures.dart
- lib/src/rules/prefer_contains.dart
- lib/src/rules/prefer_int_literals.dart
- lib/src/rules/unrelated_type_equality_checks.dart
- lib/src/rules/use_full_hex_values_for_flutter_colors.dart
- lib/src/rules/use_setters_to_change_properties.dart
- lib/src/util/dart_type_utilities.dart
- lib/src/util/unrelated_types_visitor.dart
> update type name accesses

- lib/src/rules/unnecessary_this.dart
So, that linter stops using internal `ScopedVisitor`.
> Update unnecessary_this to use LinterContext.resolveNameInScope()

- lib/src/rules/unnecessary_lambdas.dart
- test/rules/unnecessary_lambdas.dart
> Fix unnecessary_lambdas with generics

- lib/src/rules/unnecessary_final.dart
- test/rules/unnecessary_final.dart
> Fix unnecessary_final: don't fire for fields.

- README.md
> add ignore_for_file example

- lib/src/rules/prefer_double_quotes.dart
- lib/src/rules/prefer_final_locals.dart
- lib/src/rules/prefer_single_quotes.dart
- lib/src/rules/unnecessary_final.dart
> tag incompatible rules (finals and quotes)

- lib/src/rules/always_specify_types.dart
- lib/src/rules/omit_local_variable_types.dart
> tag incompatible type rules

- example/all.yaml
- lib/src/rules.dart
- lib/src/rules/missing_whitespace_between_adjacent_strings.dart
- test/rules/missing_whitespace_between_adjacent_strings.dart
Related to flutter/flutter#48090
> add missing_whitespace_between_adjacent_strings

- lib/src/rules/avoid_as.dart
- lib/src/rules/prefer_const_declarations.dart
Minor doc cleanup related to NNBD
> clean up docs for two rules

- pubspec.yaml
attempt at addressing: #1974 
(landing TBR in a hopes of fixing the build.)
> pin github package [TBR]

- tool/scorecard.dart
> harden scoring (more)

- .travis.yml
- tool/travis.sh
Introduce a new `score` BOT.
Scoring is best effort and shouldn't break the build.
Related to: #1974.
> + score bot

- pubspec.yaml
Fixes: https://github.com/dart-lang/linter/issues/1979
> update to github v6.0.5

- lib/src/rules/avoid_web_libraries_in_flutter.dart
- test/_data/avoid_web_libraries_in_flutter/web_plugin/pubspec.yaml
Fixes #1984
/cc @hterkelsen @bwilkerson
> fix flutter plugin check

- tool/crawl.dart
> fix future error handling

- lib/src/rules/omit_local_variable_types.dart
- lib/src/rules/prefer_typing_uninitialized_variables.dart
See: https://github.com/dart-lang/linter/issues/1964.
> tag incompatible rules

- analysis_options.yaml
- lib/src/rules/unawaited_futures.dart
> + prefer_is_not_operator

- .travis.yml
- tool/travis.sh
See: https://github.com/dart-lang/linter/issues/2014
> disable unstable score bot

- lib/src/rules/omit_local_variable_types.dart
- lib/src/rules/prefer_typing_uninitialized_variables.dart
> fix rule compatibility

- lib/src/rules/avoid_private_typedef_functions.dart
- test/integration_test.dart
Includes some general code cleanup.
> Improve the highlight range for avoid_private_typedef_functions

- lib/src/rules/one_member_abstracts.dart
- test/rules/one_member_abstracts.dart
Fixes: https://github.com/dart-lang/linter/issues/1826.
> allow one member abstracts implementing interfaces

- tool/bot/rule_doc_check.dart
- tool/bot/version_check.dart
- tool/crawl.dart
- tool/travis.sh
Fixes: #2034 
See also: https://dart-review.googlesource.com/c/sdk/+/139745
> validate published doc urls

- lib/src/rules/avoid_unused_constructor_parameters.dart
- test/rules/avoid_unused_constructor_parameters.dart
> allow unused `_` params

- tool/bot/rule_doc_check.dart
> cleanup imports

- lib/src/rules/flutter_style_todos.dart
- lib/src/rules/lines_longer_than_80_chars.dart
Addresses a change in analyzer 0.39.5.
> fix for API change (and incompatible inference)

- analysis_options.yaml
- lib/src/rules/unsafe_html.dart
- test/rules/unsafe_html.dart
Account for implicit targets on assignments and method invocations.
Fixes #2056
> Check unsafe attributes and methods on extensions

- lib/src/rules/avoid_types_as_parameter_names.dart
- test/rules/avoid_types_as_parameter_names.dart
> check catch clauses in `avoid_types_as_parameter_names`

- pubspec.yaml
- test/rules/unsafe_html.dart
Bump analyzer to 0.39.7.
With new analyzer, improve unsafe_html tests.
> Bump analyzer to 0.39.7; improve unsafe_html tests

- lib/src/rules/avoid_redundant_argument_values.dart
> use computeConstantValue()

- doc/WritingLints.MD
> Update mock location

- lib/src/rules/prefer_mixin.dart
- lib/src/util/dart_type_utilities.dart
- test/rules/prefer_mixin.dart
Fixes: https://github.com/dart-lang/linter/issues/2082
> add allowed “legacy” SDK class mixins

- lib/src/rules/type_annotate_public_apis.dart
- test/rules/type_annotate_public_apis.dart
> allow inferred types in final field assignments

- example/all.yaml
- lib/src/rules.dart
- lib/src/rules/exhaustive_cases.dart
- lib/src/util/dart_type_utilities.dart
- test/rules/exhaustive_cases.dart
> new lint: exhaustive_cases

- lib/src/rules/exhaustive_cases.dart
- test/_data/exhaustive_cases/a.dart
- test/_data/exhaustive_cases/e.dart
- test/integration_test.dart
Follow-up from https://github.com/dart-lang/linter/pull/2090.
> fix for prefixed identifiers

- example/all.yaml
- lib/src/rules.dart
- lib/src/rules/no_default_cases.dart
- test/rules/no_default_cases.dart
> new lint: no_default_cases

- example/all.yaml
- lib/src/rules.dart
- lib/src/rules/do_not_use_environment.dart
- test/rules/do_not_use_environment.dart
> + do_not_use_environment

- lib/src/rules/overridden_fields.dart
- lib/src/util/dart_type_utilities.dart
- lib/src/util/unrelated_types_visitor.dart
> prefer isDartCoreObject

- lib/src/test_utilities/annotation.dart
- lib/src/test_utilities/test_resource_provider.dart
- test/rule_test.dart
- test/util/annotation.dart
- test/util/annotation_matcher.dart
- test/util/annotation_test.dart
- test/util/test_resource_provider.dart
> move test utilities

- lib/src/rules/do_not_use_environment.dart
- lib/src/rules/missing_whitespace_between_adjacent_strings.dart
- lib/src/rules/prefer_const_constructors.dart
- lib/src/rules/prefer_for_elements_to_map_fromIterable.dart
- lib/src/rules/use_full_hex_values_for_flutter_colors.dart
- lib/src/rules/valid_regexps.dart
- lib/src/rules/void_checks.dart
> analyzer API use updates

- lib/src/cli.dart
- lib/src/rules/use_to_and_as_if_applicable.dart
- test/mocks.dart
- tool/doc.dart
- tool/rule.dart
- tool/spelunk.dart
> (cleanup) remove redundant defaults

- lib/src/cli.dart
> remove strong-mode flag

- lib/src/cli.dart
- test/engine_test.dart
See https://github.com/dart-lang/sdk/issues/41244
> Remove support for --package-root.

- lib/src/rules/prefer_is_empty.dart
- test/rules/prefer_is_empty.dart
Fixes https://github.com/dart-lang/linter/issues/1719
> special case assert initializers and  const contexts in `prefer_is_empty`

- lib/src/rules/exhaustive_cases.dart
- pubspec.yaml
> update to use reportErrorForOffset API

- lib/src/rules/unnecessary_lambdas.dart
- test/rules/unnecessary_lambdas.dart
Fixes: https://github.com/dart-lang/linter/issues/1561.
> check for  tearoff assignability in `unnecessary_lambdas`

- lib/src/rules/prefer_relative_imports.dart
- test/_data/prefer_relative_imports/_packages
- test/_data/prefer_relative_imports/lib/main.dart
- test/integration_test.dart
> Fix prefer_relative_imports when using path dependencies
